### ISSUE TITLE
Reduce Password Requirements

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#1]
Currently we have four requirements:
- Capital letter
- Lowercase letter
- number
- symbol

Based on user feedback, we should reduce the requirements to 3 out of these 4 requirements (any three of the four will work)

We also should confirm when a user enters one of the requirements (ask @joshdanielson for good examples)

**Comment by situatedbit** [comment]
estimate: 2

**Comment by IagoSRL** [comment]
1

**Comment by joshdanielson** [comment]
4

**Comment by IagoSRL** [comment]
Implemented, both client and server parts, tested; is for additional testing at *dev*, in case someone found an error re-open and let me know, thanks.

**Comment by IagoSRL** [comment]
Implementation note: at client side, the new 'PasswordValidator' class stores at individual fields the result of each tested requirement: length, upper, lower, number, symbol; they can be used by an UI that shows what requirements are met by the typed paImplementation note: at client side, the new 'PasswordValidator' class stores at individual fields the result of each tested requirement: length, upper, lower, number, symbol; they can be used by an UI that shows what requirements are met by the typed password.ssword.

**Comment by joshdanielson** [comment]
@IagoSRL seems great! Tested all different combinations.
