### ISSUE TITLE
Bug S2 Client is unable to see pending booking details

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#103]
Site: live

Browsers: Firefox, Chrome

Clients are unable to see details about pending bookings from the client dashboard.

To reproduce: 
1. Client books a service and chooses three time slots for the professional to choose.
2. Navigate back to client dashboard.
3. Before professional confirms the booking, in the client dashboard, there is an item _1 pending appointment requests_, but it cannot be clicked on.
4. In the message inbox, click on the message pertaining to the booking. In the conversation detail there is a button _Open Booking_. 
5. Click on _Open Booking_. 
6. The client expects to see details about the booking, but instead sees the login page, even though the client is already logged in.

![01-open-booking](https://cloud.githubusercontent.com/assets/6644016/21790159/21f6ff08-d68f-11e6-9d66-d37cdf745d10.png)

![02-login-screen](https://cloud.githubusercontent.com/assets/6644016/21790162/26799540-d68f-11e6-9118-018cd6dd2efa.png)

**Comment by IagoSRL** [comment]
The bug described in points 4, 5, 6 were fixed recently on issue #5

**Comment by joshdanielson** [comment]
- try to access through the client calendar
- try to access through the booking request

**Comment by situatedbit** [comment]
@joshdanielson 

This item references two issues. The second issue: accessing appointment card through inbox _Open Booking_ link, has been fixed. 

The first is accessing pending requests from the dashboard. Since this is a new feature, I created a new issue: https://github.com/loconomics/loconomics/issues/320.
