### ISSUE TITLE
Bug: S1 Top time slot changes between booking request cards

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#105]
Site: live

Browser: Firefox, (did not try other browsers)

As a professional, when I go to _Open Booking_ through the Inbox interface in order to confirm a booking time created by a client, I am able to navigate left and right through several booking screens for a single booking, but the appointment times that I can choose _change_ depending on which card I'm on.

As I move left and right between the different booking cards, the top-most time changes, but the bottom two do not.

Here are some screenshots and the URLs I see when I navigate through my example. Note how the topmost time slot matches one of the other two. This is because that time slot changes with the card while the other two don't.

1. Initial Page: https://loconomics.com/#!/appointment/425/booking (left-most dot highlighted)
2. Navigate with right arrow: https://loconomics.com/#!appointment/2017-01-12T08:00:00.000Z/7102097 (middle dot highlighted)
3. Navigate right again: https://loconomics.com/#!appointment/2017-01-12T08:00:00.000Z/7102098 (right-most dot highlighted)

![01-arrow](https://cloud.githubusercontent.com/assets/6644016/21791169/ea91f0f2-d695-11e6-8d16-700f6a89ccc2.png)

Here a time has been confirmed, and the radio buttons are all the same time:
![02-three-same-slots](https://cloud.githubusercontent.com/assets/6644016/21791172/ee682c28-d695-11e6-80b3-7266ae2edda1.png)

This time has already been confirmed, but not on the "alternate screens": 
![professional-confirming-booking-request-multiple-cards-same-appointment-already-confirmed](https://cloud.githubusercontent.com/assets/6644016/21791173/f28ed1ee-d695-11e6-8f2e-6735166ba5e3.jpg)

**Comment by situatedbit** [comment]
I did _not_ see this problem when the booking request time choices were on _three separate days_.

**Comment by situatedbit** [comment]
Initially, this issue reflected my confusion about how the calendar and appointment card slots worked. Now that I've spent more time with this feature, I rewrote the initial issue to focus on one bug, uncovered a few separate bugs (which I will report), and have ideas for how to handle the UI issues around navigating between appointments and calendar slots. I'm going to detail my thoughts on the UI issues in separate items.

**Comment by situatedbit** [comment]
(As an aside, I think we should maintain the same basic navigation between appointment cards within the calendar. I think there are some small/inexpensive improvements we could make to address some of the current issues. Ultimately, I think there should be a way to see all pending booking requests in a single place outside of the calendar. Some of the current conceptual difficulties stem from the appointment card as both an action space (choosing among three time slots) and as a representation of a single time slot in the calendar. We need to disentangle them.)

I'm going to create a few new issues with small UI improvements.

**Comment by situatedbit** [comment]
The problem: 

In the booking request appointment card, the top-most time slot option was set to the start time of the appointment. This resulted in the top-most time changing with each appointment card for a booking. The bottom two time slot options were constant.

I changed the top-most time slot option to be the booking source service date of the event rather than the event start time. Now the three cards are consistent.

Unfortunately this means that there are three cards, but they don't differ at all when the events are on the same day. I recommend implementing #270 to address this issue.

**Comment by situatedbit** [comment]
see pull request #273

**Comment by IagoSRL** [comment]
PR Merged, good idea too to split issues too.
