### ISSUE TITLE
Bug: S2 Client cannot access booking via inbox messages

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#112]
Site: live

Browser: Firefox (only tried Firefox)

To reproduce:
1. as a client, book a service
2. go to the messages in the inbox associated with that booking
3. on the conversation page, click on _Open Booking_ button
4. You will see the login page, even though you are already logged in.
5. Try to the use the browser back button to return to the booking, but you cannot navigate away from the login screen (unless you use the menu). Every time you press the back button, the `_suid` parameter in the login URL increments.

I confirmed this with both finished and unfinished services.

The professional is able to view the booking via messages. This seems to affect only clients.

Here are the screenshots.
![01](https://cloud.githubusercontent.com/assets/6644016/21859844/1f0b625c-d7e3-11e6-9ba4-cae73e395892.png)

![02](https://cloud.githubusercontent.com/assets/6644016/21859853/26acf7be-d7e3-11e6-9460-c05d1002fca8.png)

![03](https://cloud.githubusercontent.com/assets/6644016/21859857/299c5140-d7e3-11e6-9a87-ee5b137d06f8.png)

![04](https://cloud.githubusercontent.com/assets/6644016/21859860/2c1e61ec-d7e3-11e6-808d-e1714ced3805.png)

**Comment by joshdanielson** [comment]
@situatedbit this seems to be included as fixed in #5. Can you test and close this if you agree?

**Comment by situatedbit** [comment]
@joshdanielson This appears to be fixed. Shall I close it?

**Comment by joshdanielson** [comment]
@situatedbit @IagoSRL closing and including it this release.
