### ISSUE TITLE
Bug: S4 Some numeric input fields allow for negative values on client-side

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#113]
Site: live

Some input fields that take numbers (e.g., price for service, zipcode for service location) allow for the user to input negative values. These values are caught in validation, but we can set a minimum value on the input field to prevent this from happening in the first place. 

(Oddly on Chrome and Firefox for the desktop the user can adjust the values of these fields using the mouse wheel. If the user is using an unfamiliar mouse (or trying to scroll within the page), they can inadvertently change the value. I've seen this happen in a user study.)

To fix: add ``min=0`` to zipcode and price fields

**Comment by IagoSRL** [comment]
Closed as per merge of #543
