### ISSUE TITLE
Bug S2: Profession search field on Learn More page breaks if user presses enter

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#116]
Site: live

On the Learn More page (for professionals) the Profession search box can return results slowly. Often forms respond to pressing <enter> or on a phone, pressing the form submit button on the soft keyboard. In this search field, if a user types a job title, doesn't see the results fast enough and presses <enter> or submits the form via the soft keyboard, then the search box clears and several items appear in the search results. These items look like they're supposed to be hidden.

Here's the screenshot:

![empty-search](https://cloud.githubusercontent.com/assets/6644016/21871390/a8da8160-d816-11e6-9e2a-7394ae97587e.jpg)

**Comment by IagoSRL** [comment]
This was fixed with the refactor of the code for accessibility at #528
