### ISSUE TITLE
Bug S1: Error when submitting sign up form on Dev site

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#13]
Steps to reproduce:
- enter all required info in [service professional sign-up form](http://dev.loconomics.com/#!/signup/service-professional)
- click submit
- error received:
![screen shot 2016-11-21 at 10 56 25 am](https://cloud.githubusercontent.com/assets/1202838/20496331/97dd6b80-afd9-11e6-8c32-31d208223fcd.png)

**Comment by joshdanielson** [comment]
@IagoSRL moving this to Release 1.2 as it's a showstopper.

**Comment by IagoSRL** [comment]
Agree. With latest bug I was thinking in remember to clarify when the bug happens at *dev* but not at *live* so is a bug at working changes and must block the release, so fine :-)

**Comment by IagoSRL** [comment]
Fixed this. It's strange, but was a problem with default values at [users] table...defaults that existed before in *dev* and still at *live*.

Please @joshdanielson try it to have a double check.

**Comment by joshdanielson** [comment]
@IagoSRL tested and closing.
