### ISSUE TITLE
Remove blog.loconomics.com 

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#132]
wordpress at Azure (is a slot of the webapp)

**Comment by IagoSRL** [comment]
@joshdanielson I removed the blog completely:
- full directory from FTP
- database from Azure
- subdomain set-up at root web.config (pushed changes)

I did a backup prior to it, just in case, is about 7MB compressed with 7zip, I placed it at Dropbox folder (move it if you want). It includes a README file with explanation, database backup and files.

**Comment by joshdanielson** [comment]
@IagoSRL great, thanks!
