### ISSUE TITLE
Dev Site Bug S1: Login issues on dev site

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#138]
This happened for both my client (ID 543) and service professional (ID 540) accounts on Safari and as a result can't get to the dashboard. Strangely it works on Chrome:
client (ID 543):
(does not go to dashboard when logging in, but stays on login page, clears data but is logged in):
![screen shot 2017-01-27 at 11 46 48 am](https://cloud.githubusercontent.com/assets/1202838/22385125/56a0fa24-e486-11e6-84b6-18688d4c9353.png)
![screen shot 2017-01-27 at 11 44 00 am](https://cloud.githubusercontent.com/assets/1202838/22385047/f36a8a2e-e485-11e6-9242-2700f8429a16.png)
Chrome:
![screen shot 2017-01-27 at 11 48 34 am](https://cloud.githubusercontent.com/assets/1202838/22385198/912b2d2c-e486-11e6-8374-d7434f90fe37.png)

Service Professional account (ID 540):
login on safari forces me back to onboarding:
![screen shot 2017-01-27 at 11 55 39 am](https://cloud.githubusercontent.com/assets/1202838/22385473/a5438bf0-e487-11e6-8c1d-bfde2964298a.png)

Fine on Chrome:
![screen shot 2017-01-27 at 11 55 44 am](https://cloud.githubusercontent.com/assets/1202838/22385493/b23b6ef4-e487-11e6-8c9a-d8e75342da70.png)

**Comment by joshdanielson** [comment]
Did some more testing on this per @situatedbit 's suggestion and renamed this to login issues as it's more accurate. 
Using a "new private window" for Safari, I was able to log into my service professional account just fine (no forced onboarding and landed me on the dashboard). When I logged out and tried logging in with my client account, it said "invalid email or password" although I doubled checked the password using Chrome. When I used another "new private window", it worked just fine.

And testing it more, sometimes it works without the new window, sometimes not.

**Comment by joshdanielson** [comment]
@IagoSRL this is the bug I found while testing #20 and I just ran into similar issues while logging into Firefox AND Chrome as a new client (user ID 612). It's not letting me get to the dashboard.
![screen shot 2017-01-30 at 2 00 59 pm](https://cloud.githubusercontent.com/assets/1202838/22443694/ab17b3ca-e6f4-11e6-8d6d-b007c33612ef.png)
![screen shot 2017-01-30 at 2 04 12 pm](https://cloud.githubusercontent.com/assets/1202838/22443758/eab2d50a-e6f4-11e6-98de-6846d689bef3.png)
![screen shot 2017-01-30 at 2 04 02 pm](https://cloud.githubusercontent.com/assets/1202838/22443757/eab22f4c-e6f4-11e6-8d68-bfa77d393c35.png)

**Comment by IagoSRL** [comment]
First, this looks a lot like #143, I think are duplicated.

------------

I did some tests, worked fine for the point of this issue (on Safari 9.0.3 on Mac OS X El Capitan 10.11.3); I found another issue, though:
- Login with existent account, no problem.
- Sign-up as professional, started onboarding.
  - Closed tab, opening new one -> at onboarding as expected; close session, log-in -> at onboarding as expected;
  - tried to complete onboarding, validation errors at paymentAccount because of use of fake phone and street address (bug #196), go-back to aboutMe form with browser button, click save&continue
    - last step omitted, I'm at "Woohoo!" post-onboarding screen (bug #115)
    - but at that screen, my user menu show me as logged and onboarding finished.
    - Trying to log-out from there (no clicking links at Woohoo! screen) and log-in -> goes to dashboard as expected.

No relevant messages at Console (except for unable to load youtube https from a http source, and the validation errors at paymentAccount).

---------

Looking at database, both @joshdanielson users 543 and 540 has an OnboardingStep of null, so onboarding must not be triggered now. @joshdanielson if trying now that still happens, let me know the localStorage of your browser (key "LoconomicsApp/profile"), maybe some bad cached data (in theory, info related to basic user data and onboardingStep gets updated with the result of the log-in, updating the localStorage cache, but maybe that failed). After copy that, remove all your localStorage on the site (run at console 'localStorage.clear()'), reload page and try again, please.

**Comment by joshdanielson** [comment]
@IagoSRL trying this again with my userID 540 in Safari and it still thinks I haven't started onboarding. I think you're around so I'll wait a little bit to clear it in case you need more info. Here's my localStorage:
![screen shot 2017-02-04 at 10 17 36 am](https://cloud.githubusercontent.com/assets/1202838/22620548/36e45ef4-eac3-11e6-8a9d-547419629807.png)
![screen shot 2017-02-04 at 10 18 44 am](https://cloud.githubusercontent.com/assets/1202838/22620555/3b66a662-eac3-11e6-9c4a-2eb3cda83854.png)
![screen shot 2017-02-04 at 10 18 47 am](https://cloud.githubusercontent.com/assets/1202838/22620556/3faa9e54-eac3-11e6-9f68-467f058f96dc.png)

**Comment by IagoSRL** [comment]
Yes, keep it and don't clear. I'm trying more things (just get my *"machine"* updated to latest OSX and Safari 10)

**Comment by joshdanielson** [comment]
@IagoSRL okay! Let me know. You can send me a google chat. I'm around but might go outside for 10 minutes because someone is "sharing" (renting) my car :)

**Comment by IagoSRL** [comment]
OK, no problem ;-)

FYI: Just did the same tests but on Safari 10.0.3 on macOS Sierra (10.12.3), and no problem.

**Comment by IagoSRL** [comment]
@joshdanielson Paste here the full value for *localStorage['LoconomicsApp/profile']* (you can put that on your console). Clean-up some value if you want, as phone number; mostly I need the value for onboardingStep, to see if is different from DB.

**Comment by joshdanielson** [comment]
@IagoSRL here it is:
> localStorage['LoconomicsApp/profile']
< "{\"userID\":540,\"email\":\"joshua.danielson@loconomics.com\",\"firstName\":\"Joshua\",\"lastName\":\"Danielson\",\"secondLastName\":\"\",\"businessName\":null,\"alternativeEmail\":null,\"phone\":\"4159026025\",\"canReceiveSms\":false,\"birthMonthDay\":10,\"birthMonth\":12,\"isServiceProfessional\":true,\"isClient\":true,\"isCollaborator\":false,\"onboardingStep\":null,\"accountStatusID\":1,\"createdDate\":\"2016-02-22T14:16:34.27-08:00\",\"updatedDate\":\"2016-12-02T22:45:34.647-08:00\",\"ownerStatusID\":null,\"ownerAnniversaryDate\":null,\"photoUrl\":\"http://dev.loconomics.com/en-US/Profile/Photo/540?v=2016-12-02T22:45:34\"}"

**Comment by IagoSRL** [comment]
Thanks. I found the localStorage not being the problem, but a bug at what data server returns on login, I think is just at the internal method *GetLoginResultForID*.

**Comment by IagoSRL** [comment]
Fond that *GetLoginResultForID* was working as expected, but some users are keeping the onboardingStep, that is returend by the login, updated in memory to the user *profile* copy but not set to localStorage (a mistake I'm fixing), and seems the action to redirect user to onboarding when that is detected is not working or skipping in some way. So, almost two problems: not saving latest state for onboarding on server and not continuing onboarding on log-in.

**Comment by IagoSRL** [comment]
I tried some things.. reviewed both problems commented previously and ended to find that onboardingStep was being saved correctly and problem I though was with updating localStorage was not (there was another line of code fixing that, I just made a change to code so is more obvious). Too, my user had a value for the onboardingStep before changing the weeklySchedule activity into schedulingPreferences, and the name change make it to keep my value at database but the log-in and onboarding process detected that was not a valid value any more so just couldn't follow onboarding, just going to dahsboard. This way gets discarded too the possibility that a bad value at onboardingStep could have caused the bug (clearly did the opposite, going to dashboard and detecting user as non-onboarding).

I tested same things at Firefox 53a2 on Windows 7 and Safari 10 at MacOS Sierra.
I resset my user 141 with an onboarding step on server and tried how behaved on log-in, all as expected, and being able to finishing getting step set to null at database.
@joshdanielson I tested your both acounts 540 and 543. For 543 I had no problems, gets logged normally at dashboard. For 540, it says onboarding need to be completed, I went all the steps, finishing it; I logout and log-in and just landed to dashboard as expected.

I'm just thinking if some *race condition* may have happened, making to fail a redirect to the step URL or dashboard. It's very important that if this happens again, get a record of the browser console.

I have lost lot of time on this without being able to reproduce. @joshdanielson if you can now log-in as normal, test #60 again to see if that gets fixed and we can move on there. Will move this to another release if no more data that help us locate the bug appears today.

**Comment by joshdanielson** [comment]
@IagoSRL so my user 612 (I must have created this while getting frustrated), which is a client user, is still showing the onboarding message. I'm using Chrome and here is the localStorage info:
localStorage['LoconomicsApp/profile']
"{"userID":612,"email":"josh.d.anielson@gmail.com","firstName":"Josh","lastName":"D Client","secondLastName":"","businessName":null,"alternativeEmail":null,"phone":"","canReceiveSms":false,"birthMonthDay":null,"birthMonth":null,"isServiceProfessional":false,"isClient":true,"isAdmin":false,"isCollaborator":false,"photoUrl":"http://dev.loconomics.com/en-US/Profile/Photo/612?v=2017-01-30T21:56:42","onboardingStep":"welcome","accountStatusID":1,"createdDate":"2017-01-30T21:56:42.013-08:00","updatedDate":"2017-01-30T21:56:42.013-08:00"}"
![screen shot 2017-02-06 at 9 17 07 am](https://cloud.githubusercontent.com/assets/1202838/22658100/c079fea4-ec4d-11e6-8f3d-cc2a395bf3bf.png)
![screen shot 2017-02-06 at 9 17 27 am](https://cloud.githubusercontent.com/assets/1202838/22658101/c07b4b60-ec4d-11e6-8ad8-08455fede1c0.png)

**Comment by situatedbit** [comment]
I have not tried to reproduce this, but as a part of #115 I am refactoring some of the code around onboarding steps and login. Josh, maybe we can try to reproduce this issue on my branch ``is115``

**Comment by IagoSRL** [comment]
@joshdanielson Please if you have time, try to reproduce this issue at *dev* too, as commented by @situatedbit with his changes on #115 this may be affected positively.

Since is still hard to reproduce, and then to confirm the problem, I'm not sure if we must close it (if not happens again) or move it from release and keep and eye on it.

**Comment by joshdanielson** [comment]
@IagoSRL just tried to reproduce on dev using both Safari and Chrome using both my service professional and client account and could not. Closing and will create a new issue if encountered again. Nice work both!
