### ISSUE TITLE
Bug S3: App remains on login form after logged in

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#143]
@situatedbit commented on [Fri Oct 28 2016](https://github.com/joshdanielson/loconomics-internal/issues/1133)

Summary: after I log in to the app via the login form, the app does not navigate away from the form. Rather, the form is reset, though I am logged in.

Steps to reproduce:
Navigate
1.  to log in page as anonymous user
2. Enter credentials (I was logging in as service.loco@situatedbit.com)
3. Submit credentials
4. It should navigate to the dashboard or start onboarding (as I understand the code). Instead, the form resets. I am, however, logged in. The menu has my profile information in it (seen in screenshot below).

Browsers:
Firefox 49
Chrome 54

![login-form-remains](https://cloud.githubusercontent.com/assets/6644016/19825146/959f521e-9d2a-11e6-8c23-c0ec9022bc84.jpg)

---

@situatedbit commented on [Fri Oct 28 2016](https://github.com/joshdanielson/loconomics-internal/issues/1133#issuecomment-257051353)

Reproduced on master branch, app.html

---

@joshdanielson commented on [Fri Oct 28 2016](https://github.com/joshdanielson/loconomics-internal/issues/1133#issuecomment-257051695)

@situatedbit can you try and replicate on the live site? Just create a fake user if need be.

---

@situatedbit commented on [Fri Oct 28 2016](https://github.com/joshdanielson/loconomics-internal/issues/1133#issuecomment-257053330)

I was not able to reproduce this on the live site

---

@joshdanielson commented on [Fri Oct 28 2016](https://github.com/joshdanielson/loconomics-internal/issues/1133#issuecomment-257053629)

@situatedbit okay, cool! That's good news. I'm going to assign this to @IagoSRL and put it into the Known Bugs Milestone.

---

@situatedbit commented on [Fri Oct 28 2016](https://github.com/joshdanielson/loconomics-internal/issues/1133#issuecomment-257057827)

I did _not_ experience this problem logging in with Josh's account, joshua.danielson@loconomics.com

The user account with which I was having trouble was new. 

---

@joshdanielson commented on [Mon Nov 21 2016](https://github.com/joshdanielson/loconomics-internal/issues/1133#issuecomment-262037953)

@IagoSRL I just had this happen on the live site and is very strange...using both my users, which have completed profiles, I landed on the "Congrats" page of the onboarding. I logged out and back in and same for both users...THEN, it got weird and landed be back on the login, like @situatedbit experienced, with the form blank but I'm logged in. 

Can you look at this ASAP since it may be related to something happening now but not at all times?
![screen shot 2016-11-21 at 11 11 25 am](https://cloud.githubusercontent.com/assets/1202838/20496918/fa39e4dc-afdb-11e6-9a46-aee3889e562f.png)
![screen shot 2016-11-21 at 11 11 58 am](https://cloud.githubusercontent.com/assets/1202838/20496928/08abdf2a-afdc-11e6-86d2-0cebf3965f91.png)
![screen shot 2016-11-21 at 11 13 53 am](https://cloud.githubusercontent.com/assets/1202838/20496930/0dcccf8c-afdc-11e6-9b92-a91b4abe3517.png)

---

@IagoSRL commented on [Mon Nov 21 2016](https://github.com/joshdanielson/loconomics-internal/issues/1133#issuecomment-262040372)

Please, if you have the tab with the error opened, or you can re-open it (NO to go to the URL, but the tab itself), I want your history, your steps at loconocmis.com before the bug. I think can be related so something happening before, or the URL trying to go after login failed because a bad state. just a guess

---

@joshdanielson commented on [Mon Nov 21 2016](https://github.com/joshdanielson/loconomics-internal/issues/1133#issuecomment-262042490)

Here's my history:
![screen shot 2016-11-21 at 11 32 54 am](https://cloud.githubusercontent.com/assets/1202838/20497507/4b8b9db0-afde-11e6-8ce2-915503a2745b.png)

---

@IagoSRL commented on [Mon Nov 21 2016](https://github.com/joshdanielson/loconomics-internal/issues/1133#issuecomment-262061509)

I fixed a related issue and uploaded to *live* and *dev*, with the login page getting redirected to itself endlessly (easy to see the _suid URL query parameter increasing quickly, and the tab frozen). I was unable still to reproduce this specific problem, but trying, and hope that other fix may help at similar situations.

---

@joshdanielson commented on [Mon Nov 21 2016](https://github.com/joshdanielson/loconomics-internal/issues/1133#issuecomment-262073781)

@IagoSRL logging in now takes me to the dashboard. Not sure if that was related or it just randomly started to again.

---

@IagoSRL commented on [Mon Nov 21 2016](https://github.com/joshdanielson/loconomics-internal/issues/1133#issuecomment-262076291)

Fixed an error that get logged at console (url is undefined) when at addJobTitles but nothing more... unable to reproduce, tried several things: sessions, browsers, users, entering to onboarding, left in the middle, completing onboarding and returning go log-in, more, more and nothing. Almost, don't happen all the time (never to me still :-/ ).

**Comment by IagoSRL** [comment]
Closing as duplicated of #138
