### ISSUE TITLE
Add ability to choose plan and pay user fees

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#146]
## Child stories
- As  [Sara the Service Professional](https://github.com/loconomics/loconomics/blob/master/docs/Personas/Sara%20the%20Service%20Professional.md) I want to **view** the *plans* available to me in the app.
- As  [Sara the Service Professional](https://github.com/loconomics/loconomics/blob/master/docs/Personas/Sara%20the%20Service%20Professional.md) I want to **choose** a *plan* that meets my budget through the app.
- As  [Sara the Service Professional](https://github.com/loconomics/loconomics/blob/master/docs/Personas/Sara%20the%20Service%20Professional.md) I want to **enter** my *credit card* details through the app to pay the user fees so I can maintain access.
- As  [Sara the Service Professional](https://github.com/loconomics/loconomics/blob/master/docs/Personas/Sara%20the%20Service%20Professional.md) I want to **use** the *plan's free trial* offered to me when signing up before I'm billed.
- As  [Sara the Service Professional](https://github.com/loconomics/loconomics/blob/master/docs/Personas/Sara%20the%20Service%20Professional.md) I want to **see** that the *payment* was successful.
- As  [Sara the Service Professional](https://github.com/loconomics/loconomics/blob/master/docs/Personas/Sara%20the%20Service%20Professional.md) I want to **view** the *plan* I'm on.

### Test Cases
1) Make sure there is a monthly plan to choose from
2) Make sure there is a yearly plan to choose from
3) Make sure the app captures the user's credit card info easily
4) Make sure a recurring subscription is created with Braintree with the number of days left in trial passed through
5) Make sure we store the subscription information in our database
6) Make sure the user knows the payment went through

### Front-end
- [x] /userFees should show the following the first time a user visits it:
  - "Select a plan" section shown (like cancellation policy) if no plan selected or when "Change plan" clicked that includes monthly and annual options
  - Our Free plan includes;
     - x
  - Our Lite plan includes;
     - x
     - y
     - $14.95/mo.
  - Our Full plan includes:
     - x
     - y
     - $29.95/mo. or $299.95/year
  - "Enter payment info" section if no credit card on file with card number, ccv, expiry date, zip code
- [x] Show confirmation to user when payment is successful with a "Thank you"
- [x] Show the plan the user is currently on
### JS
-  
### API
-  
### Braintree
- [x] Create UserPaymentPlan (can have multiple plans) table with the following fields:
      - UserPaymentPlanID
      - UserID
      - SubscriptionID (from braintree, subscription that's specific to the user)
      - SubscriptionName?
      - **NEW:** FirstBillingDate (from Braintree)
      - **NEW:** SubscriptionEndDate (should be null unless plan is cancelled/changed)
      - PaymentPlan  (from braintree: Monthly, Annual)
      - **NEW:** PaymentMethodToken (from Braintree) - not sure if this is necessary if we can query it?
      - PaymentMethod (e.g. Visa ending in 5295)
      - **NEW:** PaymentExpiryDate (e.g. 03/2018)
      - PaymentPlanLastChangedDate (UpdatedAt from Braintree)
      - NextPaymentDueDate (NextBillingDate from Braintree)
      - NextPaymentAmount (NextBillingAmount from Braintree)
      - **NEW:** DaysPastDue (from Braintree)
      - TotalPastDueAmount - DELETE
      - **NEW:** PlanStatus (from Braintree)
- [x] Create user fee subscription plans in Braintree:
   - Monthly Lite
   - Monthly Full
   - Annual Full
- [x] Review using Braintree's [Drop-in UI](https://developers.braintreepayments.com/guides/drop-in/javascript/v2) instead of our hosted forms
- [x] [Create Subscription](https://developers.braintreepayments.com/reference/request/subscription/create/dotnet)
    - Monthly Lite: 
var request = new SubscriptionRequest
{
    PaymentMethodToken = "the_token",
    PlanId = "MonthlyLite",
    Descriptor = "Loconomics Monthly Lite Plan User Fees",
    TrialDuration = query: select IF SYSDATE > TrialEndDate THEN TrialEndDate - SYSDATE ELSE 0; FROM users where userID = @UserID,
    TrialDurationUnit = "day",
    HasTrialPeriod = query: select IF SYSDATE > TrialEndDate THEN "true" - SYSDATE ELSE "false"; FROM users where userID = @UserID
};

     Result<Subscription> result = gateway.Subscription.Create(request);

    - Monthly Full: 
var request = new SubscriptionRequest
{
    PaymentMethodToken = "the_token",
    PlanId = "MonthlyFull",
    Descriptor = "Loconomics Monthly Full Plan User Fees",
    TrialDuration = query: select IF SYSDATE > TrialEndDate THEN TrialEndDate - SYSDATE ELSE 0; FROM users where userID = @UserID,
    TrialDurationUnit = "day",
    HasTrialPeriod = query: select IF SYSDATE > TrialEndDate THEN "true" - SYSDATE ELSE "false"; FROM users where userID = @UserID
};

     Result<Subscription> result = gateway.Subscription.Create(request);

    - Annual Full:
var request = new SubscriptionRequest
{
    PaymentMethodToken = "the_token",
    PlanId = "AnnualFull",
    Descriptor = "Loconomics Annual Full Plan User Fees",
    TrialDuration = query: select IF SYSDATE > TrialEndDate THEN TrialEndDate - SYSDATE ELSE 0; FROM users where userID = @UserID,
    TrialDurationUnit = "day",
    HasTrialPeriod = query: select IF SYSDATE > TrialEndDate THEN "true" - SYSDATE ELSE "false"; FROM users where userID = @UserID
};

     Result<Subscription> result = gateway.Subscription.Create(request);

- [x] [Find Subscription](https://developers.braintreepayments.com/reference/request/subscription/find/dotnet)

**Comment by joshdanielson** [comment]
@IagoSRL I'm getting this error in dev using the 4111111111111111 testing credit card:
![screen shot 2017-05-08 at 3 52 45 pm](https://cloud.githubusercontent.com/assets/1202838/25828694/8251ba08-3406-11e7-9813-9e94d301f27b.png)

**Comment by joshdanielson** [comment]
@IagoSRL also I just noticed in is191 that I used a couple "&" symbols in the appModel.paymentPlans.js descriptions. I can't remember if that screws anything up with .net/razor.

**Comment by joshdanielson** [comment]
@IagoSRL also just made one last commit as I realized my closing ul tags were missing a "/" (in AppModel.paymentPlans.js)

**Comment by IagoSRL** [comment]
@joshdanielson 
I fixed the 'null' error of you screenshot. Now, working against Braintree Sandbox I get this error
> Plan ID is invalid.
Company name/DBA section must be either 3, 7 or 12 characters and the product descriptor can be up to 18, 14, or 9 characters respectively (with an * in between for a total descriptor name of 22 characters).

Are the new plans added to Sandbox for testing?

**Comment by IagoSRL** [comment]
About your latest comments, no problem; '&' has no issues here, and this code is executed in javascript on the client not at server (where is .net/razor), but usually html editors highlight it as an error because strictly, in html must be wrote as '&amp;' (an html entity) but in practice browsers parse it correctly (almost always if is followed by a whitespace; if you want to be sure/be correct, you can write it as an entity, and test how it looks).

**Comment by joshdanielson** [comment]
@IagoSRL sorry...totally forgot about the sandbox plans! They've been updated. I'm getting a different error now:
![screen shot 2017-05-09 at 9 15 33 am](https://cloud.githubusercontent.com/assets/1202838/25860986/2c6b6d04-3498-11e7-85a1-6062121276e3.png)

**Comment by joshdanielson** [comment]
And thanks for the clarification on the '&'. I'll just leave it as is if you don't think it's a problem.

**Comment by IagoSRL** [comment]
I don't know about that error, not sure if is something to change with the subscription request sent or in the control panel

**Comment by IagoSRL** [comment]
@joshdanielson The error returned by Braintree is because of the given descriptor, the format is limited to:
> Company name/DBA section must be either 3, 7 or 12 characters and the product descriptor can be up to 18, 14, or 9 characters respectively (with an * in between for a total descriptor name of 22 characters)

From https://developers.braintreepayments.com/reference/request/transaction/sale/dotnet#descriptor.name

We were sending this ones:
```
                case SubscriptionPlan.OwnerProAnnual:
                    return "Loconomics Owner Pro Annual Plan User Fees";
                case SubscriptionPlan.OwnerPro:
                    return "Loconomics Owner Pro Plan User Fees";
                case SubscriptionPlan.OwnerGrowth:
                    return "Loconomics Owner Growth Plan User Fees";
```

So we can change them to be:
- Loconomics  *ProAnnual
- Loconomics  *Pro
- Loconomics  *Growth

Let me know if you prefer different names (or an abbreviated 'Loconomics' part, that must be 3, 7 or 12 fixed characters, can have whitespaces to fill the gap).

**Comment by joshdanielson** [comment]
@IagoSRL that's fine! I wish they checked for that when they let me create them that way :( 

Here are the updated plans:
Sandbox
![screen shot 2017-05-09 at 2 31 27 pm](https://cloud.githubusercontent.com/assets/1202838/25873663/3e8facf8-34c4-11e7-8821-f805a7969b05.png)
Live
![screen shot 2017-05-09 at 2 30 31 pm](https://cloud.githubusercontent.com/assets/1202838/25873677/4b081ff6-34c4-11e7-951b-3b81e82d11dd.png)

**Comment by IagoSRL** [comment]
I don't know how all plays together; in the code, when creating the subscription we provide that text as 'descriptor.name'; not sure if is the same as the plan name, or even if is optional to give it in the API call.

**Comment by IagoSRL** [comment]
I updated the code with the new names, being aware that a two whitespaces are needed between 'Loconomics' and '*'; I put them in the previous comment, but are collaped by html to one.

I fixed another error behind that, and was able to create a subscription at *dev*.

**Comment by joshdanielson** [comment]
@IagoSRL tested and working! I put in a final commit after merging #385 into this branch as I need the CSS (looks much better). It's ready!

**Comment by IagoSRL** [comment]
I updated the is191 branch with *master* updates and the payment plans html that used IconList. I'm reviewing all the changes of is191 against master to be sure we are publishing to *live*.

**Comment by IagoSRL** [comment]
I'm closing this since we released this changes; as we already did, new issues for new bugs on this.
