### ISSUE TITLE
Onboarding Email Series

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#148]
@joshdanielson commented on [Tue Sep 20 2016](https://github.com/joshdanielson/loconomics-internal/issues/1049)

- [ ] Create onboarding reminder series, 24 hours, 72 hours, etc.
- [ ] Create "Your profile is activated" email with tutorial links, tell your clients
- [ ] Add "share" buttons at bottom of email

**Comment by joshdanielson** [comment]
moved back to internal repository as it will be done through SendGrid to start with.
