### ISSUE TITLE
Dev Site – Bug S1: Error when booking

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#16]
Booking URL: http://dev.loconomics.com/#!/booking/540/106
Screen shot:
![screen shot 2016-11-22 at 1 48 35 pm](https://cloud.githubusercontent.com/assets/1202838/20543464/c3168728-b0ba-11e6-9537-b9281d4c2288.png)

Error message:
There was an error
Object reference not set to an instance of an object.

Technical details: {"errorMessage":"Object reference not set to an instance of an object.","exception":{"ClassName":"System.NullReferenceException","Message":"Object reference not set to an instance of an object.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":" at CalendarDll.ProviderAvailability..ctor(DataContainer obj) in C:\\Users\\Iago\\Proxectos\\Loconomics\\code\\iCalendarLib\\CalendarDll\\DbUtilsTypes.cs:line 119\r\n at CalendarDll.CalendarUtils.<GetFreeEvents>b__1(DataContainer dts) in C:\\Users\\Iago\\Proxectos\\Loconomics\\code\\iCalendarLib\\CalendarDll\\CalendarUtils.cs:line 290\r\n at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()\r\n at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\r\n at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n at CalendarDll.CalendarUtils.GetFreeEvents(CalendarUser user, DateTime startDate, DateTime endDate, DateTime currentDateTimeForAdvanceTime) in C:\\Users\\Iago\\Proxectos\\Loconomics\\code\\iCalendarLib\\CalendarDll\\CalendarUtils.cs:line 289\r\n at LcCalendar.GetUserAvailability(Int32 userID, DateTime dateStart, DateTime dateEnd, Boolean excludeAdvanceTime)\r\n at LcCalendar.CheckUserAvailability(Int32 userID, DateTime dateStart, DateTime dateEnd, Boolean excludeAdvanceTime)\r\n at LcRest.Booking.CheckAvailability(DateTime startTime, Nullable`1 serviceDurationMinutes, Int32 serviceProfessionalUserID)\r\n at LcRest.Booking.InsClientBooking(Int32 clientUserID, Int32 serviceProfessionalUserID, Int32 jobTitleID, Address serviceAddress, DateTime serviceStartTime, Nullable`1 alternative1StartTime, Nullable`1 alternative2StartTime, IEnumerable`1 services, Int32 languageID, Int32 countryID, String bookCode, String specialRequests)\r\n at ASP._Page_api_v1_me_client_booking_cshtml.RestMeClientBooking.CreateItem()\r\n at ASP._Page_api_v1_me_client_booking_cshtml.RestMeClientBooking.Post()\r\n at RestWebPage.Run(WebPage WebPage)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"1\n.ctor\nCalendarDll, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null\nCalendarDll.ProviderAvailability\nVoid .ctor(CalendarDll.DataContainer)","HResult":-2147467261,"Source":"CalendarDll","WatsonBuckets":null}}

**Comment by IagoSRL** [comment]
I did a quick fix and tested, created the booking @joshdanielson you may have received an email, but the dates are wrong, more internal APIs need adjustment to DateTimeOffset and be time-zone aware, I'm fixing that.

**Comment by IagoSRL** [comment]
This bug is fixed. Changes about presentation of time-zone/offset at emails at the time zone issue.
Closing.
