### ISSUE TITLE
Study new Braintree API for easier PCI compliance on payments: v.zero

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#162]
@IagoSRL commented on [Tue May 19 2015](https://github.com/joshdanielson/loconomics-internal/issues/723)

Braintree v.zero website:
https://www.braintreepayments.com/v.zero?partner_source=email_et_hostedfields_merchant_v1_NA_v.zero&utm_medium=email&utm_source=et&utm_campaign=hostedfields-merchant-v1-NA-v.zero

Email from Braintree to Josh:

Introducing Hosted Fields

The latest set of PCI Data Security Standards (PCI DSS 3.0) is now in full effect. 

The great news is Braintree can help make PCI compliance a breeze. If you're already using our Drop-in UI, you should be all set. For merchants who prefer a more customized checkout flow, we've created a solution to help you continue to qualify for the shorter, simpler SAQ.

Hosted Fields alleviates compliance headaches by creating the required iframes in your checkout, yet gives you complete control over the style and layout of the experience. And it comes standard with our v.zero SDK.

This means you can integrate quickly, maintain control, and keep doing what you do best-all while we secure your sensitive data. 

To find out if you could benefit from Hosted Fields, read our blog.  

Upgrade to v.zero

Have other questions regarding PCI? Contact our Support team: support@braintreepayments.com

**Comment by IagoSRL** [comment]
This is in part duplicated of #307. Well, that one is newest but I think more complete, and the link here to blog don't work.
