### ISSUE TITLE
Bug S1: External URL Links in App Not Working

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#19]
We received this note from a user yesterday about the braintree terms of service link. 

Josh Stern no-reply@olark.com
7:26 PM (17 hours ago)

to me 
Hello Loconomics,
It looks like you have a broken link on the page https://loconomics.com/#!/paymentAccount

The link as written is:
https://loconomics.com/www.braintreepayments.com/agreements/merchant

But I think it should be:
www.braintreepayments.com/agreements/merchant

Cheers, Josh

---

You received this message from a visitor while you were away.

Name: Josh Stern

E-mail: joshstern6@gmail.com

The visitor was on this page: https://loconomics.com/www.braintreepayments.com/agreements/merchant

The visitor was referred to your site from: , referred to your site by https://loconomics.com/

Web Browser: Chrome
Web Browser Version: 54.0.2840.59
Operating System: Linux
IP Address: 108.31.2.9
Location: United States (Silver Spring, MD)

**Comment by joshdanielson** [comment]
Replace code lines 91-94 in paymentAccount.html with new language (and fix links):
`                    <h2 class="SectionTitle">Agree to the terms of service</h2>
                    <p>
                        Loconomics Cooperative, Inc. (Loconomics) uses Braintree, a division of PayPal, Inc. (Braintree) for payment processing services. By using the Braintree payment processing services you agree to the Braintree Payment Services Agreement available at <a class="text-secondary" href="https://www.braintreepayments.com/legal/payment-services-agreement" target="_blank">https://www.braintreepayments.com/legal/payment-services-agreement</a>, and the applicable bank agreement available at <a class="text-secondary" href="https://www.braintreepayments.com/legal/bank-agreement-us" target="_blank">https://www.braintreepayments.com/legal/bank-agreement-us</a>.If you have questions regarding the agreements, please contact Braintree at 877.434.2894.
                    </p>`

**Comment by situatedbit** [comment]
@joshdanielson, this link is bad: https://www.braintreepayments.com/legal/bank-agreement-us

I think it should be https://www.braintreepayments.com/legal/bank-agreement

Can you confirm?

**Comment by joshdanielson** [comment]
@situatedbit yes, that's it. Strange that the braintree docs are wrong, but they are.
