### ISSUE TITLE
Release 1.2 Copy Edits

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#2]
**Site:**
- [x] Revise onboarding tips:
  - Clients will find you when search by job title
  - take out ",say". You can add more than one.
- [x] Specify it needs to be a photo of yourself

**Database:**
- [x] Remove i specialize in for Massage Therapists (redundant)
- [x] Remove duplicate service attributes
- [x] Remove duplicate job titles

**Emails:**
- [x] Comment out specific FAQs for now but leave "Visit the Help Center" button
- [x] Make it clear to not reply to the communication, e.g. donotreply@loconomics.com
  reply to service professional's address
- [x] Review communication of time/time zones

**Comment by joshdanielson** [comment]
@IagoSRL ready to merge to master!

**Comment by IagoSRL** [comment]
done!
