### ISSUE TITLE
Bug S2: Missing Info in Booking Cards/Communications

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#20]
This is happening on a couple bookings so will try to explain clearly to reproduce.
1. BookingID 408 missing info:
   - Services
   - Location
     Irene's dashboard (service professional):
     ![screen shot 2016-10-17 at 8 56 43 am](https://cloud.githubusercontent.com/assets/1202838/19445352/c03509dc-9448-11e6-8545-3084e1c08299.png)
     My confirmation email (userID 295):
     ![screen shot 2016-10-17 at 8 40 51 am](https://cloud.githubusercontent.com/assets/1202838/19445376/dbb6c3e4-9448-11e6-99b3-804bff828b84.png)
2. BookingID 411 missing info 
   - Location 
     ![screen shot 2016-10-17 at 9 13 09 am](https://cloud.githubusercontent.com/assets/1202838/19445734/6ca3060a-944a-11e6-90e8-468ca907386d.png)
     ![screen shot 2016-10-17 at 9 13 29 am](https://cloud.githubusercontent.com/assets/1202838/19445732/6ca1e72a-944a-11e6-859e-e7b0cae46b67.png)
     ![screen shot 2016-10-17 at 9 13 50 am](https://cloud.githubusercontent.com/assets/1202838/19445733/6ca2ee72-944a-11e6-83c1-0cbd8d5aa5d8.png)
     ![screen shot 2016-10-17 at 9 15 22 am](https://cloud.githubusercontent.com/assets/1202838/19445735/6ca4ffc8-944a-11e6-81d8-4019a2dce839.png)
I was thinking this may have  something to do with hiding the location on booking requests, but the same happened when I did an instant booking. The location just gets lost:
![screen shot 2016-10-17 at 1 28 39 pm](https://cloud.githubusercontent.com/assets/1202838/19454370/bf3f572e-946d-11e6-9b37-109aff74f1aa.png)

**Comment by IagoSRL** [comment]
As commented at #60, I found this bug and other close related when testing the fix there, and I fixed that several bugs. Maybe not all detailed here is fixed, but the missing address may be fixed; maybe other missed info was side effects of other bugs, so please @joshdanielson test this again, it's at *dev*, and let me know.

**Comment by joshdanielson** [comment]
@IagoSRL just tested this and seems good from emails and booking cards (bookingID 814). I found some odd bugs in the process, though. Closing this.

**Comment by IagoSRL** [comment]
Good!

> I found some odd bugs in the process

@joshdanielson Please document that ones, on their own issues if makes sense.

I moved this to Release 1.2.2 since the fix gets included at that version
