### ISSUE TITLE
Install spare SSL certificate on dev site

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#216]
@joshdanielson commented on [Wed Jan 25 2017](https://github.com/joshdanielson/loconomics-internal/issues/1168)

**Comment by IagoSRL** [comment]
Done!

We can go to https://dev.loconomics.com now!

The access through 'http' still available, like for *live*. Thinking in add a rule to force redirect to http*s*.

**Comment by IagoSRL** [comment]
Updated the Grunt build tasks so now points to http**s** for *dev* builds.

**Comment by IagoSRL** [comment]
@joshdanielson I updated the document  loconomics-internal/docs/Renewing the SSL Certificate.md with additional instructions to install at Azure and some formatting.
