### ISSUE TITLE
Code clean-up, refactoring, code comments, to-do comments...

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#233]
@IagoSRL commented on [Wed Jun 20 2012](https://github.com/joshdanielson/loconomics-internal/issues/14)

This is a permanent issue and meta-issue to track in one place commits related to next coding tasks:
- Clean-up of deprecated, old code/files.
  - sometimes some files or code about how a feature was being implemented before some big changes are preserved but not needed; need be reviewed, ensure nothing breaks removing it.
  - other times some code from a file is being using, with a lot of unused code (because of changes), this need be detected and removed, and maybe refactored.
- Refactoring: some code seems good at first time is wrotten, but after several changes or being reviewied in depth, can be better implemented in some other way (to win performance, clarity, maintainability), but need special tests and carefull to don't break something that is working.
- Comments on code are documentation about how code works, specially some complicated parts. Too much times first time code is written comments are not added (or only a few) because code can change and comments became not useful for the new code. Review complicated code (or all, if there is time) when is stabilized enough and add relevant comments.
- Sometimes quick to-do's are wrotten on code comments: look for that, open new issues and fix it.

---
- This issue is 'permanent' because is a task that never ends.
- This issue is meta-issue because other more specific related issues can be created linking this (mentioning the number with #) to have on one place all related tasks; and of course we have here all related commits.

---

@IagoSRL commented on [Thu Nov 08 2012](https://github.com/joshdanielson/loconomics-internal/issues/14#issuecomment-10184126)

I fixed some general errors, with light performance enhancement as side-effect and de-duplication code, in scripts related to ajax operations that load some page fragments (jQuery.reload function mainly), a very common error fixed by this is what happens sometimes when a user session is timeout and user click some button or link that reload an element in the page (on booking/schedule, when clicking on calendar, on dahsboard/bookings when clicking the 'view booking' button, ...).
If sometimes you suffered that error, is solved now; too an auto-abort duplicated ajax operations is in place now for that kind of loads (using our jQuery.reload function), is better for performance; and new features for that functions incorporated, required to implement the new booking/schedule/ (#148).

**Comment by IagoSRL** [comment]
Thanks for think on this, I'm thinking in manage this different so will close

**Comment by joshdanielson** [comment]
@IagoSRL I had an idea of creating a label for things like this and each would be its own issue (which I think is what's starting to happen), optimization, cleanup, etc. and then we'll have a "pipeline" for them. Let's discuss Monday.

**Comment by IagoSRL** [comment]
Yes, thinking almost the same. Specific issue, title prefix and/or label. Let's talk Monday
