### ISSUE TITLE
Bug S3 Validation on Payment Info Different From Profile

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#238]
Confirmed on Dev.

During onboarding I inadvertently changed my first name to be my email address. I submitted the profile form. Then, on the payment account form, when I submitted my fake test data, I received an error message saying that my name was invalid. 

(I _think_ the validation fails on the '+' character in the email address, because I tried to reproduce it with an email address without '+'). 

_The problem is that the name validation on the profile form is different from that on the payment form. During onboarding I'm not necessarily able to go back to the profile to fix it, nor is First Name available to fix on the page where validation breaks — payment_.

Screenshot of the error: 
![firstname](https://cloud.githubusercontent.com/assets/6644016/22799425/95d37c10-eeba-11e6-9740-676c878b51fe.jpg)

**Comment by IagoSRL** [comment]
This is the same commented at #196. I commented cases for phone and address validations, but it affects anything validated differently by Braintree than our own validations.

Closing as duplicated, please @situatedbit if you want, move your use-case there (maybe update my description if is confusing).

**Comment by situatedbit** [comment]
You are correct. I had not seen #196. Thanks.
