### ISSUE TITLE
Trouble building Android app

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#242]
@IagoSRL 

I'm trying to build the Android app so I can test the replaceState code. [Following directions on in the docs](https://github.com/loconomics/loconomics/blob/master/docs/Deploying%20the%20App.md).

Here's what I've done so far:

I installed Android Studio (and all SDKs back to 4.0). I ran the following within loconomics source:

(I've omitted most of the output except what seems important)
```bash
cd app/
npm install -g phonegap        <--- installed phonegap 6.4.3
grunt prepare-phonegap
cd phonegap/

phonegap plugin install
-> No plugins added. Use `cordova plugin add <plugin>`.      <--- this was unexpected

phonegap build android
-> 
[phonegap] executing 'cordova platform add --save android' ...
Creating Cordova project for the Android platform:
	Path: ../../../../../src/loconomics/loconomics/app/phonegap/platforms/android
Package: com.loconomics.app
	Name: Loconomics
	Activity: MainActivity
	Android target: android-24
Subproject Path: CordovaLib
Android project created with cordova-android@6.0.0
ls: no such file or directory: /home/mschaefer/data/src/loconomics/loconomics/app/phonegap/res/mipmap-*
```

It breaks on the last line -- the missing resource. 

I wonder why no plugins were installed. 

Any thoughts on this?

**Comment by IagoSRL** [comment]
On Windows 7: I just tried again the 'phonegap plugin install' on my machine, and it lists the plugins, showing no error
Upgraded from 5.3.6 to 6.4.3.

I cleaned-up my environment. Same output as you. I make a wrong assumption here, for some reason if you have plugins installed the command list them rather than show the error; it seems no auto install plugins from config.xml exists, needs specify each one manually (for first build).

**Comment by IagoSRL** [comment]
@situatedbit Maybe if you copy the /phonegap/www/res into /phonegap directly? I'm remembering that, on the beginning, this lead me to problems because PGB expected the folder inside /www while most documents about Phonegap cli says opposite.

**Comment by IagoSRL** [comment]
Sorry the delay, I had to update my Java to version 8 and update Android SDK (waiting still for this to finish; I still had the old ones from by restored backup from the disaster some weeks ago).

It seems that just 'phonegap build android' fetches and install automatically any plugin in the config.xml, so no need for manual step or the line that appear at docs ('phonegap plugin install').

**Comment by IagoSRL** [comment]
@situatedbit It worked for me the solution of copy the /phonegap/www/res folder under /phonegap
(after install 24 API and update lot of things!)

If you can confirm, there is a couple of things we need to update: the docs and the prepare-phonegap task, plus gitignore.

**Comment by situatedbit** [comment]
After moving ``www/res`` to ``phonegap/``, setting my ``ANDROID_HOME``, and installing a JDK I have an Android build!

(Of course, I left my USB cable at home...)

Do you want me to update the documentation? Also, why do we need to change ``.gitignore``? Is the ``res`` directory built from another location?

(Also, Josh gave me access to build.phonegap.com)

**Comment by situatedbit** [comment]
Oh - I see, there's a ``app/.gitignore``. 

Do you want me to update that, or will you?

**Comment by IagoSRL** [comment]
I updated documentation and too the Grunt tasks at *master*. Please get a copy from there.

I 'refactored' the tasks specifically for 'CLI' or 'PGB' and 'dev' or 'live' (I saw that the *old* prepare-phonegap task was generating *live* version, when sure you want *dev*). Please, take a look to the new /grunt/aliases.js file.

**Comment by IagoSRL** [comment]
Please do not notify this changes before, was testing that new tasks behave as expected and again building Android locally.

Asking your latest question: res folder was not *build* previously, but is now (located under /source/res now, copied under /phonegap or /phonegap/www depending on the CLI or PGB task ;-)

You can update the documentation now with notes about the environment set-up to build with Android (like variables you commented ANDROID_HOME, or typical JAVA_HOME pointing to a SDK version 8), anything you find needed.

**Comment by situatedbit** [comment]
Done.  Docs update in pull request #243. Thank you!
