### ISSUE TITLE
Bug: Android 4.3 broken, menus shows on top even when closed

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#245]
Discovered at research at #237 with comment from @situatedbit https://github.com/loconomics/loconomics/issues/237#issuecomment-279279622

The menus shows always on top of other content, even when they must be closed (has *collapsed* class).

It seems just a CSS problem, because of tricks at old webkit.

Some trials: Menus are *position:fixed*, when changed to *position:absolute* they dissapear (just the opposite behavior); this may be fine since other elements may be *fixed* and promoted on top menus, problem seems the compatibility with *fixed* in the engine.

**Comment by IagoSRL** [comment]
Tried trick at https://benfrain.com/easy-css-fix-fixed-positioning-android-2-2-2-3/
But didn't worked, I tried it as following:
```SCSS
.App-menus
    .navbar-collapse
        //position: absolute !important;
        //background: red !important;
        -webkit-backface-visibility: hidden !important;
```

and then too
```SCSS
*
    -webkit-backface-visibility: hidden !important;
```

no luck.

I stop trying now, not top priority

**Comment by situatedbit** [comment]
Since we don't support Android 4.3, should we close this issue?

**Comment by IagoSRL** [comment]
Yes, its a WONTFIX now. Closing.

**Comment by IagoSRL** [comment]
@joshdanielson I created label C:Wontfix for this cases, let me know if you agree or want to reuse D:Discarded

**Comment by joshdanielson** [comment]
Sounds great!
