### ISSUE TITLE
Bug S3 Appointment cards for time slot options remain after confirmation

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#268]
When confirming an appointment that has multiple time slots on the same day, the appointment cards for the other time slots persist after confirmation, until navigating away from that calendar day.

To reproduce:
1. As a client, book a service with a provider account. Choose three time slots on the same day.
2. As a provider, navigate to the calendar and then to the appointment cards for one of those time slots. 
3. Notice that there are multiple dots at the bottom of the page, representing the different time slot cards for that day.
4. Confirm one of the times. 
    - Notice that the time on the current card is set. It _may not_ be the time you confirmed.
5. _Notice that the cards for those time slots on that day persist_. You can navigate to them using the arrows at the top of the page.
    - Notice that the appointment cards where you did not select a time _still_ show the three time slots and ask that a time be confirmed.
6. Using the arrows, navigate away from the day with the appointments. 
7. Return to the day with the appointments. Notice that the extra time slots are now gone. Only the confirmed time remains.

Here's a screenshot after I confirmed one of three times. The three dots indicate that the other two time slots remain:
![three-little-cards](https://cloud.githubusercontent.com/assets/6644016/23274658/6dc6f84c-f9b8-11e6-8157-6f164e83e9cb.png)

Discovered through #105

**Comment by situatedbit** [comment]
All provider-side access to bookings goes through the ``appointment`` activity.

I plan to handle three cases
1. when the provider confirms an appointment, reload the appointment using the date/id of the slot confirmed by the user
2. when the provider denies a booking request, reload the appointment view to the date of the calendar event start date
3. when the provider cancels an appointment, reload the appointment view to the date of the cancelled appointment

**Comment by situatedbit** [comment]
I initially tried to create events on the booking model object, but during confirm/cancel/decline, the booking objects are switched out. Then I decided to add confirm/cancel/decline events to the AppointmentCard modelview. The Appointment activity listens for these events and redirects the user depending on the situation:
1. confirm: the appointment card with the ID of the booked object; this reloads the appointments list and discards the old, unwanted appointment cards
2. cancel and decline: go to the calendar activity view of the date of the appointment that was cancelled/declined. Users then see that the item they cancelled/declined is no longer on their calendars.

I added a utility to simplify listening to events called EventEmitterListener.

**Comment by IagoSRL** [comment]
Closing the issues (I did some additional testing).

Just a comment about EventEmitterListener: simple and good utility.
Some time I think that methods like 'on' at EventEmitter must return a reference that allow to cancel the handler, like this one and like it happens with Knockout observable *subscribe* method.
