### ISSUE TITLE
Add Owner Acknowledgment 

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#281]
Child Story | Target Persona(s) | Investable 
------------ | ------------- | ------------- 
I need to know the owner has acknowledged all that's legally required before the become an official owner. | Loconomics Staff | - 
**Test Cases** | 
1) Make sure the text includes all that's legally required per our bylaws
2) Make sure to record the date/time it's acknowledged

### Front-end
- [x] Create /ownerAcknowledgment
     - user must view and accept owner acknowledgment agreement with an "I agree" button
     - After "I agree" is clicked, it should say "You accepted on " + OwnerAcknowledgmentSignature (see below) 
### JS
- Validate First and Last Name using API
### API
- [x] Create OwnerAcknoledgement API with corresponding PUT/GET calls
### Database
- [x] Add OwnerAcknowledgement table with UserID, DateAcknowledged (date/time "signed" using the user's system time zone), AcknowledgedFromIP

**Comment by situatedbit** [comment]
estimate: 3

**Comment by joshdanielson** [comment]
2

**Comment by IagoSRL** [comment]
2

**Comment by joshdanielson** [comment]
@IagoSRL I'm trying to test this on the is191 branch but got this error:
![screen shot 2017-05-08 at 3 14 33 pm](https://cloud.githubusercontent.com/assets/1202838/25827657/2c8013b8-3401-11e7-8798-c9d96c8dc09d.png)

**Comment by IagoSRL** [comment]
@joshdanielson That's because the server changes required were not in *dev* still. I was already preparing it all, and now all the work at branches is191 and is277, included required DB upgrades, are in *dev*, so that must work for you now.

**Comment by joshdanielson** [comment]
@IagoSRL ah! Please review my latest commits in is191, and I'll test in dev now.

**Comment by IagoSRL** [comment]
@joshdanielson I reviewed it, it's OK, just fixed a minor html syntax

**Comment by joshdanielson** [comment]
@IagoSRL looks good now!

**Comment by IagoSRL** [comment]
Just released in 1.4
