### ISSUE TITLE
Professional can access management screen of client-specific offerings via client card

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#282]
As a professional, I want to manage client-specific pricing for each client. 

From the client editor, the professional should be able able to access a screen for seeing all services specific to that client, remove them, edit them, and add new ones.

(From #4)

**Comment by situatedbit** [comment]
@IagoSRL For this issue I want to change the text for the _back_ link on the services professional services activity when the user is navigating from the client editor. I think the way to do it is to set ``requestData.navTitle``. However, if there is no cancel link, then ``navTitle`` is used, but always overwritten.

(From https://github.com/loconomics/loconomics/blob/is282-manage-client-specific-offerings/app/source/js/activities/serviceAddresses.js#L126)

```javascript
    if (this.requestData.cancelLink) {
        this.convertToCancelAction(this.navBar.leftAction(), this.requestData.cancelLink, this.requestData);
    }
    else { // no 
        // Reset to defaults, or given title:
        this.navBar.leftAction().model.updateWith(this.defaultLeftAction, true);
        if (this.requestData.navTitle)
            this.navBar.leftAction().text(this.requestData.navTitle);

        var jid = this.viewModel.jobTitleID(),
            jname = this.viewModel.jobTitle() && this.viewModel.jobTitle().singularName() || 'Scheduler',
            url = this.mustReturnTo || (jid && '/jobtitles/' + jid || '/scheduling');

        this.navBar.leftAction().link(url);
        this.navBar.leftAction().text(jname); // <-- leftAction().text() always overwritten
}
```

The same code is duplicated in ``activities/serviceAddresses.js``.

I think I want to change this code to something like this:

```javascript
    else {
        // Reset to defaults, or given title:
        this.navBar.leftAction().model.updateWith(this.defaultLeftAction, true);

        var jid = this.viewModel.jobTitleID(),
            jname = this.viewModel.jobTitle() && this.viewModel.jobTitle().singularName() || 'Scheduler',
            url = this.mustReturnTo || (jid && '/jobtitles/' + jid || '/scheduling');

        this.navBar.leftAction().link(url);
        this.navBar.leftAction().text(this.requestData.navTitle || jname);
}
```

Questions:
1. Do my proposed changes make sense for how this code is used?
2. Should I also update the same code in ``servicesAddresses.js``? Ideally this would be in shared code somewhere, but I don't think I want to change that as a part of this issue.

**Comment by situatedbit** [comment]
I made the code change I suggested above, but I can undo it if necessary.

**Comment by situatedbit** [comment]
I think issue 282 is done, pending a review from @IagoSRL 

Notes
- I removed an unused field in ``activities/serviceProfessionalService.js``
- I added new routes to serviceProfessionalService/ to include client ID
- clicking on the services summary on the client editor (from #276) navigates to services professional services activity.
- In #302 I will add client ID to serviceProfessionalServiceEditor when coming from serviceProfessionalService with a clientID set

**Comment by IagoSRL** [comment]
CR this branch commits and looks OK. I did a quick local test and seems works as wanted here; obvious bugs because edit/create depends on #302, and back links problems (I know this is complicated).

Changes looks able to merge back without conflict https://github.com/loconomics/loconomics/compare/is276-client-specific-offering-summary...is282-manage-client-specific-offerings
