### ISSUE TITLE
Routing Libraries

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#283]
@IagoSRL do we have any libraries to help with parsing route segments currently in our environment? 

I want to try something more declarative than matching through several ``if`` statements on ``route.segments`` within activities. I _do not_ intend to modify routing or parsing URLs in the app shell.

Considering making a small helper object with https://github.com/rcs/route-parser

**Comment by IagoSRL** [comment]
Answering the question: no.

That lib looks good. Not tight to a framework, no direct execution of controllers.

Recently was thinking on use URL patterns, so I understand the motivation for the proposal :-).
A casual tweet had point me to https://github.com/tunnckoCore/gibon, is small, independent, but it automatically execute a handler (the route controller), what may fits or not some use cases. Maybe too simple patterns options.

I think would be good to pick up a real case (an activity with complicated segments analysis) and see how could look refactored with *route-parser*, to see the benefit, if doesn't take too much time (not sure if an additional helper around the lib is needed); sounds good?

**Comment by situatedbit** [comment]
I was playing with this in #282: https://github.com/loconomics/loconomics/compare/is282-manage-client-specific-offerings

I think we'll be adding two "routes" to this activity soon. They're commented out. Let me know what you think. I'm not fully committed to it, but I feel ok. 

I really enjoy using declarative routing systems in other platforms. If we could move toward that with the app that would be great. This doesn't get us any closer to that, but I think it's helpful for parsing parameters as we currently use them in activities.

**Comment by IagoSRL** [comment]
@situatedbit Since we agreed to use your proposal here, and the routing library is being in use already, I will close this issue.
Do you want to add some additional info about this topic? maybe add docs or link examples?

**Comment by situatedbit** [comment]
To document for posterity:
- I added a routing utility through #4. (``utils/Router.js``). Documentation for usage is there. It uses https://github.com/rcs/route-parser
- Currently it is only useful for parameter matching and constructing URLs
- In the future, I think it would be worthwhile to use a routing library to do route matching in the app shell. In that case, we may choose a different helper library. I think ``route-parser`` can be swapped out without too much difficulty.

**Comment by IagoSRL** [comment]
Thanks @situatedbit for the extra info (I added a link to the Router.js file in your comment ;-).
