### ISSUE TITLE
Question: why do some appointment conflicts occur?

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#300]
@IagoSRL @joshdanielson I could spend a lot of time and investigate this further on my own, but I'm wondering if one of you know the answer to this off the top of your head – 

Normally when a professional has booked appointments, those appointment times are not available when a client is trying to book a new appointment. However, sometimes as a client I'm able to choose a time from the available time slots, and then see an error message that one of those times isn't available. Why are the available time slots sometimes blocked off, but sometimes not blocked off?

![booking-error](https://cloud.githubusercontent.com/assets/6644016/23568404/2f0cf32e-000f-11e7-8fa7-8c3100a274a0.png)

**Comment by IagoSRL** [comment]
The only situation this may happens must be because of concurrency (several events/bookings generated for the professional for same or overlapped times at the same time)....when not, is a bug.

And is not the *first* time we have one of this, and with time-zones support even more. I though all have being fixed. Need depth review.

**Comment by IagoSRL** [comment]
Had the same message now doing a further testing of *master*, looking at it.

**Comment by situatedbit** [comment]
ok - thank you. If I see it again I'll do a little digging as well.

**Comment by IagoSRL** [comment]
On my case the problem was with checking a time that was at midnight when converted to UTC. Will note to myself to review more, may be time to refactor a method marked as *Obsolete*.

**Comment by situatedbit** [comment]
@IagoSRL I tried reproducing this on _dev_ based on your comment in #325. I wasn't able to reproduce it. I tried creating several bookings today and in the future. 

Unfortunately, when I created this bug I didn't have a systematic way to reproduce it, so I can't guarantee that it was fixed, but it looks positive.

**Comment by IagoSRL** [comment]
Thanks @situatedbit for your testing. I know this is difficult to reproduce, I will close #325 and we will open any new issue for that error message if happens again.
