### ISSUE TITLE
Question label

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#301]
@joshdanielson I would like a _Question_ label in Github for when I create issues that are basically just questions to you and/or Iago.

**Comment by joshdanielson** [comment]
@situatedbit I guess this to me is the same as an @ mention. Are your questions not getting answered that way now (which may be the case)?  Would it help to change the Assignee temporarily? Then we don't need a label for every person whom we have a question for.

**Comment by situatedbit** [comment]
I have no problem with the way things are. All good.
