### ISSUE TITLE
Add TrialEndDate to Users Table

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#305]
Child Story | Target Persona(s) | Investable 
------------ | ------------- | ------------- 
I need to be able to ensure new users get the full trial they're offered when signing up, currently a default of 30 days | Loconomics Staff | - 
**Test Cases** | 
1) Make sure when a new user signs up that the TrialEndDate is set to CreatedDate plus 14

### Front-end
-  
### JS
- 
### API
-  
### Database
- [x] Add following fields to Users table
  - TrialEndDate

**Comment by IagoSRL** [comment]
Done at branch *is191-coop-membership*, uploaded to *dev* (all changes are SQL on database -tables and store procedure).
