### ISSUE TITLE
Professional sees client-specific offerings during booking

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#309]
Spin-off from #4.

Story:
Professional sees offerings specific to that client when booking for that client

After selecting a client/job title, the offerings a professional can choose should include any offering available to the client -- both public and client-specific.

Separate client-specific pricings. List them before public offerings.

Under each category, allow the professional to create offerings.

```
special services for matt
  + add new special service for Matt

special consultations for matt
  + add new special consultation for Matt

services
  + add new service

consultations
  + add new consultation
```

**Comment by situatedbit** [comment]
Just found a bug during booking. 

After a provider selects services, if they include client-specific pricings, then on the date/time selection step, the label ("You need 15 minutes") does not reflect the time of the services selected.

The issue is a result of a model api call in AppointmentView that will not include client-specific pricings. 

I'll take a look at this next week.

**Comment by situatedbit** [comment]
The bug above happens because appointment card/view view models load services using ``getObservableItem``. That call doesn't return services that are client-specific. But, it also reveals a more subtle bug. Because we're using ``getObservableItem``, there is a race condition in the current code:

During booking, after services have been selected, ``pickDateTime()`` in ``AppointmentCard`` calls ``AppointmentView.getServiceDurationMinutes()`` (https://github.com/loconomics/loconomics/blob/is4-client-specific-offerings/app/source/js/viewmodels/AppointmentCard.js#L449). This uses a computed observable that depends on a service object. The service object is loaded using ``getObservableItem`` (https://github.com/loconomics/loconomics/blob/is4-client-specific-offerings/app/source/js/viewmodels/AppointmentView.js#L105).

The race condition happens because ``pickDateTime()`` immediately binds the value to ``requiredDuration``. Under normal conditions, ``getObservableItem`` will get the service object from the cache. However, if the service isn't in the cache, this call will return ``null``.

So, there are two issues:
1. I need to be able to load client-specific services
2. I need to resolve the race condition

I thought I could load the services using ``app.model.serviceProfessionalServices.getItem``, but because ``getServiceDurationMinutes()`` is called immediately, the race condition persists.

I don't want to refactor a lot of code to fix this, but I'm not sure how to load services.

**Comment by situatedbit** [comment]
After conversation with @joshdanielson, a new grouping for provider creating booking:

![professional-books-via-client-specific-pricing](https://cloud.githubusercontent.com/assets/6644016/24379709/1c0bd014-12fd-11e7-94a4-aa07ac9f6be6.png)

**Comment by situatedbit** [comment]
Update on this issue:
1. I'm documenting my refactoring of services grouping. 
2. I still have that outstanding bug with loading services during the booking process ↑

**Comment by situatedbit** [comment]
@IagoSRL I've refactored and documented the objects used in grouping the services listings. There are many variations in how we're displaying services in the following circumstances:
1. client books services
2. provider books services
3. provider manages services
4. provider manages client-specific services

Instead of handling all of these conditions in a single algorithm (too many ifs!), I created a common view model object that performs the _default_ grouping by pricing type: ``viewmodels/ServiceListGroup.js``. 

To handle the different cases above, I created factory functions in ``viewmodels/ServiceListGroupFactories.js``. These factory functions use objects that inherit from ``ServiceListGroup``, but override functions to handle the variation between the cases (the template method pattern). These objects are internal to the ``ServiceListGroupFactories`` module. Only the factory functions are exported and used by serviceProfessionalServices activity to produce service list groups for the templates.

I am happy to talk through the details with you. I want to make sure that the code conveys its intent.

**Comment by situatedbit** [comment]
I can look at the bug again tomorrow morning (my time)

**Comment by IagoSRL** [comment]
@situatedbit Not sure if you prefer to keep this issue open while fixing the know bug or do it at #4. Just feel free to close this if you want.

I updated #4, cross out the other closed issues, please review and mark the tasks done at the initial comment.

**Comment by situatedbit** [comment]
I'll move the bug description into #4.
