### ISSUE TITLE
client sees specific pricings during booking

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#322]
From #4.

*Story*: When client books service, they should be able to see all offerings specific to them.

- [x] On services page during booking, show client-specific pricing
- [x] Reload services when non-logged in user logs in during booking process
- [x] verify that this API call is still needed with #4: ``users/{id}/service-professional-services/{job-title}``: bookable by client. If it's not needed, then remove it.

**Comment by situatedbit** [comment]
@IagoSRL 
I think this item is completed. 

Because ``viewmodels/ServiceProfessionalService.js: groupedServices`` will vary depending on the activity that uses that view model, I started to pull out the grouping logic into a separate module. Each activity can use its own grouping module by setting its own ``groupServices`` function. After I work on #309, I think handling different cases for grouping services will become less complex.

**Comment by situatedbit** [comment]
(Also, I didn't create a pull request, but pushed the issue branch: https://github.com/loconomics/loconomics/compare/is4-client-specific-offerings...is322-client-sees-specific-pricing-in-bookingl

**Comment by IagoSRL** [comment]
@situatedbit I did review the commits linked on this issue, just one comment (you saw it already), not sure if you were expecting this before close this issue or there are additional work you need to do.

**Comment by situatedbit** [comment]
Thank you!
