### ISSUE TITLE
Link to client manager from services manager

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#323]
From #4. 

Story: Professional sees link to user management page while creating new pricing or managing offerings in scheduler, in case they want to operate on client-specific offerings

**Comment by situatedbit** [comment]
Cases when provider sees the link:
- managing services: yes
- managing services for client: no
- adding service: yes
- selecting service for booking: no

**Comment by IagoSRL** [comment]
PR merged, closing
