### ISSUE TITLE
Profile link on job title search results page goes to wrong job title

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#326]
Live.

As a client, when I search for a professional by their job title and then click on that professional's name to view their profile, I don't necessarily see the profile for the job title that I searched for. If the professional has more than one job title, I will see their "default" job title regardless of what I searched for.

Here's an example.
1. Search for "comedians". Click on "Go" to view all comedians.

![01-search](https://cloud.githubusercontent.com/assets/6644016/24169998/9489a068-0e3c-11e7-803a-52ff131d5735.jpg)

2. Click on the name of a professional comedian, assuming you will see the comedian job profile.

![02-browse](https://cloud.githubusercontent.com/assets/6644016/24169988/8d357ac6-0e3c-11e7-9693-8177ab2eb26d.jpg)

3. In this case, the dog walker profile of the professional appears first. This should be the Comedian profile for this professional.

![03-profile](https://cloud.githubusercontent.com/assets/6644016/24169982/8a80076a-0e3c-11e7-8717-5b5e0bde45b0.jpg)

**Comment by IagoSRL** [comment]
Merged, thanks!
