### ISSUE TITLE
Bug S3: Join up link on learn more page for logged in professionals

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#338]
The "join up" button is still included twice on the _learn more_ page when a professional is logged in. At the very least, the buttons should be removed. 

Other options:
1. Should this page even be in the header for logged-in profesionals?
2. Should this page be replaced with other content for logged-in professionals who haven't joined the co-op yet?

![logged-in](https://cloud.githubusercontent.com/assets/6644016/24632337/a33e79e4-1878-11e7-938f-a57b9cc629b7.jpg)

**Comment by joshdanielson** [comment]
LearnMore page is no longer accessible to logged in professionals.
