### ISSUE TITLE
Evaluate business reqs for onboarding data

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#343]
From #330 

Goal: Identify the data gathered in the current onboarding process that is required/desired during the onboarding process and what can be pushed to later enhancements or can be skipped. 

Tasks

1. Identify all data points gathered during current onboarding
2. Categorize data points: Required, Desired, Skippable, Postponable
3. Create new Epics for removing individual data points _and for supporting their completion post-onboarding_.

**Comment by situatedbit** [comment]
![onboarding-mapping-ideas](https://cloud.githubusercontent.com/assets/6644016/24672914/42ee6e06-192b-11e7-9f4b-f784cf3e4071.jpg)

**Comment by situatedbit** [comment]
@joshdanielson I would also like to move this one into top priorities. It will pave the way to shortening up onboarding, which would make sense prior to integrating value propositions.

**Comment by joshdanielson** [comment]
Done!

**Comment by situatedbit** [comment]
Josh: " I think our onboarding should be able to be finished within 10 minutes"

**Comment by joshdanielson** [comment]
- review GA capabilities for time spent on page
- create issues/stories for making changes

**Comment by situatedbit** [comment]
![img_20170419_111240](https://cloud.githubusercontent.com/assets/6644016/25195134/825a9e8a-24f1-11e7-9cd1-31e132e7ec8c.jpg)

**Comment by situatedbit** [comment]
https://loconomics.mybalsamiq.com/projects/onboarding-optimizaton/grid

**Comment by situatedbit** [comment]
# Current Onboarding + Information Required

![current-onboarding](https://cloud.githubusercontent.com/assets/6644016/25347106/a5c7c402-28ce-11e7-86d1-11ea7c6e4596.png)

**Comment by situatedbit** [comment]
# Current Status on Onboarding Thinking

![new-onboarding-midthought](https://cloud.githubusercontent.com/assets/6644016/25347171/cf1e6770-28ce-11e7-8000-c5a332d7e41f.png)

**Comment by situatedbit** [comment]
*Updated Onboarding Thinking*

![onboarding-paths](https://cloud.githubusercontent.com/assets/6644016/25675522/9d8d0b72-2ff3-11e7-8788-64bfd2853acc.jpg)

**Comment by situatedbit** [comment]
The diagram above outlines the direction we want to go with onboarding. After conversation with Josh, we're going to prioritize the following items for the time being:
1. remove services overview from onboarding
2. remove booking policy from onboarding
3. improve usability issues on forms used during onboarding

I'll create issues/epics for these.
