### ISSUE TITLE
Revise Onboarding Copy

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#348]
- [ ] Add value proposition to each onboarding step
   - space for icon and copy up top
   - inline reinforcement using placeholders and label text
- [ ] Explain it what happens to you/what happens next/how it works, e.g. within 24 hours your profile will appear in the marketplace. If you want to add your clients, add your clients
- [ ] Clarify how information entered will be used, e.g. email address (clients will only see this after they book you)
- [ ] Post-onboarding requests - what is the next step in getting people to use the system?
   - now let your clients know you're here
   - attend a workshop
   -

**Comment by situatedbit** [comment]
![scheduling-preferences-notes](https://cloud.githubusercontent.com/assets/6644016/25461542/6b9a4a44-2a9e-11e7-8224-180ec417b0ff.jpg)

**Comment by IagoSRL** [comment]
Is this ready for testing? (it's at QA pipeline). What and who needs to test?

Based on latest @situatedbit design posted, there is something that requires being split to another, less priority, issue?

**Comment by joshdanielson** [comment]
I guess I didn't think about testing copy changes but I suppose a quick look at the commits to make sure there aren't missing tags and it can always use an extra set of eyes for spelling (like last week). 

Yes, it's ready for a quick review and merge!
