### ISSUE TITLE
Create Personas

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#355]
Sufficient for onboarding, at least to start.

Current persona placeholders: https://github.com/loconomics/loconomics/tree/master/docs/Personas

We can time-box this item to 2 hours. This should be sufficient to describe and document 3-4 personas. 

Reference for personas + process for creating them: https://drive.google.com/file/d/0ByA0sHJADr7UUW5tTThtVGl5aVU/view

**Comment by situatedbit** [comment]
![img_20170419_123139](https://cloud.githubusercontent.com/assets/6644016/25198422/54b2b9ee-24fc-11e7-8373-52412d324bc5.jpg)

**Comment by situatedbit** [comment]
![img_20170419_155835](https://cloud.githubusercontent.com/assets/6644016/25205769/34cce24a-2519-11e7-88cf-8261e1b4ff40.jpg)

**Comment by situatedbit** [comment]
(Item above: a persona we wanted to create, but ran out of time)

Matt:
[ ] add photos
[ ] move to easy-to-find location

**Comment by joshdanielson** [comment]
@situatedbit we should do a quick read through of Denise's persona qualities to see if they could be added

**Comment by situatedbit** [comment]
Master Document: https://docs.google.com/document/d/1jIFXIF7zRiYcdB7jJ1EVjGzEJnVKrK8zF92nZ5n_B90/edit

- Charlie: https://drive.google.com/open?id=0ByA0sHJADr7UQ0hkY1BNbTctNTA
- Devin: https://drive.google.com/open?id=0ByA0sHJADr7UVlZ1aXRBeXNLSHM
- Morgan: https://drive.google.com/open?id=0ByA0sHJADr7UcTZNankzN0xBQ0E

**Comment by situatedbit** [comment]
Created pull request with new personas. Removed them from google so they are accessible for everyone. Removed the stock images I had added because they aren't creative commons or something similar. 

https://github.com/loconomics/loconomics/pull/364
