### ISSUE TITLE
Add sign-up functionality on Landing Pages

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#366]
Awaiting completion of #312

**Comment by situatedbit** [comment]
Created branch ``is366-signup-from-landing-page`` from ``is226-create-profession-specific-landing-pages``. Will merge back in to complete #226

**Comment by IagoSRL** [comment]
@situatedbit With all your work here and latest fix for the redirect, I think this is done, moving the issue to QA.

I merged this issue branch (is366-signup-from-landing-page) into the landing pages branch #226 (is226-create-profession-specific-landing-pages) and I think we must already stop committing and close is366; any last minute fix to this must go to is226 directly from now, preventing conflicts and simplifying bugfixes.

**Comment by IagoSRL** [comment]
I tried this several times even testing other issues that depended on this so I think is everything fine.

Just in case: @joshdanielson Did you tested to signup using the welcome page at dev? (https://dev.loconomics.com/welcome/massageTherapists.html)

**Comment by joshdanielson** [comment]
@IagoSRL I did! I guess I forgot to put the label, sorry.
