### ISSUE TITLE
Bug S2: Profile link appears in mobile menu when not logged in

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#370]
Currently on dev but _not_ live.

On the narrow layout, when I'm not logged in there is a link to my profile. It shouldn't be there unless I'm logged in:

![profile-link](https://cloud.githubusercontent.com/assets/6644016/25496485/06354c2e-2b36-11e7-8edf-568575c8b93f.jpg)

**Comment by ardanak** [comment]
@situatedbit I wasn't able to reproduce the error in chrome dev tools with the mobile device setting. Am I missing something?

**Comment by joshdanielson** [comment]
@ardanak and I couldn't reproduce so closing.
