### ISSUE TITLE
Bug S1: Learn More Professionals page URL fails

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#371]
On dev, but _not_ on live: 

The _learn more professionals_ page does not render within the app.

![learn-more-professionals](https://cloud.githubusercontent.com/assets/6644016/25496659/92e58530-2b36-11e7-8c75-e969341a50e5.jpg)

**Comment by situatedbit** [comment]
This appears to be a bug in #226

**Comment by IagoSRL** [comment]
Is fixed on my 331 branch, an error setting the signup.countryID() that now is country() with different value (I just removed the line, the default preset is fine there)

**Comment by situatedbit** [comment]
ok - I'll close this.

**Comment by IagoSRL** [comment]
I should have fix it there first

**Comment by IagoSRL** [comment]
Just backported the fix into is226
