### ISSUE TITLE
Bug S1: Facebook signup fails with popup blocker

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#373]
When the browser is blocking popups, signing up with Facebook fails, even if the user then allows the popup to be displayed after it was _initially_ blocked.

To reproduce:
1. In Chrome, for example, disallow popups for dev.loconomics.com.
2. Navigate to the sign up page.
3. Try to sign up with Facebook.

![signup-fb-01](https://cloud.githubusercontent.com/assets/6644016/25543927/41e628e2-2c0d-11e7-9e79-737e2e5a2fb9.jpg)

4. First, the popup will be blocked.
5. Show the popup anyway.

![signup-fb-02](https://cloud.githubusercontent.com/assets/6644016/25543934/474003ee-2c0d-11e7-9250-29942f50ac9d.jpg)

6. The content of the popup will not render and the sign up process will not continue (even if you are already signed into Facebook or have already given Loconomics permission to use your Facebook account).

![signup-fb-03](https://cloud.githubusercontent.com/assets/6644016/25543941/4d2abe70-2c0d-11e7-90ef-7f0a30c1e06c.jpg)

Note: I tested several combinations of situations: popup blocker, already-sign-in to facebook vs not signed in to facebook, Loconomics already connected with Facebook vs not-yet connected with Facebook. Consistently, the problem occurred when the popup dialog was _initially_ blocked.

**Comment by situatedbit** [comment]
I suspect the issue is around facebookUtils: loader use, but I need to dig further to test.

**Comment by situatedbit** [comment]
Here is what I think is happening. I can't confirm it yet, because I would have to test it on dev, but at least this is a start.

In ``utils/facebookUtils.js``:
1. When the popup blocker is enabled, ``FB.login`` does not call the response function. [``FB.login`` creates a popup window](https://developers.facebook.com/docs/reference/javascript/FB.login/v2.8).
2. Browsers typically [only allow popups in direct response to user action (e.g., a click)](http://stackoverflow.com/questions/2587677/avoid-browser-popup-blockers).
3. We call ``FB.login`` in code that is called asynchronously after a click: the user clicks _Sign up with Facebook_, we use ``loader.js`` to load the Facebook connect script asynchronously, then in a _callback_ we call ``FB.login``.

- The most direct way to fix this is to always load the facebook connect script :-1: 
- Alternatively, [we can load the facebook script synchronously](http://stackoverflow.com/questions/2879509/dynamically-loading-javascript-synchronously). The browser will lock up while the script is loading. We would want to change the language on the signup form while Facebook is loading/initializing.

@IagoSRL Are we using any tools to load javascript synchronously? Which resolution do you prefer?

**Comment by situatedbit** [comment]
Another idea:
1. Add a method (``f()``) to Facebook utils allowing us to load the Facebook script asynchronously.
2. Add an observable to Facebook utils indicating when the Facebook API is loaded.
3. Modify Signup view model to call ``f()``
4. Modify Signup view model to not respond to clicks on the Facebook button until the Facebook API is loaded.

**Comment by situatedbit** [comment]
@IagoSRL I implemented the Facebook utils part of my third idea and committed it to ``is373-facebook-popup``. I implemented 1-3 above, but I didn't modify the signup template or use facebookUtils.isReady() in Signup. 

Since this item is blocked on #367 I won't finish this right now. 

If you want to finish this one on Monday, I am OK with that.

**Comment by situatedbit** [comment]
i have this working for signup on landing page, normal signup, and through booking.

I realize now that this problem also occurs with login via facebook. I'll add the same code to the login process next.

**Comment by situatedbit** [comment]
Created pull request.

@IagoSRL this item needs to be tested on _dev_. I tested it as far as I could locally, but please assign to @joshdanielson when you have a chance to move it to dev. I'm not sure if you should merge it into master first or not.

Test: 
(Unfortunately you need to delete your facebook-created user after each of these scenarios).

With the popup blocker active on dev.loconomics.com, use your Facebook account:
1. As client, sign up as new user during booking
2. As a service professional, sign up as new user from the learn more page
3. As a service professional, sign up from a landing page
4. As a service professional, sign up from the normal sign up page
5. After you've created a user, log in using Facebook

**Comment by joshdanielson** [comment]
@IagoSRL @situatedbit this is now working for me. The Delete User stored procedure must not delete from webpages_FacebookCredentials. I cleaned up that table for my old users and all works now.

Close when ready.
