### ISSUE TITLE
Bug S1: JobTitleID not getting passed into servicesOverview

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#374]
I know this has happened in the past so not sure if something changed. 

![screen shot 2017-04-28 at 4 11 31 pm](https://cloud.githubusercontent.com/assets/1202838/25550420/9923d602-2c2d-11e7-90b7-93f18398ab00.png)

**Comment by joshdanielson** [comment]
Just confirming that this is happening on live now. Let's do a fix in the next release if possible.

**Comment by situatedbit** [comment]
I think the source of this problem is similar to #381: when skipping adding a job title, onboarding selectedJobTitleID isn't set during app initialization.

Blocked on #381

**Comment by joshdanielson** [comment]
@IagoSRL this is still happening. I signed up from a landing page and selected a job title.

![screen shot 2017-05-03 at 7 24 18 am](https://cloud.githubusercontent.com/assets/1202838/25665159/98a4e49e-2fd1-11e7-9b9d-ec10cf219509.png)

**Comment by IagoSRL** [comment]
The forgotten server files are updated now, please test again. and sorry

**Comment by joshdanielson** [comment]
@IagoSRL just tried again and got something really weird. I selected "Groomer" on the landing page and it still asks to select a job title but is not groomer:
![screen shot 2017-05-03 at 7 44 51 am](https://cloud.githubusercontent.com/assets/1202838/25666157/846eb11e-2fd4-11e7-8b23-40bcd112bf1b.png)

**Comment by IagoSRL** [comment]
Checking dev database, that looks like the job title assigned for the ID 303, that is the ID from the landing page dropdown for Grommer.

```select * from positions where positionid = 303```
<pre>
303	1	1	Cake Walker	Cake Walker			2015-12-10 15:21:25.790	2015-12-10 15:21:25.790	ur	NULL	NULL	NULL	1	NULL		0	0	0	514	NULL	0	0	1	0	0
</pre>

**Comment by IagoSRL** [comment]
Still, that screen must not appear, I'm reviewing again.

**Comment by joshdanielson** [comment]
Good point! Sorry.

**Comment by IagoSRL** [comment]
I did three more trials at *dev*. First failed, like in you latest screenshot, the two last worked. Maybe just the browser cache with a old preloaded js.

**Comment by joshdanielson** [comment]
@IagoSRL it worked in firefox and in chrome in an incognito window so must be the cache. Close when you're ready.
