### ISSUE TITLE
Bug S1: Onboarding progress not working

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#380]
Doesn't seem to be working on any step.
![screen shot 2017-05-01 at 5 56 38 pm](https://cloud.githubusercontent.com/assets/1202838/25600196/4478f788-2e97-11e7-8cb5-7fe2796b27c3.png)

**Comment by situatedbit** [comment]
I think the source of this problem is the same as #381: when skipping adding a job title, onboarding.setStep is not called with the correct step during app initialization. Then the step never increments and the progress indicators always show that you are on step 0. 

Blocked on #381

**Comment by situatedbit** [comment]
I also tested this on dev. Looks good. Removing myself as an assignee.

**Comment by joshdanielson** [comment]
@IagoSRL I also tested on dev and working.
