### ISSUE TITLE
Bug S1: Form/Agreement text should be hidden after submitting payout info

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#381]
http://loconomics.com/#!/paymentAccount
- I created a Venmo payout and got this screen:
![screen shot 2017-05-01 at 6 01 08 pm](https://cloud.githubusercontent.com/assets/1202838/25600299/f06e43ae-2e97-11e7-84d2-d80105f20454.png)

Also, Form/Agreement text should be hidden after submitting payout info (I noticed this across the site...was fixed temporarily after happening a while back).

**Comment by joshdanielson** [comment]
After refreshing the page a few minutes later, it was approved (and form hidden) but still no way to get out of onboarding easily:
![screen shot 2017-05-01 at 6 06 00 pm](https://cloud.githubusercontent.com/assets/1202838/25600364/8d6565f2-2e98-11e7-8874-5257363dbc61.png)

**Comment by joshdanielson** [comment]
Or really at all:
![screen shot 2017-05-01 at 6 07 27 pm](https://cloud.githubusercontent.com/assets/1202838/25600380/b1907764-2e98-11e7-9d9b-81eaee79335e.png)

I'm also thinking this could be isolated to venmo. Will try another user with a normal bank account.

**Comment by joshdanielson** [comment]
Same happened with using my savings account.

**Comment by joshdanielson** [comment]
Also, strange but it worked when I signed up as a massage therapist from the learnMore page:
![screen shot 2017-05-01 at 6 25 51 pm](https://cloud.githubusercontent.com/assets/1202838/25600805/ae5663c6-2e9b-11e7-8508-3a6a53fece7e.png)

**Comment by IagoSRL** [comment]
Uploaded to *dev* fix for the blocking bug here, and it fixes #380 too

**Comment by joshdanielson** [comment]
@IagoSRL tested on dev and working.
