### ISSUE TITLE
Bug S3: Error loading clients

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#382]
When clicking on "Client Manager" after having added a client (did not give the error before)
![screen shot 2017-05-01 at 6 57 29 pm](https://cloud.githubusercontent.com/assets/1202838/25601299/dfd35112-2e9f-11e7-8032-3252c60fd2da.png)

**Comment by situatedbit** [comment]
@joshdanielson does this always happen to you?

**Comment by joshdanielson** [comment]
Fortunately or unfortunately, no. I"ll create a new one if/when it happens again and record the api calls. Closing.
