### ISSUE TITLE
Revise profile photo button language to be dynamic

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#388]
- Change photo should said "Upload photo" if there isn't a photo already uploaded
- Rotate photo should only appear if a photo is uploaded

**Comment by IagoSRL** [comment]
2

**Comment by joshdanielson** [comment]
2

**Comment by situatedbit** [comment]
2

**Comment by situatedbit** [comment]
2

**Comment by situatedbit** [comment]
I think this is no longer a 2. 

After doing some digging into how we are storing profile photos, it does not appear that the API reports whether the user has already uploaded a photo. This would require a change to the API in addition to changing the labels on upload form. 

@IagoSRL do you know of a _quick_ way to implement this? If not, I've spoke to @joshdanielson and we think this is no longer a top priority if it is more than a 2.

**Comment by situatedbit** [comment]
@joshdanielson I'm going to send this one to the bottom of top priorities.

**Comment by IagoSRL** [comment]
Add a 'hasUploadedPhoto' property to REST API and Model about user profile (User model)

**Comment by IagoSRL** [comment]
Implemented, @joshdanielson  ready for testing at the is388 branch

**Comment by joshdanielson** [comment]
@IagoSRL tested, working, closing.
