### ISSUE TITLE
Make all service attribute categories optional

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#389]
Part of https://github.com/loconomics/loconomics/issues/392. (See story there)

Because we want to allow professionals to gradually enhance their profile, none of the fields in the current "services overview" form should be required.

To complete this item:
- remove any requirement validation from the app - wasn't required
- remove any requirement validation in the API - wasn't required
- Update API documentation - wasn't required
- Default the services description to an empty string (already is)

Updated in Dev and Live databases:

`UPDATE Dev.dbo.serviceattributecategory SET RequiredInput = 0 WHERE LanguageID = 1 AND CountryID = 1;
`

**Comment by joshdanielson** [comment]
@situatedbit @IagoSRL ready for review.

**Comment by IagoSRL** [comment]
There was no upgrade script at repo for this, I added it.

I executed this too at *dev* as part of pushing there #392, and result was
> (149 row(s) affected)
