### ISSUE TITLE
Remove services overview form from onboarding sequence

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#390]
Part of #392. (See story there)

Depends on #389, #393, #394.

To complete this item: 
- remove onboarding code from the servicesOverview app activity
- remove servicesOverview from the app onboarding model

**Comment by situatedbit** [comment]
2

**Comment by IagoSRL** [comment]
2

**Comment by joshdanielson** [comment]
2

**Comment by situatedbit** [comment]
committed to [is392-optional-services-overview](https://github.com/loconomics/loconomics/compare/is392-optional-services-overview)

**Comment by joshdanielson** [comment]
@situatedbit tested in branch.
