### ISSUE TITLE
Make services overview button label more explicit

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#391]
Part of #392.

Persona:
[Morgan, established massage therapist](https://github.com/loconomics/loconomics/blob/master/docs/Personas/Morgan.md)

Story:
As a newly-signed-up professional, after I've created my initial listing, I want to know that I can add details to my profile to enhance it, but I don't want to have to explore all of the buttons under my new listing admin page. Because I'm new to Loconomics, I'm not familiar with what I can add to my profile. I'd like to know the kinds of items I can add to my profile via the services overview label on the listing page.

To complete this item: 
- update the button label text on the listing page

Label text ideas:
- Enhance Your Listing
_Overview, specialization, services offered, experience level_
- Listing Details
_What your clients should know about you and your services_
- Services Overview
_What your clients should know about your services_

**Comment by situatedbit** [comment]
1

**Comment by joshdanielson** [comment]
1

**Comment by IagoSRL** [comment]
2

**Comment by situatedbit** [comment]
Due to display constraints, I went with:

**{Job Title} listing details**
_Tell clients about what you do_

**Comment by joshdanielson** [comment]
@situatedbit tested in branch.
