### ISSUE TITLE
Remove services overview from onboarding

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#392]
Persona:
[Morgan, established massage therapist](https://github.com/loconomics/loconomics/blob/master/docs/Personas/Morgan.md)

Story:
Because I'm still trying to figure out whether Loconomics is right for me, as a newly-signed-up professional with an established practice and client base, I want to start seeing what my profile looks like quickly and be able to enhance it later. Therefore, I'd rather fill out the content on services overview after I create an initial copy of my profile than during onboarding.

Other reasons to move out of onboarding:
- Users may be on a phone and uninterested in completing large form until they can move to a different device
- Distinction unclear between offerings and service details like "specializations" and "types of services" described on the services overview form

**Comment by situatedbit** [comment]
@joshdanielson I think I've completed all of the items in this epic. Can you please test this on your local machine before I create a pull request and @IagoSRL reviews it?

The branch is ``is392-optional-services-overview``

I'm gong to assign the epic to you, but keep the child items assigned to me until you've tested this, then I'll create a PR and assign to @IagoSRL

**Comment by joshdanielson** [comment]
@situatedbit testing now...

**Comment by situatedbit** [comment]
Assigned to Iago for pull request https://github.com/loconomics/loconomics/pull/432

**Comment by IagoSRL** [comment]
Reviewed, tested, uploaded to *dev* and child issues closed too.
