### ISSUE TITLE
Migrate users from services overview onboarding step to the next step

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#393]
Part of #392.

Depends on #389.

Because we are removing services overview from onboarding, some professionals will have stopped onboarding at the "servicesOverview" stage. For those users, we should update the database to move them to the next step in onboarding.

**Comment by situatedbit** [comment]
2

**Comment by IagoSRL** [comment]
1

**Comment by joshdanielson** [comment]
2

**Comment by situatedbit** [comment]
working in branch is392-optional-services-overview

**Comment by situatedbit** [comment]
Added SQL to migrate onboardingstep column in users table. 

I committed it to `` is392-optional-services-overview``

I _did not_ run it against the Dev database.

**Comment by situatedbit** [comment]
@IagoSRL moving this item to review and assigning it to you so you can run it on Dev with the rest of the items from this epic.

**Comment by IagoSRL** [comment]
Just a question here @situatedbit: the file is `is392-optional-services-overview - B1 - users-onboarding-data-migration.sql` If this is 'B1' there were are some point an 'A1'? (there is no more upgrade files on this issue).
I added `is392-optional-services-overview - C1 - attributes are optional.sql` for #389

On master, this will get renamed for the new release (7.10)

**Comment by IagoSRL** [comment]
I run it at *dev* already, since I pushed all #392 changes

**Comment by situatedbit** [comment]
There were no other SQL files. I think I misunderstood the naming convention for sql scripts per issue.

**Comment by IagoSRL** [comment]
No worry. The convention may need a review or updated docs, we can comment on next meeting about 'what to change'
