### ISSUE TITLE
Hide services overview on profile if missing

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#394]
Part of #392.

Because we are removing services overview from onboarding and removing them as a requirement in the profile, we should hide the "Overview of services" heading from the profile if there are no service attributes.

**Comment by situatedbit** [comment]
estimate: 2

**Comment by joshdanielson** [comment]
22

**Comment by IagoSRL** [comment]
2

**Comment by situatedbit** [comment]
working in branch is392-optional-services-overview

**Comment by situatedbit** [comment]
pushed to is392-optional-services-overview

**Comment by joshdanielson** [comment]
@situatedbit I got this error when I clicked "view my profile" after creating a dog sitter profile (skipping services overview was successful!)
![screen shot 2017-05-08 at 3 42 55 pm](https://cloud.githubusercontent.com/assets/1202838/25828471/2ad34b08-3405-11e7-801b-6b5a1226e368.png)

**Comment by situatedbit** [comment]
Josh, could you add a bit more context here? Was this right after you signed up? Had you gone to the services overview screen at all or otherwise cleared it out? 

I'm not able to reproduce it.

**Comment by joshdanielson** [comment]
@situatedbit it was directly after signing up and I clicked on "View my profile" from /onboardingSuccess.

**Comment by situatedbit** [comment]
I still wasn't able to reproduce it, but I tidied up some code that should address the issue. 

Also, I realize now that you're not going to be able to test this fully because of a bug remaining in the API on dev. You'll always see an experience level of "I'm new at this" on your profile, until the API on dev can be updated with the code in this branch.

**Comment by joshdanielson** [comment]
@situatedbit I'll try again now.

**Comment by joshdanielson** [comment]
@situatedbit I did NOT get the error again. Feel free to do a pull request.

**Comment by IagoSRL** [comment]
I tried to force the bug previously reported by @joshdanielson (setting at DB an intro of null) and it works OK.
