### ISSUE TITLE
Add additional landing pages

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#395]
- [x] /welcome/healing-arts-professionals
    - Massage Therapist	106
    - Reiki Practitioner	283
    - Nutritionist	141
    - Hypnotherapist	146
    - Rolfer	318
    - Life Coach	186
- [x] /welcome/licensed-professionals
    - Massage Therapist	106
    - Psychotherapist	193
    - Chiropractor	170
    - Acupuncturist	185
    - Esthetician	179
- [x] /welcome/local-service-professionals
    - Photographer	90
    - Tutor	32
    - Art Tutor	296
- [x] /welcome/home-care-professionals
    - Cleaning Professional	14
    - Gardener	22
    - Handyman	82
    - Electrician	34

**Comment by joshdanielson** [comment]
@IagoSRL @situatedbit ready for review.

**Comment by IagoSRL** [comment]
Published to *live*
