### ISSUE TITLE
Bug S3: Blank profile after onboarding with payment problems

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#398]
Josh onboarded and entered payment information that was ultimately flagged by Braintree. Nonetheless, his user completed onboarding and was directed to his profile, which is blank: 

![screen shot 2017-05-03 at 1 57 43 pm](https://cloud.githubusercontent.com/assets/6644016/25681502/5941fe1c-3009-11e7-9cd8-a7ea041f1aaf.png)

Potential solutions:

- Allow professionals to see their own profile even if they are not visible to the public
- Show a message on the profile indicating why the profile is not available

**Comment by situatedbit** [comment]
The profile is blank because the API call ``api/v1/en-US/users/{userID}`` returns a blank ``jobProfile`` object  if there aren't any job titles (``UserProfilePosition`` rows) where ``StatusID=1`` (active, public). Because the user hasn't yet created a payment plan, ``StatusID`` is not set to 1.

**Comment by IagoSRL** [comment]
Merged #485, the first task here is solved, only lacks the informative message, or is preferred to implement that as part of the new proposal for the profile activity?

**Comment by situatedbit** [comment]
I'm adding that in #437

**Comment by IagoSRL** [comment]
Perfect, closing this so.
