### ISSUE TITLE
Rename Booking Policies label

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#400]
On the listings page, the _Booking Policies_ label obscures that cancellation policies are also on that page. Change the label to _Booking and Cancellation Policies_.

**Comment by IagoSRL** [comment]
1

**Comment by joshdanielson** [comment]
1

**Comment by situatedbit** [comment]
1

**Comment by situatedbit** [comment]
This is in the ``marketplaceJobtitles`` activity.

**Comment by IagoSRL** [comment]
@ardanak's PR merged, closing.
