### ISSUE TITLE
Remove booking policies activity from onboarding sequence

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#401]
Part of https://github.com/loconomics/loconomics/issues/402

To complete this item:
- remove all onboarding code from the booking policies activity
- remove booking policies from the app onboarding model
- verify that by default, the policies default to _Acceptance required_ and _Flexible_ cancellation policy

**Comment by situatedbit** [comment]
2

**Comment by joshdanielson** [comment]
2

**Comment by IagoSRL** [comment]
2

**Comment by situatedbit** [comment]
Blocked on #433

**Comment by IagoSRL** [comment]
I'm not sure that this is blocked by #433; if the decision is to have default values for the policies, there is no a required alert that needs to be completed.

Can be an 'enhancement' alert, so we display it to users that have a plan that allow them to choose booking policies (the more restrictive ones does not allow that, we commented) and they have not entered and saved the form still (would need a way to know they have actively chosen the policies); or some other kind of reminder, but that's out of the scope of #433.

**Comment by situatedbit** [comment]
I agree. I removed the blocked label.

**Comment by IagoSRL** [comment]
Done at is584-epic-onboarding
