### ISSUE TITLE
Change nav title during onboarding to be listing-focused

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#403]
The current onboarding nav title is _Get Started_.

We are reorienting onboarding around creating the first listing. This is a more direct description of what onboarding is. 

I suggest we change _Get Started_ to _Create First Listing_ during the entire onboarding process.

**Comment by joshdanielson** [comment]
I like it! 

Adding to this is removing all href links. I did the main activities but some sub activities still have a link to the home page.

**Comment by situatedbit** [comment]
I estimated this, given that our estimation call is scheduled for tomorrow and I want to work on this today.

**Comment by situatedbit** [comment]
@joshdanielson What is this _Get started_ menu item used for? On most onboarding screens, it links to /. Is it mean to be a link to the home page or merely a label for onboarding? On the narrow/phone layout, it's only a heading, not a link.

I'm going to pause my work on this until I understand the background on this.

![get-started-link](https://cloud.githubusercontent.com/assets/6644016/25719729/4291c902-30bf-11e7-8b26-9496d5dcd332.png)

**Comment by situatedbit** [comment]
Created pull request #420

**Comment by IagoSRL** [comment]
Merged, thanks
