### ISSUE TITLE
Onboarding-specific save buttons

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#404]
To reiterate the point of creating a first listing during onboarding:

During onboarding, when appropriate, change the labels for activity form save buttons from _Save and Continue_ to _Save and continue creating first listing_ or _Continue creating first listing_.

In activities where items are already saved (e.g., new offerings or service locations), simply use _Continue creating first listing_.

/serviceProfessionalService
/licensesCertifications
/serviceAddresses

**Comment by situatedbit** [comment]
2

**Comment by IagoSRL** [comment]
1

**Comment by joshdanielson** [comment]
2

**Comment by situatedbit** [comment]
@joshdanielson I'm no longer convinced this is worth doing.

**Comment by joshdanielson** [comment]
@situatedbit I trust you...close if you want.
