### ISSUE TITLE
Validate service location zipcode on blur

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#405]
On the service location form, the zip code field validates negatively before the user finishes typing the zip code. 

![premature-validation](https://cloud.githubusercontent.com/assets/6644016/25685657/eaa9b804-301d-11e7-8eea-e931377fbf29.jpg)

Suggested change: do not validate the zip code (or display a message) until the user exists the field. Thereafter, update the validation as they type.

**Comment by IagoSRL** [comment]
2

**Comment by joshdanielson** [comment]
2

**Comment by situatedbit** [comment]
2

**Comment by situatedbit** [comment]
changing estimate to 3 because current implementation of postal code lookup and address update doesn't have clear access to zipcode fields in order to know when there is field focus or blur.

**Comment by IagoSRL** [comment]
@situatedbit If you really only want to validate on blur, you can replace the use of 'textInput' by 'value' at the data-bind attribute, just for the postalCode field. That's actually trigger only on blur (by default). I think that way you can even keep the current logic of *createPostalCodeAutolookup*.

Maybe I misunderstood the point of the problem and is not so easy as that.
In that case, we can refactor that shared module to directly export the 'lookup' function (`exports.lookup`), that you can call in the viewmodel-databinding when you want, and too an 'auto' (`exports.auto`) that just creates the computed that trigger the internal lookup if there are still cases when is wanted (or drop it if not wanted at all).

**Comment by situatedbit** [comment]
I want a slightly different interaction: 
- lookup on value change
- if creating a postal code, only show validation error on blur
- if editing a postal code, always show validation error

The problem with only doing a lookup on blur is there isn't enough feedback to the user once they enter a correct postal code. Unless the tap or click out of the field, they won't see the city update.

I think we want similar behavior in all instances of postal code lookup. 

My idea is to refactor createPostalCodeAutolookup into a view model. It would still update address models like it currently does. In the template we can add view model handlers for blur and focus.

**Comment by situatedbit** [comment]
@IagoSRL there is one path that I don't know how to test. How can I edit an appointment's location as a client? I've created an appointment request with a new location within a service area, but even after it is confirmed by the professional, the client is unable to modify the location. How can I test client-appointment-card template's edit location component?

**Comment by situatedbit** [comment]
@IagoSRL nevermind. I found it.

**Comment by situatedbit** [comment]
PR #445
