### ISSUE TITLE
Update service location form copy

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#406]
To keep language consistent with #408, update the copy on the service location form. 

This screenshot shows the current form, one for a new location, and one for editing a location:
![service-location](https://cloud.githubusercontent.com/assets/6644016/25685919/73528aae-301f-11e7-8739-d4fba2a5f6c1.png)

**Comment by IagoSRL** [comment]
1

**Comment by joshdanielson** [comment]
1

**Comment by situatedbit** [comment]
1

**Comment by situatedbit** [comment]
is409-location-forms-copy

**Comment by situatedbit** [comment]
See comment in #409

**Comment by joshdanielson** [comment]
Tested on branch and looks great. I like the language a lot @situatedbit!
