### ISSUE TITLE
Add clarifying language and layout to service locations screen

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#408]
I'm recommending some changes to the services locations screen based on current challenges:
- it's difficult to know the distinction between a service area and a service location
- it's not clear that only _one_ is required to move forward (not one of each)

Here's a screenshot of the current form during onboarding, the copy I'm suggesting prior to the user adding any locations, and then after they've added an area or a location:

![locations](https://cloud.githubusercontent.com/assets/6644016/25685865/1c20e6d6-301f-11e7-93f4-62b018aab6eb.png)

**Comment by situatedbit** [comment]
2

**Comment by joshdanielson** [comment]
2

**Comment by IagoSRL** [comment]
1

**Comment by situatedbit** [comment]
I thought I would be able to finish this within a day, but it is more complex that I initially thought. The serviceAddress activity is used under several conditions, and it'll take me longer to finish. 

I'm not going to start it today. Moving it back to Top Priorities.

**Comment by situatedbit** [comment]
See comment in #409

**Comment by joshdanielson** [comment]
@IagoSRL @situatedbit added a couple small changes, and it's ready to go.
