### ISSUE TITLE
Improve service locations during onboarding

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#409]
Each listing requires a service area or location. There are a few points of friction in adding these. The issue in this epic address different points of friction.

**Comment by situatedbit** [comment]
@joshdanielson can you please test issues #406, #407, and #408? The branch is ``is409-location-forms-copy``. I will assign those child stories to you as well for testing.

Please verify the layout and copy on the services addresses page during onboarding, after onboarding, and during creating bookings as a professional and as a client (with instant booking with a service area). 

I created a pull request #451 and assigned to @IagoSRL

**Comment by IagoSRL** [comment]
@joshdanielson Must I merge this even before you test it?

**Comment by joshdanielson** [comment]
@IagoSRL I did test this in the branch. My comments must have been in the issues. It's ready to merge.

**Comment by IagoSRL** [comment]
D'oh! Didn't saw that comments, sorry. Will review and merge.

**Comment by IagoSRL** [comment]
Merged!
