### ISSUE TITLE
Clear service location city when zip code is cleared

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#410]
On the service location form, the city is populated from the user-entered zip code. But, when the zip code is cleared, the city persists. 

![city](https://cloud.githubusercontent.com/assets/6644016/25685731/5032ad70-301e-11e7-8cc2-17cc18c14a8f.png)

Suggestion: clear the city when the zip code is cleared, or modified.

**Comment by situatedbit** [comment]
2

**Comment by IagoSRL** [comment]
1

**Comment by joshdanielson** [comment]
1

**Comment by situatedbit** [comment]
Created PR #445 which covers this issue as well.
