### ISSUE TITLE
Direct manipulation of marketplace listing

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#412]
Currently professionals can view their listing, but in order to change any content, they have to navigate to their listing admin screen, find the relevant button to modify the profile content. 

A faster and simply way to allow them to modify the profile content is by clicking directly on the element they wish to change (or a nearby link or button). 

This is an epic.

Possible stories:
- As a new professional who rushed through the onboarding process, the first thing I want to do when I see my listing for the first time is to edit it. I don't know where to do that, but the first thing I try to do is click on the default avatar on the profile, and I'm able to upload a profile photo.
- As any professional who has made it through the onboarding process, I want to enhance my listing by adding service details. At first it didn't occur to me that I could add these details, but there is a prompt on the profile that I can click on to add (and later, edit) service details for my listing. I click on it and see the services overview form.
- And so on, for each type of data on the marketplace listing

**Comment by situatedbit** [comment]
@joshdanielson Working on user stories and wireframes. Here's the current progress: https://loconomics.mybalsamiq.com/mockups/5939958.png

**Comment by joshdanielson** [comment]
@situatedbit looking great!

**Comment by situatedbit** [comment]
@joshdanielson @ardanak 

I've uploaded my work on the accelerated process for onboarding, including allowing the professional to edit their own profile/listing through buttons on the listing.

Josh and I talked earlier this week. My understanding is that he and Aram were going to develop user stories from these mockups, and then refer back to me with any questions.

There are two layouts in the mockup. The first is an empty listing. This is what a professional would see immediately after they sign up. The second layout includes a piece of content in each of the listing sections to demostrate what happens in each section as the professional adds content to their listing.

There are parts of the current listing layout that I gloss over in the markup. If something is unclear, please ask. For instance, I don't propose any changes for the time being in the area around the profile photo and the book button.

The yellow stickies are additional notes about layout and text.

The blue lines indicate URLs where the buttons lead.

The Profile/Listing actions are terse user actions. (E.g., _edit profile photo_ can be expanded to _While seeing their profile photo in the context of the listing, the professional is able to edit the profile photo by clicking/tapping on it_). These are hints (but not definitions) for user stories.

![direct-edit-profile](https://user-images.githubusercontent.com/6644016/28485915-eb87711a-6e31-11e7-8d08-39397e8c6c36.png)

**Comment by joshdanielson** [comment]
@situatedbit thank you! @ardanak and I will follow up with you next week sometime.

**Comment by joshdanielson** [comment]
This became part of #580. Closing as duplicate.

**Comment by joshdanielson** [comment]
Renamed #580 to this issue and am discarding this one.
