### ISSUE TITLE
Rearrange service location form to look like an address

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#414]
Rearrange the service location form to look more like a location is normally displayed in the US: name followed by street, zip/city.

This item _does not_ include changes to the copy. That's a part of #406 and depends on other issues. This item can be completed independently.

Here's a mockup of the form arrangement for reference:
![service-location](https://cloud.githubusercontent.com/assets/6644016/25685919/73528aae-301f-11e7-8739-d4fba2a5f6c1.png)

**Comment by situatedbit** [comment]
I estimated this, given that our estimation call is scheduled for tomorrow and I want to work on this today.

**Comment by situatedbit** [comment]
Created PR #415

**Comment by joshdanielson** [comment]
@IagoSRL @situatedbit tested and looks good on my end. @IagoSRL close when ready.
