### ISSUE TITLE
Bug: Wrong link for photo-name at mobile menu 

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#416]
Clicking in the phone-name in the top of the mobile menu goes to *profilePictureBio*, that doesn't exists now.

This must be happening since we unified that activity with the *aboutMe*, must point to that one.

**Comment by IagoSRL** [comment]
It's done, merged to *master* and in *dev*

**Comment by joshdanielson** [comment]
@IagoSRL I tested this on dev and all good.

**Comment by IagoSRL** [comment]
thanks!
