### ISSUE TITLE
Navbar link 'List your services' cropped for logged professionals

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#417]
@joshdanielson This are two minor issues:
- the link 'list your services' appear now for logged users that are professionals. They already are listing their services, cannot become professionals *again*. I suppose this must be displayed just to clients.
  - Quick fix: negate the `data-bind="visible: isServiceProfessional()"`
- the link appear cropped (it reads 'List your s...') and it looks different than in the anonymous users navbar
  - Quick fix: change element class "LargeNavBar-label" by "btn btn-secondary"

This is very minor and quick, but I don't know if was changed on purpose, so please confirm it.

**Comment by joshdanielson** [comment]
Please change per your recommendations!

**Comment by IagoSRL** [comment]
Just found in the code that there is another link to 'learnMoreProfessionals' but labelled as 'Join our co-op' just before the one is showing incorrectly:
```
<a data-bind="visible: !isServiceProfessional() && !isAnonymous()" href="/learnMoreProfessionals"><button class="btn btn-secondary">Join our co-op</button></a>
<a data-bind="visible: isServiceProfessional() && !isAnonymous() && !isInOnboarding()" href="/learnMoreProfessionals"><span class="btn btn-secondary">List your services</span></a>
```
