### ISSUE TITLE
Proposal: remove generated files from web directory

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#418]
At the web directory we have several files that are part of the webapp and landing pages, and need to be uploaded to the site's FTP. They are auto generated from the App directory using Grunt tasks.

They are:
- /web/_specialRoutes/app.html: Is the webapp html (processed and minified), generated with `grunt build-webapp-html` (included as part of `grunt build-webapp`).
- /web/assets: all the subdirectories (css, fonts, images, js) are copied from the App dir by the task `grunt build-webapp` task.
- /web/welcome: this contains one processed and minified html file per landing page.

I am not sure the best practice here, if this files must or must not be included in git, but are generating *noise* with commits like 'webapp rebuild', 'landing pages build'; and every time I prepare files to upload to *dev* for testing, I need to commit or discard them before I switch back to another branch (a bit annoying).

Since they are auto-generated, same like the app build files, I think we can *gitignore* them.

**Comment by situatedbit** [comment]
I think we should ignore them, too.

**Comment by IagoSRL** [comment]
@joshdanielson I finally did this (is at branch #460 still), that means removal of all the related files. While should not be a problem, I noticed that the folder /web/assets/images had more files than /app/source/images (is expected to share the same content, with a Grunt task that copy all content from the images folder under app into web); could have happened too that the task didn't removed files already copied but removed in origin (actually, the task has that limitation), but I left this comment just in case some image was place manually under the web directory by mistake (previous commits can be checked to see all files and copy anyone that should be preserved into /app/source/images).

**Comment by joshdanielson** [comment]
Ok, thanks!

**Comment by samwa** [comment]
Hi @IagoSRL 
I got this change today when I merge masters
The grunt task that copies from app/ to web/ (grunt build-webapp) fails due to warnings in parallel:build-webapp (log file is attached below)
I ended up copying the contents of build/ over to web/ manually
I think you forgot to change web/Default.cshtml to use /_specialRoutes/index.html instead of /_specialRoutes/app.html

Cheers
Sam

[log.txt](https://github.com/loconomics/loconomics/files/1588420/log.txt)

**Comment by samwa** [comment]
Should we also add app/package-lock.json to the git ignore? this file is auto generated each time you run npm install

**Comment by IagoSRL** [comment]
Hi @samwa, something weird.

From you log file, the error comes from uglify, it seems detects wrong code (or think it is wrong). There are a bunch of other warnings from coding style but they don't stop processing (the *one-var* ones from eslint; I will fix them in next days/weeks and make it blocking after that).

I tried cloning your fork, doing a `build-webapp` at master and at the *is9* branch; on both cases, worked fine, so is strange :-/ (on a Windows 10 machine, Node v8.9.3, npm 5.6.0, the version of grunt-contrib-uglify is 3.3.0, from the '#harmony' branch that uses uglify-es).
Maybe is not getting the correct version of uglify?? Is not expected to happens this (I understand that package-lock.json is there to prevent that) but still I recommend you try to remove de node_modules folder and `npm install` from scrach, try again and let me know.

--------------

About the name of the generated file, is the correct one when using `grunt webapp`, is just different than the one generated with `build`.

--------------

About git-ignoring the `package-lock.json`, [the 'theory' recommends to keep it at git](https://docs.npmjs.com/files/package-lock.json), but I'm founding it annoying too how many times updates on any `npm install`, when supposely should only on new added packages or `npm update` (from my understanding). [There are some discussions though](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5), I will keep it for now, trying the recommendation of commit just that and package.json when changed, separately from other changes (but don't discard to ignoring it in the future if keeps so annoying and no benefits, we will see).

**Comment by IagoSRL** [comment]
@samwa About the problem related with *uglify* (js minification), lastest PR #750 by @ndarilek can help here; it's merged

**Comment by samwa** [comment]
@IagoSRL I removed the node module folder, merged your master to mine and grunt build-webapp works now
Thanks for the update

Agree that package-lock.json is annoying, I guess i can ignore it for now as i'm not touching the app code

**Comment by IagoSRL** [comment]
Hi @samwa,

@ndarilek did the work to switch to `yarn` from `npm` as package manager at #757; that means the package-lock.json file was removed and replaced by yarn.lock that **should** not be so annoying (maybe first time still changes the file, please commit it but let me know if keeps repeating) and fixing other problems. Docs were updated about using Yarn, but is pretty similar to npm.

Closing (let me know if new problems arise)
