### ISSUE TITLE
Prevent pre-processing of the activities html

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#423]
We are including all the activities html files in the html bundle just like normal elements, causing the browser to process them at start-up even if only one is needed at that moment (the one that matches the current route).
All 'data-activity' elements begin hidden by CSS, what prevents some layout calculations, but I think all styles are still computed or almost assigned.
The databinding with Knockout is not connected until first use, same as the activity specific js, so not a problem.

This is a problem because of:
- Bad start-up performance.
- Higher memory consumption, even for elements that the user may never use in a session.
- Not wanted, not needed, resources load, like images, iframes (Youtube and Google Maps are being loaded all the time). Around 73-76 requests on load, 7.2MB transferred (!!!).

This was originally commented at #203 (from old #921 at Fri Mar 04 2016), with some proposals.

### Proposal A
To wrap every included activity html in a template tag, like we do with components; that way the browser don't process it. This requires to update the Shell component that displays the activity html: it must locate the template and instantiate it; in case is already instantiated it, just make it visible like happens now.

Going a bit further, activities can become a component loaded dynamically.

#### Downsides
This doesn't reduces the size of the unique html bundle we have now (even may grow a little), that needs to be achieved by splitting current unique bundle in several ones. The initial idea for bundles was to group several related activities in a bundle, reducing the number of requests and feeling fast the switch to related activities.

Any template included in the activities html needs to be moved out or will stop working. This may be a better practice anyway.

#### Additionally
We can make a quick research if the current 'activity instance reuse' behavior must be keep or not. The change would be to drop the activity instance (html+javascript) when no used (navigation goes away the activity scope). If this is found as better, could even simplify each activity/viewmodel logic by removing 'resetting'.
The fears of this were: switch to a previously used instance not so fast (because needs to generate the html from template each time), and browser not disposing memory correctly from previous activity instances, so it keeps growing.

### Proposal B
Implement bundles by creating one for each activity (html+js+css). The bundles are needed anyway, and could be another issue.

If we choose to implement this option for bundles (rather than include several activities per bundle as commented previously), this would not require the additional work to move the html to templates because we load just one activity html at a time, that is immediately used so can be attached to the document directly as an element and not a template that is instantiated soon after. For this to work, the bundle for the native App must be full split too or will reproduce this problem still.

We can think in the possibility to replace Browserify with Webpack to help with bundling (it affects to #360).

#### Downsides
Doesn't allow us to drop the activity instance and create a new one from the original template. Well, we can store the template in javascript memory instead of DOM, so it just changes how is implemented.

### Notes
Bundles require to implement a loader for the shell (the API is there for that, it has a 'loader' entry point, just is not implemented currently).

First proposal was commented at #203 too.

**Comment by situatedbit** [comment]
Yes!

I am assuming that Proposal B is more complex than Proposal A in its initial implementation. Perhaps eventually we want to move to Proposal B, but it seems we can get solid benefits relatively soon from Prop A.

I _strongly_ want us to do _Proposal A: Additionally_. The static activities and view models greatly increase the complexity of the codebase. We should determine how to avoid resource leaking when we deactivate activities, and then make this happen. The more we can cut down on long-living objects the better off we will be.

**Comment by situatedbit** [comment]
I suggest separating _Proposal A: Additionally_ into a separate issue.

**Comment by situatedbit** [comment]
I'm going to create a 4-hour investigation issue to explore:
1. creating a template for each activity's html
2. releasing activity resources when navigation moves away from the activity
3. I will evaluate implications in code complexity
4. I will try to ascertain whether there are significant performance implications after this change.

**Comment by situatedbit** [comment]
Investigation issue: #457

**Comment by situatedbit** [comment]
I'm going to close this one and keep it as notes. When #457 is finished, I'll create new issues to complete the work.
