### ISSUE TITLE
Update database to make services overview optional for an active profile

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#425]
Note: update alerts table (possibly Alert ID 8)

**Comment by situatedbit** [comment]
2

**Comment by IagoSRL** [comment]
1

**Comment by joshdanielson** [comment]
2

**Comment by situatedbit** [comment]
@IagoSRL I don't think there is anything in the alerts system that requires the service attributes. 

While I still don't fully understand how the alert system works, I couldn't find anything pertaining to the attributes. On my local database I'm able to activate profiles without adding service attributes.

I'm going to move this to review/QA so you can determine whether the database needs to be changed.

**Comment by IagoSRL** [comment]
I will test. Just thinking out loud, maybe what happens is that, because all attributes are optional, the alert for this is 'passed' so gets disabled and no need to set it as optional.

-------------

On database, the trick for this are the stored procedures with a name like `TestAlertPositionServices` (the one for alertID:8). It must be executed on server after any database change that implies the 'user' tables included in the check (`userprofileserviceattributes` on this). All this procs calls to `SetUserAlert` proc, to enable or disable the alert, and finally `TestProfileActivation` that checks if there are required alerts still enable for the user, updating the user-jobtitle to be enabled or disabled accordingly.

**Comment by situatedbit** [comment]
Ok, I see. Since we are keeping the ``Required`` column for service attribute categories, should we also keep this stored procedure, even though it's not being used?

Also, it's not in the codebase, so if we were to get rid of it we should add it to the codebase, then remove it in separate commits.

```SQL
USE [Dev]
GO

/****** Object:  StoredProcedure [dbo].[TestAlertPositionServices]    Script Date: 5/8/2017 5:49:09 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		Iago Lorenzo Salgueiro
-- Create date: 2012-06-01
-- Description:	Test if the conditions for the
-- alert type 'positionservices' are satisfied, 
-- updating user points and enabling or 
-- disabling it profile.
-- =============================================
CREATE PROCEDURE [dbo].[TestAlertPositionServices]
	@UserID int,
	@PositionID int
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @AlertID int
	SET @AlertID = 8
	
	DECLARE @CATS TABLE (CatID int)
	
	INSERT INTO @CATS (CatID)
	SELECT DISTINCT A.ServiceAttributeCategoryID
	FROM ServiceAttributeCategory As A
		  INNER JOIN
		 ServiceCategoryPositionAttribute As B
		   ON A.ServiceAttributeCategoryID = B.ServiceAttributeCategoryID
			AND B.PositionID = @PositionID
	WHERE A.RequiredInput = 1
		AND A.Active = 1
		AND B.Active = 1
    
    -- First ever check if this type of alert affects this type of user
    IF dbo.fxCheckAlertAffectsUser(@UserID, @AlertID) = 0 OR
		-- Check that user has that position (this is a position related alert). If it has not (=0), alert will off because doesn't affect:
		(SELECT count(*) FROM userprofilepositions WHERE UserID=@UserID AND PositionID=@PositionID) = 0 OR
		-- Check all required data
		-- Must have almost one service attribute selected 
		-- per required category for the position
		@PositionID = 0
		OR (SELECT count(*) FROM (SELECT A.ServiceAttributeCategoryID
		FROM userprofileserviceattributes As A
		 INNER JOIN
		ServiceCategoryPositionAttribute As B
		  ON A.ServiceAttributeCategoryID = B.ServiceAttributeCategoryID
		   AND A.ServiceAttributeID = B.ServiceAttributeID
		  -- We only check the 'RequiredInput' Categories
		   AND B.ServiceAttributeCategoryID IN (SELECT CatID FROM @CATS)
		WHERE A.UserID = @UserID AND A.PositionID = @PositionID
			AND A.Active = 1 AND B.Active = 1
		GROUP BY A.ServiceAttributeCategoryID
	) As Z) = (SELECT count(*) FROM @CATS)
	BEGIN
		--PRINT 'you''re cool!'
		-- PASSED: disable alert
		EXEC dbo.SetUserAlert @UserID, @PositionID, @AlertID, 0
	END ELSE BEGIN
		--PRINT 'buuuhhhh!'
		-- NOT PASSED: active alert
		EXEC dbo.SetUserAlert @UserID, @PositionID, @AlertID, 1
	END
	
	-- Test if user profile must be actived or not
	EXEC dbo.TestProfileActivation @UserID, @PositionID
END
GO
```

**Comment by situatedbit** [comment]
> I will test. Just thinking out loud, maybe what happens is that, because all attributes are optional, the alert for this is 'passed' so gets disabled and no need to set it as optional.

You're correct.

**Comment by IagoSRL** [comment]
I'm OK to keep the proc still same as Required column.

With this clarified, the alert, technically, don't need to be updated.

**Comment by IagoSRL** [comment]
Finally, alert untouched, is not needed because all attributes plus intro are optional, nothing committed for this.
