### ISSUE TITLE
Edit link from profile

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#436]
Primary Persona: [Charlie, babysitter looking for business](https://github.com/loconomics/loconomics/blob/master/docs/Personas/Charlie.md)

## Story
As a new pro on Loconomics, having just onboarded, I'm interested in seeing what my new profile looks like. Because I'm looking to grow my business and establish trust early with potential clients, it's important to me that I add critical details to my profile. **When I view the profile, I want to quickly navigate back to the listing admin page** to add details, add offerings, and so on.

When a professional is looking at their own profile, then they should see a link back to their listing admin page.

### Additional Value

After users onboard, we can send them to their profile and they'll still be able to get back to the listing admin page.

Eventually this will allow us to add placeholders for missing items in the profile, eventually allowing us to add direct manipulation to the profile.

It precedes removing other onboarding steps. We don't want users to get stuck on the listing without knowing how to add missing items.

![edit-listing](https://cloud.githubusercontent.com/assets/6644016/26646273/d4a2b42e-45ef-11e7-92c7-3576b0e8e9de.jpg)

**Comment by situatedbit** [comment]
@joshdanielson  This was implemented in #437, though in a different form. I think it can be closed.

**Comment by joshdanielson** [comment]
@situatedbit agreed. Closing as duplicate.
