### ISSUE TITLE
Skip payment info during onboarding

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#437]
Primary Persona: [Devin, aspirational dog walker](https://github.com/loconomics/loconomics/blob/master/docs/Personas/Devin.md)

## Story

As a new professional, I responded to the outreach email and signup through the landing page. Because I'm not at home (a coffee shop?), I don't have my payment information with me. I'm anxious to see my listing and start adding to it. During onboarding I want the _option_ to skip setting up my payment information. 

From #433, I should see in the listing admin page that I still need to add my payment information before being able to make my listing public.

## Additional Value

This can speed up the onboarding process while still helping us capture payment information early when possible.

## Dependencies

This item depends on #433

**Comment by situatedbit** [comment]
I also want to hide the terms of service by default during onboarding. Pros can show the terms of service by clicking on the toggle link. 

Here's my suggested layout for the skip button as well as the terms toggle link:

![onboarding-skip-payment](https://cloud.githubusercontent.com/assets/6644016/25877496/9ec1176a-34d8-11e7-9119-80cf85e97426.png)

**Comment by joshdanielson** [comment]
I think this should labeled Braintree's Terms of Service as it's unclear and they could think it's referring to ours, which they already agreed to.

**Comment by situatedbit** [comment]
We shouldn't do this until we have #433 done. Otherwise it'll be one more thing the client needs to do to finish their listing, but we have no place where we actually tell users what still needs to be done prior to making their listings visible. That's what #433 does.

**Comment by joshdanielson** [comment]
- Not require payment info for listing to be active
- Require payment info only before:
  - accepting a booking request
  - turning on instant booking
- Email communications must notify service professional that they will have to enter their payment info before accepting
- limit ability to accept until payment info is entered
- some sort of mini-onboarding..."before you accept this booking request..."

**Comment by situatedbit** [comment]
Notes from during discussion:
- pro should know that the profile isn't public
- only complete profiles show up as tabs/links in profile (even for own professional)

**Comment by situatedbit** [comment]
3

**Comment by IagoSRL** [comment]
3

**Comment by situatedbit** [comment]
Blocked on #433

**Comment by situatedbit** [comment]
This item is ready to go, but shouldn't be released yet. It's blocked on a couple items:
1. Now that payment can be skipped during onboarding, pros need to be able to preview their listing prior to it being public. Currently they cannot see their listing until it is complete and public. I'll create an item to address this.
2. There's a bug generating a blank profile if there is missing payment info: #398

I'm going to promote both of these items and start working on them.

**Comment by situatedbit** [comment]
@IagoSRL Thanks. I'm making progress now. Had some other distractions. I can skip payment, but I'm adding a notice to service professionals when the profile or listing they are viewing is inactive.

**Comment by situatedbit** [comment]
@IagoSRL please assign to @joshdanielson when you've moved the code on to dev so you can test it.

**Comment by joshdanielson** [comment]
@situatedbit @IagoSRL tested and looks great!

**Comment by IagoSRL** [comment]
Merged #491 and closing.
