### ISSUE TITLE
Bug S2: Postal code not included in user fees payment form

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#438]
![screen shot 2017-05-10 at 10 53 57 am](https://cloud.githubusercontent.com/assets/1202838/25913343/42ab6722-356f-11e7-9d25-0e0cb1048720.png)

**Comment by IagoSRL** [comment]
Pushed fix, I tried in *dev* and now is in *live*, Please @joshdanielson test to

**Comment by joshdanielson** [comment]
@IagoSRL working! Trial period and plan verified on Braintree (I'm going to cancel it now since it was under at test user):
![screen shot 2017-05-10 at 11 59 52 am](https://cloud.githubusercontent.com/assets/1202838/25916056/375909c0-3578-11e7-856d-35036f019fbd.png)
![screen shot 2017-05-10 at 12 02 09 pm](https://cloud.githubusercontent.com/assets/1202838/25916169/90e54012-3578-11e7-88ba-c2250b1d6eca.png)
![screen shot 2017-05-10 at 12 01 37 pm](https://cloud.githubusercontent.com/assets/1202838/25916168/90e3ae32-3578-11e7-9484-52f4e325e784.png)

**Comment by IagoSRL** [comment]
Perfect!

I fixed another detail I had. The 'next payment' was not displaying correctly at /account, I uploaded a fix and seems fixed

**Comment by IagoSRL** [comment]
Thank. I closed this
