### ISSUE TITLE
Revise LearnMore page with new value props and plans

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#444]

**Comment by joshdanielson** [comment]
@IagoSRL assigned this to you. Review my last commit. I can't get the upgrade now buttons to be hidden if !isServiceProfessional().

**Comment by joshdanielson** [comment]
This commit: https://github.com/loconomics/loconomics/commit/0d55cb4e25a6f3536a071475d0f138ac28eba06e

**Comment by IagoSRL** [comment]
@joshdanielson Pushed changes. Please test and if ready, send me a PR

**Comment by joshdanielson** [comment]
@IagoSRL done!
