### ISSUE TITLE
Export Stored Procedures to Codebase

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#455]
@IagoSRL Using the _Generate Scripts_ feature on the dev database I exported all of the stored procedures to sql files. They're a lot easier to search that in the database itself. 

If we add them to the repo, then we can track changes on them more consistently, too.

I would add them myself, but I was wondering which database you wanted to export _from_, and which options you wanted to include:
- DROP and CREATE?
- USE DATABASE statement?
- fully qualified object names?
- etc.

Also, after I exported my copies I converted them from UCS-2-LE to UTF-8. ``grep`` wasn't working with UCS-2-LE.

**Comment by IagoSRL** [comment]
We have a few procs already under /web/_DBUpdate/stored-procedures/, following different rules but I think must be:
- DROP and CREATE?  No
- USE DATABASE statement?  No  *(prevents error applying the script in a context with different db name -as happens between dev, live, and localhost environments)*
- fully qualified object names?  Yes
Other options don't affect procs I think.
One file per proc.

The problem still is that there is not a 'create or replace' syntax in TSQL, so all Create statement will fail if the object exists previously (when applying it), and any previous DROP statement will fail if object don't exists (and even remove any permissions applied on existent object).
Note: when the proc is copied as an 'upgrade script' must change the 'CREATE' by 'ALTER' if already exists on target.

I think we must put them in a new root folder, as /database/stored-procedures/

**Comment by situatedbit** [comment]
Shall I export from the dev database?

**Comment by IagoSRL** [comment]
Yes, it has the most recent changes.
And we must include UDFs too, under a /database/functions folder.

As a new rule, new changes/additions to this objects in issues, must update the files too, additionally to create the UpgradeScript for it (note to myself to review this on PRs).

**Comment by situatedbit** [comment]
Steps:
1. From Dev database, generate CREATE scripts for stored procedures and user-defined functions. One file per object.
2. Options: USE DATABASE statement (no), fully qualified names (yes)
2. Add them to the repo under ``database/stored-procedures`` and ``database/functions``, respectively
3. Convert the text encoding to UTF-8 for each file
4. Add a note to our dev documentation for how to update these objects in the database during releases and pull requests

**Comment by situatedbit** [comment]
For future reference, after exporting the files via MSSQL Studio, I ran this to convert them to UTF-8 and remove the filename prefix ``dbo.``:

```bash
#!/bin/bash

FILES=*.sql
for f in $FILES
do
  iconv -f UCS-2LE -t UTF-8  $f > ${f//*dbo./}
  rm $f
done
```

**Comment by situatedbit** [comment]
@IagoSRL created a pull request for this and assigned to you.

**Comment by IagoSRL** [comment]
PR Merged. Thanks for posting too details like the bash script.
