### ISSUE TITLE
Revise /upgrade to become reusable

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#461]
- will be used in the learnMore page #444
- includes minor css changes

**Comment by IagoSRL** [comment]
@joshdanielson per our comments at PR #463, I updated the description html for the plans at AppModel.paymentPlans.js. I did it by embedding the html inside js, referecing the files at /html/parts.
Please just check that it looks as expected and take care of this shared use if you need to modify some content or rename files.

**Comment by IagoSRL** [comment]
Done another change about this (appModel.paymentPlans and activities/userFees): added the free plan to the list and details, with an empty ID and choosen by default, with payment form hidden until user picks another plan.

**Comment by joshdanielson** [comment]
@IagoSRL having I just changed the headline, but all else looks great!

**Comment by IagoSRL** [comment]
@joshdanielson It's OK, I merged and closed branch, goes into Release 1.5
