### ISSUE TITLE
Offering name field is larger than validated length

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#467]
The offering _name_ field allows for more than 50 characters, but when the form is submitted and validated through the API, it is limited to 50 characters.

To fix:

- on the input field, limit to 50 characters
- under the input field: indicate that the limit is 50 characters
- update how many characters are used as the user types

**Comment by situatedbit** [comment]
Here's how you get to the form in question: On service professional dashboard: Your Listings, then click on a Job Title (e.g., Dog Walker), then on Offerings. Create a new offering (consultation, service, etc.). The name field is on the new offering form.

**Comment by IagoSRL** [comment]
Closing after merge #494.

@ardanak I opened #498 for the audit you proposed.
