### ISSUE TITLE
Sign up with email button on learn more page impossible to see

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#468]
On the learn more page, the sign up by email button has a transparent background. This makes it really difficult to see. 

To fix:
- Give the sign up and login buttons a solid color background.

![sign-up-button](https://cloud.githubusercontent.com/assets/6644016/26744051/22b2baa6-4799-11e7-95bf-bdf0970f0882.jpg)

**Comment by joshdanielson** [comment]
@situatedbit I resolved this in #444 since it was quick. Please re-open if you still have issues with it:
![screen shot 2017-06-05 at 10 47 24 am](https://cloud.githubusercontent.com/assets/1202838/26795952/696c0296-49dc-11e7-9fb0-3fba0ea26811.png)
