### ISSUE TITLE
Next Steps screen has too many options

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#469]
With some distance from the copy, the next steps (post onboarding) screen appears to present too many choices, some of which aren't likely appropriate for a new user. We should consider a _single_ next step. The primary task up to this point is to complete an initial listing. It seems strange to interrupt this process to ask users if they want to do _something else_. 

Preview your listing: Upload credentials shouldn't be visible if the pro has already (just recently) uploaded their credentials. It also shouldn't be there for job titles that don't require them.

RSVP for an upcoming event is probably best placed within a follow-up email. This way it doesn't interrupt with the task flow of creating a listing.

I understand why we include Explore owner plans, but it seems too soon to entice pros with running for the board of directors, or even earning patronage. _Patronage_ is not a word most people know. We want them to be involved in a co-op, but jumping to board of directors is too much. If we keep _Explore owner plans_, I think we should lead with more tangible benefits like being able to book clients through the marketplace. _Grow your business_ is a bit abstract.

I'm happy to talk more about these.

![next-steps](https://cloud.githubusercontent.com/assets/6644016/26745687/85bfe734-47a0-11e7-962b-a4e9ed1798eb.png)

**Comment by situatedbit** [comment]
Based on feedback from Christopher, we're going to remove all options but preview listing. We'll add a story for asking professionals to spread the word _after_ they've completed an initial listing.

**Comment by situatedbit** [comment]
@joshdanielson what do you think of the copy changes?

![success](https://user-images.githubusercontent.com/6644016/26852975-fdcf936a-4ac4-11e7-804b-d88196d07883.png)

**Comment by IagoSRL** [comment]
PR merged, closing
