### ISSUE TITLE
Release Release 1.5

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#470]
There are 11 closed issues assigned to the milestone already. https://github.com/loconomics/loconomics/milestone/7?closed=1

This is about publish to website and native apps: Android, iOS too.

Goal: release by 06/06/2017

Pending to know if issues #444 and #461 can be closed in time for the release.

**Comment by IagoSRL** [comment]
Moved release date to 06/07/2017.

Issues #444 is closed and #461 seems ready.

**Comment by IagoSRL** [comment]
Is released at *live*; I updated *dev* too.

@joshdanielson Next are the release notes for this (including changes in previous version not released to stores), let me know any other language for the App Stores release notes:
> Simplification and enhancement of the onboarding process.
Allows professionals to become members of the cooperative.

**Comment by IagoSRL** [comment]
Correction: because latest App version at stores was 1.2.2, the release 1.3 notes apply too here:
- New feature: client specific pricing
- Enhancements to the onboarding process
- Reorganization of menus and content ("revised app architecture")
- Updated sign-up form
- Reduced password requirements
- Detailed/positive password validation
- New: landing pages
- Some refactors and bug-fixes.

**Comment by joshdanielson** [comment]
@IagoSRL all looks good, but I made small edits. Here's a final version:
- Simplification and enhancement of the onboarding process.
- Cooperative owner plans added
- New feature: client-specific pricing
- Reorganization of menus and content 
- Updated sign-up form
- Reduced password requirements
- Detailed password help
- Some refactors and bug-fixes.

**Comment by IagoSRL** [comment]
OK. Can you @joshdanielson review the new iTunes agreement? (cannot upload new version)

**Comment by IagoSRL** [comment]
Apps sent to review to Google Play and App Store

**Comment by IagoSRL** [comment]
Android app got published, iOS one expecting review. I will close this issue and milestone anyway

**Comment by IagoSRL** [comment]
Got notification from Apple that version 1.5 is already published (the process was faster than never in my experience)
