### ISSUE TITLE
Back/Cancel link from offerings editor during onboarding

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#477]
On a wide layout, there is no back/cancel link to the offerings listing from the offerings editor screen.

This only happens during onboarding.

![onboarding-offering-editor](https://user-images.githubusercontent.com/6644016/26986953-752cf070-4cfe-11e7-8782-f82b5ac6140c.jpg)

**Comment by joshdanielson** [comment]
Closing as will be fixed with #592.
