### ISSUE TITLE
Credentials upload screen needs to better explain screenshots

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#478]
In my experience, professionals don't think to take a screenshot of the website of their licensing board. We mention that they could take a screenshot to upload, but we need to be more explicit about this suggestion. 

_If your licensing board has a website where you can verify your license, go to it and take a screenshot._ (or something similar)

Furthermore, most users don't know _how_ to take a screenshot. We should link to directions for how to do this.

![credentials-form](https://user-images.githubusercontent.com/6644016/26987145-42f6afc8-4cff-11e7-9a0e-de45f6b05355.jpg)

**Comment by IagoSRL** [comment]
Closing as of merge #579
