### ISSUE TITLE
Create Personalized Landing Pages for Board Members

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#479]
As a board member, I'd like to invite my network to create a listing on loconomics and send them to a landing page specific to my network.

- [x] make sure pages have board member's testimonial showing first
- [x] make sure job titles board member will be recruiting are shown

**Comment by joshdanielson** [comment]
@IagoSRL please do a landingPages build and let me know when complete.

**Comment by IagoSRL** [comment]
Published!
