### ISSUE TITLE
Clarify language on About Me address form

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#481]
The address form on the About Me profile screen could use a couple clarifying points:
1. That the address we're looking for is the mailing address
2. A _City_ label in the blank space where the city name is auto-populated, just like we are now doing it on the service location form.

## Current Form

![your-address](https://user-images.githubusercontent.com/6644016/26987441-6d000692-4d00-11e7-824b-d26732492809.jpg)

## Service Location Form

![work-address](https://user-images.githubusercontent.com/6644016/26987449-718d7f28-4d00-11e7-8b5a-099854a1d5f4.jpg)

**Comment by IagoSRL** [comment]
Closed as per PR #560 by @ardanak
