### ISSUE TITLE
Audit all the input fields for a 'character limit constraint'

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#498]
Based on the issue #467 by @situatedbit and [comment at the pull request](https://github.com/loconomics/loconomics/pull/494#issuecomment-311262156) by @ardanak.

All the text input fields needs to limit the maximum number of characters.
The server has size constraints at the database columns already, and some REST API endpoints has too validations rules for length (that allows to send back a better error message). The ideal is to have a validation rule in all of them.

The goal of this issue is to audit and propose changes where needed (client and server).
Additionally, the UI may include the message about 'characters remaining'; this was added as a feature to the `app-unlabeled-input` at #494. Audit what fields may need this.

**Comment by joshdanielson** [comment]
maxlength was added to input fields as part of #528. Moving charRemaining to new issue. Closing.
