### ISSUE TITLE
Bug S1: Error when paying for owner plan

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#513]
After I entered my credit card details, I got the following error message:
![screen shot 2017-07-05 at 5 55 17 pm](https://user-images.githubusercontent.com/1202838/27891031-da4aa184-61ab-11e7-95d9-5b5a7964fe0c.png)

When I navigated back to /account, it appears it went through, although there is no record of it in the braintree control panel:
![screen shot 2017-07-05 at 5 59 42 pm](https://user-images.githubusercontent.com/1202838/27891040-e8afdc44-61ab-11e7-804a-30118876d1a9.png)

**Comment by IagoSRL** [comment]
@joshdanielson Found that specific error (SQL syntax error at 'meetsOwnershipRequirement'. Tested the fixed SQL directly and works, I uploaded change to *live* and *dev*, but not tested the full process.

Please, close if you confirm the fix

**Comment by joshdanielson** [comment]
@IagoSRL this is still happening.

**Comment by IagoSRL** [comment]
(I closed by mistake).

Checked the logs for the error, I see it with a slight difference for sql syntax error. Curiously, when running the SQL directly against Live DB it works

**Comment by IagoSRL** [comment]
New fix uploaded. I tested this time the `CheckAndSaveOwnerStatus` method directly and worked; additionally, added extra error control to that so an error running the status check doesn't crashes the payment-plan creation (to prevent your situation with a DB record created but Braintree subscription not created).
It's at *live* and *dev*

**Comment by joshdanielson** [comment]
@IagoSRL it works! I cancelled it in Braintree, though, and will delete my latest user. There were plans created with my two other users, 295, 292, that both appear in the database as having subscription plans but never made it to braintree because of the bug. 

I want to create my own subscription through the iOS app once it's released to double-check that we don't pay Apple 30%. Then I can check the payment, history, trial period, etc. Sound good?

**Comment by IagoSRL** [comment]
OK, closing. About Apple, I think is not a problem since we don't run payments against app store, but try anyway.

**Comment by joshdanielson** [comment]
@iagosrl yes, just worried they may try and block it. Fingers crossed.
