### ISSUE TITLE
Bug S3: 'navBar not defined' error in profile

### ISSUE THREAD

**Issue by ardanak** [loconomics/loconomics#544]
**Steps to reproduce bug**:
**1**. Navigate to profile. 
**2**. Click on 'About Me' or 'Training and education

@IagoSRL @joshdanielson @situatedbit  can someone duplicate this and confirm bug?

****
![error](https://user-images.githubusercontent.com/1480837/28143863-caab5194-671c-11e7-8152-e1e96d7b0cc4.png)

**Comment by joshdanielson** [comment]
@ardanak I just tried to reproduce on both live and dev and could not - no error messages.

**Comment by ardanak** [comment]
@joshdanielson thanks for checking

I resolved the issue by deleting node_modules and rebuilding it with npm install. 
That seemed to fix the problem.
