### ISSUE TITLE
Meet 3.3.4 - Error Prevention (Legal, Financial, Data)

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#554]
## Summary
Provides that when legal, financial, or test data can be changed or deleted the changes or deletions can be reversed, verified, or confirmed
**Conformance Level:** AA
**Existing 508 Corresponding Provision:** None

**Comment by joshdanielson** [comment]
@IagoSRL adding this task:
- [ ] adding a second account number field to validate against the first to prevent a user from entering the wrong account number as it's not validated by braintree (only the routing number is).

**Comment by IagoSRL** [comment]
Done (client side validation only)

**Comment by IagoSRL** [comment]
Please @joshdanielson , review the language

**Comment by joshdanielson** [comment]
Tested. Updated language with #666. Closing.
