### ISSUE TITLE
Remove Bank Account Requirement for Booking Request Listings

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#564]
As a service professional, I want my listing active so I can get booking requests without entering my bank account info until I have clients paying me.
- update alerts
- check any client booking code that may check if the user has set their payment account (data for new booking)
- enable listing if they have booking request
- they can create a service professional booking since there are no payments

**Comment by IagoSRL** [comment]
Updated server code to allow booking even without paymentAccount when is a 'booking request'.
Updated the upgrade script at #571 to change paymentAccount alert from required to optional, run users tests again so the listing of ones with 'booking request' gets enabled even without paymentAccount ready.

Is still at branch is563 not at *dev*.

**Comment by IagoSRL** [comment]
Had to make a latest change to this: the alert for paymentAccount will keep as required BUT the stored proc to test the alert checks for InstantBooking enabled on user to force or not the alert per requirements here. So this issue is done.
