### ISSUE TITLE
Require Bank Account Info if Client booking has a payment

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#565]
As Loconomics, we need to capture the service professional's bank account for a client booking that has a payment **greater than $0 to professional**. 
- professional is not allowed to confirm a booking request if no bank account present
- create a special component that is added to the appointment activity to communicate and capture bank account info
### flow:
  - email links, if bank account not present, user is taken to a mini-onboarding to include:
    - new activity explaining why we need their bank account with button "Enter Payment Preferences"
    - /paymentAccount with button "Save and continue to booking"
    - /appointment with booking request to choose time and confirm

**Comment by IagoSRL** [comment]
Done, in branch is563
