### ISSUE TITLE
Require Payment Option when enabling Instant booking

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#566]
As Loconomics, we need the service professional's payment option/bank account if they enable instant booking to ensure we have a place to transfer payment.

### Flow
- Service professional tries to enable instant booking
- User taken to /paymentPreferences and we communicate the options, now only /paymentAccount
- Instant booking enabled and alert shown that it's enabled and ready for clients to book

**Comment by IagoSRL** [comment]
Done, in branch is563
