### ISSUE TITLE
Create /paymentPreference activity

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#567]
As a Service Professional, I want to choose how I get paid by Loconomics clients. 
### Desired options
- Direct deposit (current sub-merchant)
- Venmo
- In-person after service (future issue)
   - credit card
   - cash
   - check

### Flow
- Only shown:
  - when service professional has a booking request with payment
  - when service professional tries to enable instant booking
  - as option in /account

### Needed
- Messaging explaining how payments work and the options
- Message of why this is required (one from instant booking and other from booking request)
- New activity for /paymentVenmo
- Rename /paymentAccount to /paymentDirectDeposit
- Remove onboardingTip  - move to /paymentPreference
- Explain how to upgrade to accept in-person (future issue)

**Comment by IagoSRL** [comment]
Renamed paymentPreference as payoutPreference (and all the components are organized under a payout folder)

**Comment by IagoSRL** [comment]
This is done. The old paymentAccount activity still exists because is linked from onboarding, while not in any menu, to be removed as of #571 and related ones.
@joshdanielson If you can take a look to this just in case a bug or something wrong, or just closing it
