### ISSUE TITLE
Remove /paymentAccount from onboarding

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#571]
### Tasks
- remove step from onboarding
- migrate existing onboarding users beyond payment account step (active) and give list of newly active to Josh

**Comment by IagoSRL** [comment]
This is implemented at branch is563, and the file to manually execute after update server to migrate any existent user from the paymentAccount step and get a list is 
`/Upgrade/A - Remove paymentAccount onboarding step.cshtml`

**Comment by IagoSRL** [comment]
Some tweaks to the upgrade process, this is done

**Comment by joshdanielson** [comment]
@IagoSRL the alert is still set to required in both the dev and live databases and showing on listingEditor. I didn't want to change it as it should probably be in a script I assume.

**Comment by IagoSRL** [comment]
I updated the alert to be optional

**Comment by joshdanielson** [comment]
Perfect, tested and working!
