### ISSUE TITLE
Communicate to users upgraded from payment onboarding step

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#572]
Communicate to users that their listing is active and how payment works (manually by Josh)

**Comment by IagoSRL** [comment]
1005
1248
1250
1253
1256
1304
1325
1330

**Comment by joshdanielson** [comment]
@IagoSRL I think @KyraHarrington and I will do a little blurb in a newsletter (long overdue) instead of individual communications (I like sent each of these users an email after they signed up and pretty sure they didn't respond). So closing as discarded if that makes sense.
