### ISSUE TITLE
Direct manipulation of marketplace listing

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#580]
Includes cleanup of juvo's html and css.
This issue has been converted and renamed from #412 (Original title "Refactor Listing CSS/HTML"
I've uploaded my work on the accelerated process for onboarding, including allowing the professional to edit their own profile/listing through buttons on the listing.

Josh and I talked earlier this week. My understanding is that he and Aram were going to develop user stories from these mockups, and then refer back to me with any questions.

There are two layouts in the mockup. The first is an empty listing. This is what a professional would see immediately after they sign up. The second layout includes a piece of content in each of the listing sections to demostrate what happens in each section as the professional adds content to their listing.

There are parts of the current listing layout that I gloss over in the markup. If something is unclear, please ask. For instance, I don't propose any changes for the time being in the area around the profile photo and the book button.

The yellow stickies are additional notes about layout and text.

The blue lines indicate URLs where the buttons lead.

The Profile/Listing actions are terse user actions. (E.g., _edit profile photo_ can be expanded to _While seeing their profile photo in the context of the listing, the professional is able to edit the profile photo by clicking/tapping on it_). These are hints (but not definitions) for user stories.

![direct-edit-profile](https://user-images.githubusercontent.com/6644016/28485915-eb87711a-6e31-11e7-8d08-39397e8c6c36.png)

**Comment by joshdanielson** [comment]
@IagoSRL this branch is ready for you to remove the need for UserID at listingEditor.

**Comment by IagoSRL** [comment]
It's done

**Comment by joshdanielson** [comment]
Closing as this was merged to master with #694.
