### ISSUE TITLE
Add Booking Policies to Listing

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#585]
As a client I want to see what a service professional's cancellation policy is while deciding whether or not to book them.

Tasks:
- [ ] Add data to js activity
- [ ] Add and style on html

**Comment by IagoSRL** [comment]
2

**Comment by RialtoBeach** [comment]
2

**Comment by ardanak** [comment]
3

**Comment by joshdanielson** [comment]
2

**Comment by IagoSRL** [comment]
@joshdanielson You did this as part of #580, already merged, so closing
