### ISSUE TITLE
Remove overlay that automatically appears when a visitor lands on or downloads loconomics

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#587]
As a user visiting or downloading Loconomics, I want to learn about Loconomics before signing up.

Tasks:
- [x] Stop showing annoucementModal.html to new visitors

**Comment by joshdanielson** [comment]
@IagoSRL not sure how quick this is, but if it's an easy task, can you move it to the next release? If not, just leave it as is.

**Comment by IagoSRL** [comment]
This means, removing at all the modal (files , data) right?

**Comment by joshdanielson** [comment]
@iagosrl yes. If we need something like it ever again, we can find the code and reuse it.

**Comment by IagoSRL** [comment]
Done and merged to master. Give it a try but is pretty straightforward so I didn't requested a QA phase.
I removed the generic announcement modal too, but can be recovered by reverting just one commit (b2ca12509).

**Comment by joshdanielson** [comment]
@IagoSRL thank you! tested on master with an incognito window and working.
