### ISSUE TITLE
Revise Welcome.html with next step options

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#589]
Revise post-sign-up screens targeting either the client or the professional. **skipped for professionals signing up from landing page**

Create a single post- sign up screens for users coming through the generic sign up form (not a landing page), that allows providers to start creating their first listing. Clients can then book services.

Should include:
- Want to add a listing?
- Want to book a professional?
- Want to help us recruit?

**Comment by IagoSRL** [comment]
2

**Comment by joshdanielson** [comment]
2

**Comment by ardanak** [comment]
2

**Comment by joshdanielson** [comment]
@IagoSRL I just added this to the #567 branch.
