### ISSUE TITLE
Revise initial onboarding steps

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#592]
As a new service professional or client, I want to enter only enter what's required to continue to my next task (create listing or book service professional).
## Mockup
![onboard](https://user-images.githubusercontent.com/1202838/28635984-7e4e0244-71f1-11e7-999b-92b2f272d3dc.png)

**Comment by IagoSRL** [comment]
@joshdanielson I'm figuring out next steps implementing this new Onboarding chart. The public contact step includes 'business name', but our new activity 'publicContactInfo' has not that field, will we manage that in a new step (for the serviceProfessionalBusinessInfo activity) or left that out?
(maybe is easier to left that out, and same step works for client)

**Comment by joshdanielson** [comment]
@IagoSRL I agree, let's leave it out. They can add it via serviceProfessionalBusinessInfo from listingEditor.

**Comment by IagoSRL** [comment]
Merging all this branch into *master*. Do not push more changes!

**Comment by IagoSRL** [comment]
@joshdanielson The only child issue opened here is #572 about communicate with users about onboarding change / payment not requirement. Maybe too send to any user stuck in onboarding commenting the changes.
