### ISSUE TITLE
Require publicContactInfo for all users during onboarding

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#594]
Make publicContactInfo.html a required activity for onboarding if not already entered.
## Service professionals:
- First name
- Last name
- Mobile phone
- Business name
## Clients:
- First name
- Last name
- Mobile phone

**Comment by IagoSRL** [comment]
2

**Comment by RialtoBeach** [comment]
2

**Comment by joshdanielson** [comment]
2

**Comment by ardanak** [comment]
2

**Comment by IagoSRL** [comment]
@joshdanielson Sorry I commented at #592 what I could have commented here better about "Business name". 
Apart of that, code changes to place public contact info as first step is done.

**Comment by joshdanielson** [comment]
@IagoSRL I agree, let's leave it out. They can add it via serviceProfessionalBusinessInfo from listingEditor.

**Comment by IagoSRL** [comment]
OK

**Comment by IagoSRL** [comment]
Since the activity is ready, onboarding process updated with this as first activity and migrate scripts done, this is done for testing too.

**Comment by IagoSRL** [comment]
Enabling onboarding for clients and testing sign-up I found errors at `publicContactInfo` that prevents any new user to move forward. Digging into it, this activity is trying to save an empty address underneath and fails (there are no address fields here); it does this indirectly by using a ContactInfoVM class, and there is another one UserProfileVM (that internally is named ContactInfoVM wrongly) that looks more like a copy and produces the same problem in the userBirthDay activity, and in all cases have lot of unused code. I need to clean-up the mess there to fix the problems.

Moved this from QA until I review all that (cannot be used for new profiles now)

**Comment by IagoSRL** [comment]
Fixed issues by refactoring the buggy VM inside the specific activities, working for signed-up users. Put in QA again

**Comment by joshdanielson** [comment]
Remaining tasks:
- [ ] Review alert to ensure it is marked as complete
- [ ] Step should be skipped if info is already collected (as it is in /signup/client

**Comment by IagoSRL** [comment]
@joshdanielson The new second task you put here should not be removed because of #717?

**Comment by joshdanielson** [comment]
@IagoSRL good catch. I removed the task.

**Comment by IagoSRL** [comment]
Updated the alert, uploaded to *dev* and tested on new signup; so all sub-tasks here are done

**Comment by joshdanielson** [comment]
Tested and closing (alert no longer appears). publicContactInfo still showing if entered but that's okay since #717 will require it.
