### ISSUE TITLE
Require addJobTitles for service professionals who come from generic sign up

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#595]
After the user signs up and chooses that they want to create a free listing, has filled out their publicContactInfo/Photo we need to require they choose a job title before they are taken to edit their listing.

### Tasks
- [x] Require only for users who choose to "Add a listing" who did not already choose a job title
- [x] Skip for landingPage user signups

**Comment by IagoSRL** [comment]
2

**Comment by joshdanielson** [comment]
2

**Comment by RialtoBeach** [comment]
2

**Comment by ardanak** [comment]
2

**Comment by joshdanielson** [comment]
@IagoSRL I moved this to Review/QA thinking you did this on #584 but am not sure.

**Comment by IagoSRL** [comment]
@joshdanielson I did not move this to QA because the second task here is not done (skipping addJobTitle when coming from landing page), that is on the works.

**Comment by IagoSRL** [comment]
Pushed the change to skip addJobTitles, and some fixes to onboarding setup, now needs more testing.

**Comment by joshdanielson** [comment]
@iagosrl just testing this and having some issues. I did grunt build-landingPages publish-landingPages and then was able to load the welcome/san-francisco landing page, enter my job title and email address and then submitted and then was taken to this screen (see it says /dashboard in the URL):
![screen shot 2017-11-07 at 10 31 48 am](https://user-images.githubusercontent.com/1202838/32510918-1de8d17e-c3a7-11e7-815f-89962a2a81cf.png)

**Comment by IagoSRL** [comment]
Yeah, that happens on local develoment (I know it); the redirect that exists from landing to webapp is based on being in the server that host the page and there there is no need to pick a 'appDebug.html' to load the webpp, is just right in the index. So is normal, as expected, if you tweak the URL putting /appDebut.html#!dashboard would behave as will do when in the server.

I was thinking for a while to rename the appDebug.html as index.html and remove the app.html, both to prevent confusion and to help in this situations for a closer behavior to server/production.

**Comment by joshdanielson** [comment]
@IagoSRL okay, still confused as it should bring me to the next step in onboarding, publicContactInfo, right? And I manually did that, entered my contact info, and clicked next step and got the "Create a free listing" form:
![screen shot 2017-11-07 at 10 42 11 am](https://user-images.githubusercontent.com/1202838/32511374-756bbabe-c3a8-11e7-8245-a645dc667fcd.png)

**Comment by IagoSRL** [comment]
It should skip that automatically

**Comment by joshdanielson** [comment]
@IagoSRL yeah, I think the fact that it took me from the landing page sign up to /dashboard is the first issue. I wonder if it got tripped up thinking I was creating another listing vs continuing the Massage Therapist one I started on the landing page.

**Comment by IagoSRL** [comment]
@joshdanielson I tested this again, normal signup and landing page and worked (despite the URL of the landing page not going to appDebug.html, but the hash part was correctly set as publicContactInfo not dashboard). Please try again ensuring to have latest commits.
For testing landing pages, run `grunt build-landingPages` before try.

**Comment by joshdanielson** [comment]
@IagoSRL weird, it's still happening. I did do the grunt build-landingPages before and now.

**Comment by joshdanielson** [comment]
@IagoSRL I tried this one last time and still the same. I also tried the dev site thinking you'd uploaded it there, but the signup is missing altogether from the landing page there:
![screen shot 2017-11-07 at 2 54 43 pm](https://user-images.githubusercontent.com/1202838/32522308-b50192c0-c3cb-11e7-9570-ec6c6fd72f62.png)

**Comment by IagoSRL** [comment]
@joshdanielson I pushed to *dev* all Onboarding work until now. I did test successful:
- http://dev.loconomics.com/welcome/dog-care-professionals.html
- http://dev.loconomics.com/#!/learnMoreProfessionals
Can you try there again, please?

**Comment by joshdanielson** [comment]
@IagoSRL tried both and both working. @KyraHarrington is also testing (general onboarding). Closing.

**Comment by joshdanielson** [comment]
@IagoSRL just tried signing up from the home page /signup/client, clicked "add a free listing" and completed publicContactIinfo (was already entered..fine with #717 happening), added my schedule and landind on listingEditor without a job title:
![screen shot 2017-11-09 at 10 18 18 am](https://user-images.githubusercontent.com/1202838/32622404-966dbc90-c537-11e7-91fb-48d40e8c431b.png)

**Comment by IagoSRL** [comment]
@joshdanielson Pushed other changes to *dev*, tested both with Firefox and Chrome, from signup activity, choosing 'add listing' and works...unable to reproduce you last error.

**Comment by joshdanielson** [comment]
Tried again and working fine now!

**Comment by joshdanielson** [comment]
@IagoSRL tested in booking, too and working. Closing
