### ISSUE TITLE
Remove phone-number from generic sign-up

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#596]
This should alleviate any errors using facebook sign-up.

## Tasks
- [x] Remove from signup form & form validation
- [ ] Remove as requirement in REST API (constraints)

**Comment by joshdanielson** [comment]
2

**Comment by IagoSRL** [comment]
2

**Comment by ardanak** [comment]
2

**Comment by joshdanielson** [comment]
Closing as duplicate to #717.
