### ISSUE TITLE
Improve search speed for job title searches

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#597]
Child Story | Target Persona(s) | Investable 
------------ | ------------- | ------------- 
I want suggested results to appear quickly when I search so I can save time typing and know what I'm entering is correct. |  | - 
**Test Cases** | 
1) Make sure the job title search in /addJobTitle is fast
2) Make sure the job title search in /learnMoreServiceProfessionals is fast
3) Make sure the attribute search in /servicesOverview is fast
4) Make sure the job title search on the home page is fast

### Research best solution:
- http://lucene.apache.org/solr/features.html
- https://www.elastic.co
### Front-end
- [x] /learnMoreProfessionals
- [x] /addJobTitles
- [x] / (home page)

**Comment by RialtoBeach** [comment]
3

**Comment by joshdanielson** [comment]
3

**Comment by IagoSRL** [comment]
2, hope not 3

**Comment by ardanak** [comment]
3

**Comment by IagoSRL** [comment]
With the new autocomplete component did a minor change for the timing that executes the search requests, that can have a small impact on perceived performance, but still the big problem is:
- the time the server takes to prepare the data (the large and complex SQL).
- this autocomplete is using the same query/API that the home page search, that returns not only job-titles, but service professionals and search categories too, all based on location; location is not needed just to pull a list of the job titles we support. In an older version, we had a specialized and fast auto-complete query/API.

By fixing the complex SQL problem we are fixing the home page / marketplace search performance too. But still an optimized, job titles only, query for auto-complete is the ideal.

**Comment by joshdanielson** [comment]
@IagoSRL I copied the user story from #15 and closed that issue as a duplicate. Here are the affected activities to review for the front-end implementation:
- [ ] /learnMoreProfessionals
- [ ] /addJobTitles
- [ ] /servicesOverview
- [ ] /home (job title search)

**Comment by joshdanielson** [comment]
@IagoSRL also review issues #345, #116, #214 to see if they can be closed with this fix.

**Comment by IagoSRL** [comment]
@joshdanielson I finished the remaining details here, and uploaded a minor change to *dev* about the new job-titles/autocomplete API. Please test.

I closed #116 since is fixed, the other related ones not affected

**Comment by joshdanielson** [comment]
@IagoSRL addJobTitle looks great. The home page search is still slow, though.

**Comment by IagoSRL** [comment]
Home should be fast too, but test on branch (except the server was reloading after pushing an API change).

**Comment by joshdanielson** [comment]
@IagoSRL tested and working very fast in the branch!

**Comment by IagoSRL** [comment]
With the last fix to prevent a regression, displaying un-approved job-titles, and tested, I close and merge this into master.

**Comment by joshdanielson** [comment]
Re-opening this issue for these errors in the home page search:
- "Sounds like you?" should not be there as it's a client search
- returns service professional descriptions instead of client descriptions
- mistakenly includes "No? Fear not, we'll create a  job title for you..."
- I'm still questioning the speed as well
![screen shot 2017-11-07 at 7 20 41 am](https://user-images.githubusercontent.com/1202838/32501321-8c824018-c38c-11e7-932f-a7a23105af17.png)

**Comment by joshdanielson** [comment]
@IagoSRL I think I can do a quick fix as the home page is its own component.

**Comment by joshdanielson** [comment]
@IagoSRL I take that back...it does not look like the home page has its own (kocomponents/home/search-box does not appear to be in use. I'm not sure how to alter job-title-autocomplete...I'm thinking there should be one more param searchType with two different values to use with visible: searchType: home/addJobTitle and then I can alter the html for each. 

Also
- "Sounds like you?" should be "Sound like you?" (for addJobTitle searches)

**Comment by joshdanielson** [comment]
@IagoSRL okay, I'll open a new issue! Same thinking (I think), which is good.
