### ISSUE TITLE
Bug S1: Error When Click on Message in Inbox

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#61]
![screen shot 2016-12-02 at 10 55 42 am](https://cloud.githubusercontent.com/assets/1202838/20846487/b9c0f322-b87e-11e6-9f5e-41657ff5ab67.png)
![screen shot 2016-12-02 at 10 55 35 am](https://cloud.githubusercontent.com/assets/1202838/20846488/b9e46226-b87e-11e6-8a24-4ee0e199cca7.png)

**Comment by situatedbit** [comment]
@joshdanielson I'm not able to reproduce this. On Dev, I've tried clicking on Open Booking on inbox message as both a client and a professional. Is there any other information you can add to the issue that might help me reproduce it. Have you seen it happen in the last month?

**Comment by joshdanielson** [comment]
@situatedbit closing. Can't reproduce.
