### ISSUE TITLE
Bug S1: Live Site - No place for client to input mobile phone number on bookings.

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#621]
@IagoSRL if you can look at this tomorrow first thing, it seems like something I should have caught sooner. I'm assuming the user found Liat's profile and tried to create an account during the booking (I attached that screenshot, too), which does NOT ask for mobile phone number. So we just need to add that back to the booking (for now) until we complete #594. When we get to that, we'll have to have this step re-appear in the booking path for those who don't have the required fields complete.
[Loconomics Cooperative, Inc.pdf](https://github.com/loconomics/loconomics/files/1220972/Loconomics.Cooperative.Inc.pdf)
![screen shot 2017-08-13 at 2 36 09 pm](https://user-images.githubusercontent.com/1202838/29253562-48736838-8035-11e7-860c-32703cd2ab93.png)

**Comment by IagoSRL** [comment]
For some reason we have a copy of the signup template inlined in the booking, and was no updated with the changes done to signup globally. I quickfixed and published already this, but we must have another issue to de-duplicate this preventing this and others problems in future.

**Comment by IagoSRL** [comment]
New published version tagged as 1.6.2 (only at webapp)

**Comment by joshdanielson** [comment]
@IagoSRL thank you! Let's discuss a bit on the call.
