### ISSUE TITLE
Accessibility: New focus-setting code does not allow caret browsing

### ISSUE THREAD

**Issue by ndarilek** [loconomics/loconomics#623]
The newly-written code, which sets focus to the first `<h1/>`, does not seem to allow for caret navigation. While tab/shift-tab works, any attempts to move the caret with the arrows seem to refocus the title.

Steps to reproduce:
 1. Visit dev.loconomics.com in Firefox.
 2. Ensure that caret browsing is active by pressing F7, then clicking through the dialog if necessary.
 3. Press _tab_ to move focus to a link.
 4. Press an arrow key.

Expected result: I'm able to arrow around the page character-by-character or line-by-line.

Actual result: Focus seems to land back on the first `<h1/>`.

**Comment by IagoSRL** [comment]
I'm testing, I found the problem when navigating to Signup but not to "Login" and "List your services".

I can see that at Signup there is a H1 that is visually hidden (only available for screen readers using sr-only class); this may be the problem.

**Comment by IagoSRL** [comment]
Some more research: for each navbar link behavior is different:
- Link Signup: I had to press the right arrow button 27 times to reach the beginning of the first visible text ("Sign up for free").
  - It's the number of characters of the 'h1' header visually hidden with "sr-only" plus some whitespace. That h1 was the element focused.
- Link Login: I had to press the right arrow button 2 times to reach the beginning of the first visible text ("Log in to your account". The container was the element focused.
- Link List your services: the caret appear correctly at the beginning of the 'h1' header ("Work independently…together."). That h1 was the element focused.

So, some smaller problem when is the container the focused element, and major when the "sr-only" text is the one focused. The ideal situation is for the 'h1' header to be visible for everybody and the first text in the activity/page.
My question is: the header at Signup with 'sr-only' is not being managed correctly by the screen reader?

**Comment by ndarilek** [comment]
Hmm, I'm encountering this directly on http://dev.loconomics.com. I 
can't navigate past the text "Make life better" unless I use the tab key.

If I click "Log in," the behavior seems to go away. I seem to be stuck 
immediately after landing on the main page, where I can't review the 
homepage content by line/character.

**Comment by ndarilek** [comment]
Interesting, can't seem to duplicate the issue now.

And it works fine on the signup form too.

Not sure what happened earlier, but I'm tentatively willing to call this 
closed.

**Comment by IagoSRL** [comment]
I tested home page and seems to work too.
Just I found another error introduced by my change on "navigation focus": when page load first time, it focus the content, so users may don't know there is a navigation and header before that; we must add a 'skip navigation' link too at beggining.

**Comment by IagoSRL** [comment]
I pushed changes for the two things I commented lately: skip navigation link and fix the first load focus. @ndarilek If this ones are fine and the original error commented here is not reproducible we can close this.

**Comment by joshdanielson** [comment]
@ndarilek if you still see this happening, please re-open with steps to reproduce.
