### ISSUE TITLE
Accessibility: Issues with location search autocomplete

### ISSUE THREAD

**Issue by ndarilek** [loconomics/loconomics#625]
On the main page, searching for a location gives no indication that it is either an autocomplete field, or that completion results are available. If I type a partial string, "aus" for example, down-arrow presents available completion results.

I found [this](https://haltersweb.github.io/Accessibility/autocomplete.html) as a good example of an accessible autocomplete field that works well with my screen reader. I haven't tested it on a mobile device, but it does seem that they've taken that into account as well.

**Comment by IagoSRL** [comment]
Thanks for the link resource, I will review it additionally to the course tips to make all autocomplete in the site accessible.

A special note goes for this 'location autocomplete', since is now a third party plugin using Google Maps API, but I must be able to rebuild it.

**Comment by IagoSRL** [comment]
This is not done, but we have now the input-autocomplete component to help in this. At the /activity/home.js file there is code to set-up the 'geocomplete' jQuery plugin (that is to be replaced/removed) and next to that there is some commented/untested code about using the Google Maps API directly for that purpose; that should help implementing it.

Optional, but ideally, is to wrap the new code in a component (under /kocomponent) following the examples of home/search-box.js and job-title-autocomplete.

**Comment by IagoSRL** [comment]
Done per PR #661 by @ndarilek
