### ISSUE TITLE
Accessibility: Issues with profession search autocomplete

### ISSUE THREAD

**Issue by ndarilek** [loconomics/loconomics#626]
When I visit the profession search field on the main page, then type in something like "massage", no indication is given that an autocomplete option is available. Likewise, up/down-arrow does not select a profession.

I do see the list of professions below the field, but there's no easy way via the keyboard to add the full text of a profession into the field, nor is it obvious that new results are available.

Please see #625 for a link to an accessible autocomplete widget that might work here.

**Comment by IagoSRL** [comment]
Implementation for this is done too as commented in #635

**Comment by IagoSRL** [comment]
Since comments at other issues/emails about new autocompletes are accessible, I'm closing this issue (profession search specific autocomplete).
