### ISSUE TITLE
Accessibility: schedulingPreferences accessibility issues

### ISSUE THREAD

**Issue by ndarilek** [loconomics/loconomics#627]
Here are some issues I've encountered on this screen:

 * You're putting labels within checkbox input elements. E.g.:

```
                                <div>
                                    <label>
                                        <input type="checkbox" class="checkbox"
                                               data-bind="switch: { disabled: isLocked, state: day.isEnabled }"
                                       /><span data-bind="text: label"></span>
                                    </label>
                                </div>
```

This is incorrect, as the label should be an entirely separate element. Further, this makes the checkboxes keyboard-inaccessible. They can be focused, but Space/Enter does not change their status. I need to fix this issue, as without a fix I am incapable of continuing through the signup process. I'll submit a PR shortly.

 * The Bootstrap switch component adds confusion for screen reader users. The component adds the text "ON" and "OFF" but does not correctly update their ARIA states to indicate which state is valid (I.e. both are presented to screen readers regardless of the current state.) Additionally, the switch is followed by the checkbox which also conveys the state of the widget. I'd recommend ditching the switch for now and sticking with a basic checkbox, only adding in components once they are vetted as accessible.
 * Labels are not matched to their inputs. I'm not super familiar with Knockout templating, but my PR adds the correct attributes to the `isAllTime` input. E.g.:

```
                        <div class="WeeklySchedule-allTime">
                            <label for="isAllTime">
                                <span>All days/times</span>
                            </label>
                            <input id="isAllTime" type="checkbox" data-bind="switch: { disabled: isLocked, state: schedule.isAllTime, onColor: 'success', offColor: 'lightgray'}" />
                        </div>
```

Note the `for` attribute on the `<label/>` matches the `id` attribute on the `<input/>`. When I tab to this checkbox, the associated label is read. When I tab to all other checkboxes, I hear "checkbox not checked" and not the associated day. If you can duplicate this, perhaps by setting the ID on the inputs to the template's day and the `for` on the label to the same, I can use your fix to implement similar changes for other broken form elements, but I don't know how to access Knockout data values in HTML attributes.

**Comment by ndarilek** [comment]
I've updated the associated PR to correctly associate form elements with labels. Adding/removing time blocks seems to work OK. It may be possible to provide better feedback, but for the moment I think that aspect is good.

So all that needs to happen is dropping/replacing the Bootstrap switch component and this screen is fairly usable/accessible.

**Comment by IagoSRL** [comment]
I'm looking at the problem with the Bootstrap switch and will push to the is528 branch, will let you know.

**Comment by IagoSRL** [comment]
Hi @ndarilek, I replaced the use of Bootstrap switch with custom code that makes the experience to be just like a regular checkbox; I created CSS classes to give it a better visual appearance (still not exact as before but good enough) but the important is that doesn't affect keyboard and accessibility; I wrapped code in a component to ensure being consistent used.

At /marketplaceJobtitles activity there was one of that buttons too and I replaced it, adding a label too

**Comment by ndarilek** [comment]
The new switch implementation on this page addresses all of my previous concerns.

**Comment by IagoSRL** [comment]
Thanks for check it @ndarilek  
Then I can close this issue now (feel free to re-open if something seems still wrong with this subject)
