### ISSUE TITLE
paymentAccount: "Skip for now" button doesn't seem to work

### ISSUE THREAD

**Issue by ndarilek** [loconomics/loconomics#630]
Not sure if this is an accessibility issue, but when I attempt to skip this step to finish onboarding, pressing Space or Enter on the "Skip for now" button does nothing.

**Comment by IagoSRL** [comment]
This may have broken depending on work at #563 (I though that work was not pushed to dev but will double check); and soon that step will be removed from onboarding, will see if can do that before our deadline or fix this.

**Comment by joshdanielson** [comment]
@IagoSRL for items that we know will be fixed/removed with completing onboarding, we can just detail them with a clear plan of when they'll be accessible, i.e. September 15th with Release x.x. It doesn't make sense to spend time on them and shouldn't affect anything with the proposal as long as it's clear it'll be complete in September as part of other changes.

**Comment by ndarilek** [comment]
Cool, would it be possible to tweak my account on dev.loconomics so I'm 
passed onboarding? Not sure if I can check out other issues until that 
is done.

Thanks.

**Comment by IagoSRL** [comment]
@ndarilek I set your user as completed the paymentAccount, so onboarding is done for your user. Please log-out and log-in to ensure you get the update.

**Comment by ndarilek** [comment]
Thanks!

**Comment by IagoSRL** [comment]
You are welcome.

@joshdanielson I will let you to manage this issue as you consider and document the 'know bug' until we do #563

**Comment by joshdanielson** [comment]
Closing this as part of #563.
