### ISSUE TITLE
Revise visibility/Removal of modals

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#643]
Reloading any page with only CSS shows modals that should not be visible:
![screen shot 2017-08-30 at 5 44 51 pm](https://user-images.githubusercontent.com/1202838/29901211-8d24f540-8dab-11e7-92fe-bca8ba438ef2.png)
- announcementModal: Matt asked that this be removed as a usability issue so we can hide/remove it if you're okay with that.  (I couldn't find it as an issue). 
- confirmModal
- datetimePickerHelp
- errorModal
- notificationModal
- textEditorModal
- timePickerModal

**Comment by IagoSRL** [comment]
At the moment we stop pre-including the modals in html but requiring them as of their javascript files this will get fixed. At #490 (I did some moves forward for that issue already by splitting js from app.modals.js as part of #528 )

**Comment by IagoSRL** [comment]
@joshdanielson This is done and pushed to branch is528. Please confirm it by:
- checking you don't see it in the html
- you can use all modals (the hidden activity _modals is the quickest way to test all available)
- modals are not in the html even after use them

**Comment by joshdanielson** [comment]
@IagoSRL tested and looks good! Closing.
