### ISSUE TITLE
Grunt task htmlmin is crashing

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#655]
Recently the `build-webapp` task was crashing because of the `htmlmin` subtask; it's disabled right now and we can release still without that step, only that the html file is bigger.

**Comment by joshdanielson** [comment]
@IagoSRL I'm not sure this is related, but I'm having issues with my saved changes not showing up on my localhost even though it appears grunt built the html again (I refreshed). It does work if I open a second terminal tab and do a grunt build-html, though. I'm working on the is580 branch and updated from master this morning.

**Comment by IagoSRL** [comment]
@joshdanielson Try using `grunt build-dev`, since the `build` one is set-up now to just do a 'release build' (a few more tasks to optimize, like htmlmin, than build-dev); is faster too and any additional task will not be useful for you or anybody just in development

**Comment by IagoSRL** [comment]
This still happens with content from *master*. The error still the same: `ENAMETOOLONG`:
```
Running "htmlmin:webapp" (htmlmin) task
Warning: spawn ENAMETOOLONG Use --force to continue.
```

Debugging with VSCode and node inspector, running 'grunt htmlmin:webapp', first related error shows this stack is:
```
at new HTMLParser (D:\Iago\Proxectos\Loconomics\code\app\node_modules\grunt-contrib-htmlmin\node_modules\html-minifier\src\htmlparser.js:235:13)
  at minify (D:\Iago\Proxectos\Loconomics\code\app\node_modules\grunt-contrib-htmlmin\node_modules\html-minifier\src\htmlminifier.js:944:3)
  at exports.minify (D:\Iago\Proxectos\Loconomics\code\app\node_modules\grunt-contrib-htmlmin\node_modules\html-minifier\src\htmlminifier.js:1304:10)
  at D:\Iago\Proxectos\Loconomics\code\app\node_modules\grunt-contrib-htmlmin\tasks\htmlmin.js:22:15
  at Array.forEach (<anonymous>:null:null)
  at Object.<anonymous> (D:\Iago\Proxectos\Loconomics\code\app\node_modules\grunt-contrib-htmlmin\tasks\htmlmin.js:11:16)
  at Object.<anonymous> (D:\Iago\Proxectos\Loconomics\code\app\node_modules\grunt\lib\grunt\task.js:252:15)
  at Object.thisTask.fn (D:\Iago\Proxectos\Loconomics\code\app\node_modules\grunt\lib\grunt\task.js:70:16)
  at Object.<anonymous> (D:\Iago\Proxectos\Loconomics\code\app\node_modules\grunt\lib\util\task.js:294:30)
  at Task.runTaskFn (D:\Iago\Proxectos\Loconomics\code\app\node_modules\grunt\lib\util\task.js:244:24)
  at Task.<anonymous> (D:\Iago\Proxectos\Loconomics\code\app\node_modules\grunt\lib\util\task.js:293:12)
  at D:\Iago\Proxectos\Loconomics\code\app\node_modules\grunt\lib\util\task.js:220:11
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)
  at Function.Module.runMain (module.js:686:11)
  at startup (bootstrap_node.js:187:16)
  at bootstrap_node.js:608:3
```

Beggining of the error message (it shows a large piece of the html being processed, ending at the html closing tag plus newline, but starting at a midpoint in the input html; I just get first lines of the message here)
```
Error: Parse Error: <legend class "text-center"><span data-bind="text: serviceProfessionalInfo() && serviceProfessionalInfo().profile() && serviceProfessionalInfo().profile().firstName()"></span>'s
                          locations:</legend>
                        <div class="Box-sm" data-bind="template: { name: 'addresses-select-template', data: serviceAddresses }"></div>
                      </fieldset>
                      <fieldset class "text-center" data-bind="visible: clientAddresses.hasAddresses">
                        <legend class="text-center">Select one of your locations:</legend>
                        <div class="Box-sm" data-bind="template: { name: 'addresses-select-template', data: clientAddresses }"></div>
                      </fieldset>
                      <button type="submit" class="btn btn-primary btn-block" data-bind="disable: isLocked, click: nextStep, visible: booking().serviceAddress">Save and continue</button>
```

Continue debugging, a strange situation happens when entering a large loop (I wasn't able to finish it step-by-step) when running the 'grunt-notify' task: it tries a look up of executable files for 'growlnotify' (at Windows); if I let the process end, it ends without displaying messages at the console output (opposite as standard execution, that shows up the first commented message as of Grunt logging).

Tried disabling 'grunt-notify', and running the `grunt htmlmin:webapp` task and I get the error message I get when debugging (with the large html inside) so it seems that when trying to execute the notification with that message throws the "ENAMETOOLONG", hidden the original error. What happened, is that notifications are executed by spawning a process passing the error message as a command line parameter, and it is too long, then leading to that ENAMETOOLONG error that usually happens as part of a too much large path.

So knowing now which is the real error message, what happens is a parsing error of the html near the beginning of the code in the message, so needs to review bad html syntax.

**Comment by IagoSRL** [comment]
Found source of the problem and fixed: several occurrences of `class "` and `class"` wrong code (lacks an equal sign there or there is a whitespace rather than an equal sign), at `booking.html` (activity).

Now htmlmin works and the full task is enabled again, merged into master.
