### ISSUE TITLE
Revise onboarding order

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#687]
### LONG DESCRIPTION
To reduce onboarding fatigue, only two steps will be required before reaching the listingEditor.
### To-do
- Include only the following onboarding steps:
  - All:
    - welcome
  - Service professionals
    - publicContactInfo #594   
    - addJobTitles #595   
    - serviceAddresses

**Comment by IagoSRL** [comment]
At this issue, the 'serviceAddresses' step is not at the diagram in the Epic #592, and I think is the correct one. I think any further comment about new onboarding steps can happen in the epic, and this issue already did his job as requiring us to review the process, so I'm closing.

**Comment by joshdanielson** [comment]
@IagoSRL I added a new issue #712 to capture this. We discussed this last week or the week before to alleviate users getting confused with required credentials (it's straight-forward with a service address entered)
