### ISSUE TITLE
Communication to non-US users who sign up

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#688]
### Long Description
Users who sign up that are not located in the US should be told that we're not yet launched outside of the US and to check back periodically and invite programmers/business people to email us if they'd like to launch in their country. 
### To-dos
- revise /welcome
- pull in locale

**Comment by joshdanielson** [comment]
@IagoSRL I'll let you close this once it's merged.

**Comment by IagoSRL** [comment]
I tested this on *dev* and worked perfectly, closing
