### ISSUE TITLE
servicesOverview taking a long time to load

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#70]
From Christopher:
- [ ] brief description not showing for at least 2 seconds, sometimes more
- [ ] attributes can take up to 1 full minute to load

@IagoSRL I think it's pretty random, but the more attributes there are under serviceAttributeCategories the longer. This happens for licensesCertifications as well, I know.

**Comment by IagoSRL** [comment]
Related to #15 (that's more generic)

**Comment by joshdanielson** [comment]
Closing as duplicate to #15
