### ISSUE TITLE
Bug S1: Booking time requested not able to be saved (on master)

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#711]
### Long Description
When clicking on a time to request a booking, there is no option to save and clicking the time does not save it.
### Steps to reproduce
- Go to a listing
![screen shot 2017-11-02 at 11 53 25 am](https://user-images.githubusercontent.com/1202838/32344583-9991ff1c-bfc4-11e7-9695-6e7cba7fc4fe.png)
- click "Schedule"
- select a service
![screen shot 2017-11-02 at 11 55 24 am](https://user-images.githubusercontent.com/1202838/32344645-ca05b3a0-bfc4-11e7-9ceb-4fca6d2d16f4.png)
- select an appointment time
![screen shot 2017-11-02 at 11 55 33 am](https://user-images.githubusercontent.com/1202838/32344664-d9c7cec2-bfc4-11e7-9dfd-37dbde5732e5.png)
![screen shot 2017-11-02 at 11 55 39 am](https://user-images.githubusercontent.com/1202838/32344665-d9f86d34-bfc4-11e7-84cf-a1d56d060e22.png)
- No way to move forward with the booking

**Comment by IagoSRL** [comment]
You should be able to click a time and that automatically moves forward

**Comment by joshdanielson** [comment]
Tried again on dev just now and still happening.

**Comment by joshdanielson** [comment]
@IagoSRL tested on branch and working. Closing.

**Comment by IagoSRL** [comment]
Pushed changes to *dev*.

thanks!
