### ISSUE TITLE
Require serviceAddresses in Onboarding

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#712]
### Long Description
To make it clear to service professionals their required credentials once they get to listingEditor, we should require serviceAddresses during onboarding

**Comment by IagoSRL** [comment]
It's done, moved to QA

**Comment by joshdanielson** [comment]
@IagoSRL looks good. Is it possible to skip to the next onboarding step after clicking save on the /serviceAddressEditor form?

**Comment by joshdanielson** [comment]
Remaining task:
- [ ] skip to the next onboarding step after clicking save on the /serviceAddressEditor form

**Comment by IagoSRL** [comment]
Move to next step directly from editor done

**Comment by joshdanielson** [comment]
Tested and working. Closing.
