### ISSUE TITLE
Warning: Browserify bundle error: Error: Cannot find module './activities/userBirthday' from '/home/nolan/Projects/loconomics/app/source/js' Use --force to continue.

### ISSUE THREAD

**Issue by ndarilek** [loconomics/loconomics#714]
Getting the following when attempting to work on #642. Could someone please check this into master so I can continue? Thanks!

**Comment by joshdanielson** [comment]
@IagoSRL can you review this? It's blocking @ndarilek on completing #638.

**Comment by IagoSRL** [comment]
I saw the problem: the link has a wrong casing, causing error only on case-sensitive file systems. Was linked as 'userBirthday' but file is actually 'userBirthDay'.

I fixed and commit directly to *master*, should work now @ndarilek.
