### ISSUE TITLE
Bug S1 (Branch 584): User gets logged out after adding job title

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#715]
### Bug Description
When onboarding as a service professional, I was forced to log in again after adding my job title.

### Steps to reproduce
1. Click "Sign up"
2. Enter form info and sign up
3. Select "Create free listing"
4. Add/review public contact info
5. Add job title and click enter
6. /login screen appears

**Comment by IagoSRL** [comment]
Pushed fix for this (required an addition to the REST API, uploaded to *dev* already)

**Comment by joshdanielson** [comment]
Tested and working. Closing.
