### ISSUE TITLE
Remove First & Last Name and mobile phone from /signup/client

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#717]
@IagoSRL after discussing this with @jameslindsay and looking back at the wireframes @situatedbit did, I think it's best we remove First and Last Name and Mobile phone from the signup form. The rationale is that the value proposition is better explained in publicContactInfo and we're more apt to get the email address, which is the most important. I tried to figure out how to do this but couldn't figure it out so assigning it to you and giving it a "2" (change if you need to).

Merging in task from #596 and closing that as a duplicate.
This should alleviate any errors using facebook sign-up.

## Tasks
- [x] Remove from signup form & form validation
- [x] Remove as requirement in REST API (constraints)

**Comment by IagoSRL** [comment]
As part of removing firstName, lastName and phone from the Signup (both front-end and back-end), I removed completely too other fields still in code but visually removed in the past: postalCode, referralCode, device; and bindings specifically `forClient` and that computed observable.

**Comment by IagoSRL** [comment]
There is an exceptional case that I'm tempted to keep the firstName and lastName as optional, underneath, but available in the API: at Facebook Connect we can read that info from the user profile and will means user has less to type (and share exact name as in Facebook --if doesn't change it at 'publicContactInfo').

**Comment by joshdanielson** [comment]
@IagoSRL that could be a solution for now...remove the * from those fields as well.

**Comment by IagoSRL** [comment]
@joshdanielson First name and Last name removed from the embedded signup when anonymous user does a booking, right?

**Comment by IagoSRL** [comment]
OK, I'm removing there too, the new onboarding for client has cover us.

**Comment by joshdanielson** [comment]
@IagoSRL may be confused so forgive me, but we need first and last name for a booking for all clients.

**Comment by joshdanielson** [comment]
*when making a booking

**Comment by IagoSRL** [comment]
Yes, my comment was about that specific case, 'when making a booking'. I remove it already, clients can set that at onboarding just after

**Comment by IagoSRL** [comment]
...except that would not be a name to display to the professional, OK, I can recover and add yet a new flag to know is from a booking.

**Comment by joshdanielson** [comment]
@IagoSRL okay, let me know when I should test on dev

**Comment by IagoSRL** [comment]
And phone number too for client booking? (was before...trying to recover some lines, kept other changed)

**Comment by joshdanielson** [comment]
@IagoSRL yes, sorry it was vague.

**Comment by IagoSRL** [comment]
Recovered firstName, lastName and phone, added flag 'atBooking' for both VM and API, used at booking and enforces that fields for new clients.
