### ISSUE TITLE
Add job-title-autocomplete param to distinguish home/addJobTitle searches

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#718]
### Long Description
Slight differences in how we display job titles and descriptions in search results require we distinguish what type of search is using the component.
### To-do
- Create job-title-autocomplete component param "searchType" with two values for now: "home" and "addJobTitle"
- Revise "Sounds like you?" to "Sound like you?"
- Edit html in job-title-autocomplete component
  - placeholder should be "Search for professionals"
  - Show "Sound like you?" only in addJobTitle
  - Show searchDescription instead of description for home searches
  - Show "No? Fear not, we'll create a  job title for you..." only in addJobTitle searchessearches seem to be fine. 
![screen shot 2017-11-07 at 7 20 41 am](https://user-images.githubusercontent.com/1202838/32501321-8c824018-c38c-11e7-932f-a7a23105af17.png)

**Comment by joshdanielson** [comment]
@IagoSRL if you do the first task, I can handle the rest.

**Comment by joshdanielson** [comment]
@IagoSRL moving this one to the top of the list. I should have caught this one this morning before the release. My fault for not catching it much sooner.

**Comment by IagoSRL** [comment]
Done, merged into *master* but I left this in QA for a quick review @joshdanielson just in case.
Note I have to do a couple of more things:
- Hide the "You're our first" at search too.
- Add 'searchDescription' column in the autocomplete results returned by the REST API (pushed this change to *dev*).

**Comment by joshdanielson** [comment]
@IagoSRL just tested this in the branch and all seems complete. Closing.
