### ISSUE TITLE
Redirect unsecure URLs to secure URL

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#719]
### Long Description
Users who type in www.loconomics.com or just loconomics.com are warned of security risks and not automatically redirected to https://loconomics.
### To-do
- review and implement suggested fix: https://www.ssl2buy.com/wiki/http-to-https-redirect-using-htaccess-or-web-config
![screen shot 2017-11-07 at 7 48 34 am](https://user-images.githubusercontent.com/1202838/32502634-1692b208-c390-11e7-8f07-217fcf8b7bfc.png)

**Comment by IagoSRL** [comment]
Dupe of #372 

Aside: the 'warning' is something new, a change in latest versions of browsers.

**Comment by IagoSRL** [comment]
Applied rule on *live* the same way as before (#372).
Looking forward to redirect 'www.loconomics.com' to just 'loconomics.com' so we have just one entry point (cached files, data stored locally is stored per domain in the browser, to prevent users having two unrelated copies is better to redirect).

**Comment by joshdanielson** [comment]
@IagoSRL tested on live and working. Closing.

**Comment by IagoSRL** [comment]
Implemented too:
> Added Rewrite rule from 'www.loconomics.com' to 'loconomics.com', both from http and https, enhanced #719

Tested going to:
- http://loconomics.com
- http://www.loconomics.com
- https://www.loconomics.com
- All goes to https://loconomics.com (that should work directly too, without conflict with other rules)

**Comment by joshdanielson** [comment]
@IagoSRL not a necessity, but we have the same issues with loconomics.coop. It's hosted on https://www.gandi.net/en. It's set up to forward to our mighty network who masks the address, but they didn't know how (or didn't want to) do the www.loconomics.coop or http://loconomics.coop redirect to https://loconomics.coop. Is there a file we can upload to the hosting account? Just thought I'd ask while it's fresh in your brain.
