### ISSUE TITLE
Bug S1 (Dev): Photo not loading in listingEditor without refresh

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#720]
### Long Description
After uploading a photo on listing editor and saving it, it does not appear in the listingEditor without refreshing.
![screen shot 2017-11-09 at 10 08 27 am](https://user-images.githubusercontent.com/1202838/32622975-8e4454c8-c539-11e7-8beb-793276abd508.png)
![screen shot 2017-11-09 at 10 18 18 am](https://user-images.githubusercontent.com/1202838/32622982-93a06b50-c539-11e7-8b90-46b254dda4b4.png)

**Comment by joshdanielson** [comment]
@IagoSRL #388 could be done in conjunction with this.

**Comment by IagoSRL** [comment]
Uploaded fix to *dev*. It's a back-end only fix, can be tested at *master* without rebuild.

**Comment by joshdanielson** [comment]
@IagoSRL this is still not working on dev or master (synced and refreshed). Same steps to reproduce.

**Comment by IagoSRL** [comment]
Sorry, I did a mistake pushing the change, is not ready. I too pushed to *dev* all latest fixes/merges

**Comment by joshdanielson** [comment]
@IagoSRL tested and working now. Closing.
