### ISSUE TITLE
Release 1.7 bug fixes

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#722]

**Comment by IagoSRL** [comment]
I tried your changes and worked.

But there is still another problem with the 'non USA countries' profile: the user gets stuck in onboarding mode, not able to finish it, with a 'Create your first listing' that leads to the welcome page (or seems to do nothing when you are already in that activity). Should we finish the onboarding just when showing the 'welcome'?

Aside, we should open an issue about to make this 'country limitation' setting configurable per set-up, so a "Loconomics Australia" show as not available any other country than theirs; and maybe a redirect proposal if they try to sign-up as USA there?

**Comment by joshdanielson** [comment]
@IagoSRL yes, we should complete their onboarding when showing the welcome.

Good to open the new issue. If/when we have foreign domains, we will redirect them there as you suggested.

**Comment by IagoSRL** [comment]
I pushed that change, and merged into master. I think is ready to be closed (you can do a final trial that onboarding finish for non US users before close)

**Comment by joshdanielson** [comment]
@IagoSRL just tested at master (and synced) and after signing up with a spain account, I did not get the /welcome message and landed on the dashboard (instead of /welcome):
![screen shot 2017-11-15 at 10 29 38 am](https://user-images.githubusercontent.com/1202838/32853367-e9d0b0c4-c9ef-11e7-84d4-42a4c4fef3c5.png)

**Comment by IagoSRL** [comment]
Oh! Fixed.

**Comment by joshdanielson** [comment]
@IagoSRL don't see anything uploaded to master yet.

**Comment by IagoSRL** [comment]
pushed that just in the branch, merged now to master

**Comment by joshdanielson** [comment]
@IagoSRL tested and closing.
