### ISSUE TITLE
Bug S2: Payment summary showing in $0.00 bookings

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#725]
### Long Description
When a free consultation is booked, payment summary with an edit icon shows up in the last step of booking and when clicking on it, it goes to this page:
![screen shot 2017-11-10 at 3 55 46 pm](https://user-images.githubusercontent.com/1202838/32683559-fee35484-c630-11e7-8021-009f2e136236.png)

### To-do
- hide if booking total $0.00

**Comment by IagoSRL** [comment]
Done (check the is725 branch)

**Comment by joshdanielson** [comment]
@iagosrl tested and working! Please merge then close.
