### ISSUE TITLE
Lead generation components style bugs

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#729]
Just released Lead Generation components (#675) at App Release 1.7.1, found some visual bugs to polish.

Check next screenshot with button too small to hold the text.

![screenshot-2017-11-21 handymen - loconomics](https://user-images.githubusercontent.com/1070576/33097935-f3c4c4e6-cf0b-11e7-8eee-128d3048d2c9.png)

...please @joshdanielson do your own test and attach anything; and fix if possible

**Comment by joshdanielson** [comment]
@IagoSRL good catch and sorry I didn't catch it. I think it's fine to save for the next release, but up to you. I just created a new branch is729-Lead-generation-components-style-bugs with a fix.

**Comment by IagoSRL** [comment]
@joshdanielson I did a small change: changed `width` as `min-width` with same value, and adding `width: auto`. Thinking in translations, and being more flexible in sizes: this way it keeps displaying with the size you wanted (the percentage) but when that value is too small, it keeps as wide as the text.
Just think that adjust a size for a text in a specific language can break at some languages so if more flexible solutions are found, the best (specifically, using min/max properties usually play better).

Anyway, "for translators", buttons labels should be kept small, since there is a chance of having a small area where text can get cut still, and even if is possible to use `white-space:normal` to allow it to span several lines, that makes it appear less as a button (that's why is not applied by deffault).
