### ISSUE TITLE
Clients UI is broken at all sizes

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#737]
### Long Description
After implement accessibility guidelines, the /clients activity gets a new header and slight layout changes (in line with all others). It's problematic because the Clients UI has a special layout.

One thing is that the new header pushed some content down while keeping the absolute elements at same place, ending with the search box/quick add box falling behind a header and users cannot used it; users even don't realize it exists at desktop (completely hidden) and a small area shows up in mobile (but not enough to know "what's that"). Looks weird and broken.

Another know issue of this UI is #31: a problem that happens too because of the absolute positioned layout, initially developed with mobile in mind (where originally worked). But now **does not work on mobile** because of the changes commented earlier: there is a double scrollbar and large white area at the bottom (user can scroll by mistake to a blank area).

### Quick solution
The complexity of this UI is mostly because of the requirement to have a lateral 'index by letter' area and layout emulating the mobile systems 'Contacts' apps.

I propose a quick solution: remove the lateral index, remove absolute positioning and use a standard layout in-line with other activities.
We lost a feature that is not used right now (because users still has not too much contacts) and recover the search bar, that actually can works better than the index to quickly find someone.

### For later
If the original layout idea, and the index, is still wanted, we can work on recover that as of issue #31 or a new one.

**Comment by joshdanielson** [comment]
@IagoSRL I agree with your proposed solution. The search bar should be more than sufficient (and probably always was, so sorry for the index feature).
