### ISSUE TITLE
39403 errors, 0 warnings potentially fixable with the `--fix` option.

### ISSUE THREAD

**Issue by ndarilek** [loconomics/loconomics#754]
That's a lot of errors... :)

I can't speak to the contents of all the errors, but I am getting lots of:

```
  150:2   error    Expected linebreaks to be 'CRLF' but found 'LF'    linebreak-style
```

I wonder if this might be handled in a different way, perhaps in Git itself rather than the linter? https://help.github.com/articles/dealing-with-line-endings/

Not sure what to do here. I'm on Linux, guessing that either Git or the bundler is switching your line endings. I don't have any custom git configuration addressing this, so I'm not doing anything special on my end.

**Comment by ndarilek** [comment]
Eliminating the line-ending check in .eslintrc and merging master into is747 drops us to 3 errors. Unfortunately, I have to scroll through so many warnings that I can't easily locate the errors, nor do I know if they're mine.

Am I missing a step to make master build without errors? Note that this happened with the original issue topic branch, so if anything, merging master made it better.

Thanks.

**Comment by IagoSRL** [comment]
PR merged, you are right in the rule change.

For pending errors, try running `eslint --quiet` to show errors only, so warnings don't annoying you.
Can't try now, but anything I merge to master I try before to don't have lint errors and build errors (but it seems is not the same in other machines :-/ )

**Comment by ndarilek** [comment]
Thanks! I think the issue is that, while there's probably an eslint command I can run, we probably as a rule shouldn't leave master in a state where it throws 39000 errors and over 200 warnings when the default build process is run. :) I know folks are very busy, so I'm not saying that to be critical, just that it may be a good best practice to get into as more developers come on-board.

#756 and its associated PR should help with this. I imagine Travis builds on Linux-based machines, and they'd have caught this issue and sent emails about it as soon as the code hit the repository. Also, the error we hit was actually in my own code, one of the new components introduced in one of my PRs, so if we'd have gotten "The build is broken" emails immediately after my PR was merged, I could have narrowed the search to my own code rather than fixing enough warnings so I could find the error in my scrollback. :)

Thanks! I'm just trying to help us work more smartly. :)

**Comment by IagoSRL** [comment]
Hi Nolan,

Well, as a rule I never push a broken build to master, so we think alike. I
try to install and build before push there. At this specific case I
recognize making a mistake not reviewing carefully all the options enabled
by eslint, and one was platform specific, and **shouldn't**.

Travis could even fail detecting this, just suppose: that I did setup
eslint from a Linux machine rather Windows; then Travis run and detects no
errors (under Linux), everything looks fine; but Eslint by default set
Linux line endings on that case, and another dev working on a Windows
machine pulls master and gets 39000 (linting) errors. Easily could have
happened that way, and Travis didn't help there.

Still, Im open to setup Travis, but I have no experience with it so help is
welcome here.


---------------


About PRs, I did a mistake too merging this two from the web. I want to
push forward, didn't have a computer that moment and code look fine (one of
them I reviewed previously and even commited changes, and the other was
very similar and at both cases, the components were not used still) and
just merged: another mistake of mine. My usual process is CR, then checkout
PRs branch locally, testing it on my machine; when looks fine, I merge on
my local master, npm install if some change there, grunt build with linting
and only push the merge on success (or I rollback my local merge and
request changes at the PR). And I archive the branch.

So, Travis could help double checking this once I push, and is welcome.


---------


About warnings, some could happen (they are not errors), but this with a
lot of them was an exceptional case I shouldn't do; I just want to push
forward other changes and let start doing the changes for that rule. I
should have wait to enable that just in a branch and only merge when no
warnings. Too much rush.


-------------


By the way, please if something like that happens (unstable state or
errorsbor anything else), let me know immediately even if you want to check
it in your own (that's welcome), so we can support us. At this case, I
could have recommended the 'quiet' option to prevent the warnings so you
can focus on errors, or even choose to immediately off the rule throwing
them, understanding my fault so you have not to fix that warnings.


I'm learning from this errors and your opinions are very welcome, thanks.
no more rush on future merges to master.


(PS I'm traveling back to home still, may be not active next hours)

> --
Iago Lorenzo Salgueiro

**Comment by IagoSRL** [comment]
@ndarilek Since this looks fixed, I'm closing
