### ISSUE TITLE
Scrape External Listings

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#764]
## Epic Story
As a student, I'd like to learn about all the places I can list my services so I can earn as much as possible.

**Comment by joshdanielson** [comment]
@IagoSRL I'm going to list the final to-dos here in the epic just so they don't get lost:
- external-listing-add:
  - job title search is the client one (not professionals)...I think the same is for addJobTitles if I recall correctly.
  - nothing happens when clicking "Save"
- external-platform-info
  - I added "-" before each list

**Comment by IagoSRL** [comment]
Show this now sorry.
I uploaded back-end again to *dev*. **only back-end**, front-end must be tried on your local from the is764 branch. All should be working (save worked for me, but let me know if some console error).

I know for the job titles autocomplete I get the 'search' version (descriptions), can try enable the 'addJobTitle' mode but may trigger other unwanted behavior --may need a change in the component. Will be tomorrow (in some hours).

**Comment by joshdanielson** [comment]
Working now! Good on the autocomplete - let me know when you want me to test. 

I'm going to add some more platforms in the morning. Give me a deadline of when you want to release to live. I should be in pretty early. 

THANK YOU!

**Comment by IagoSRL** [comment]
I pushed changes into the branch. The autocomplete now has a 'professionals' target for this use case, show descriptions displays expected text while we don't allow user to create a job title.

I added a 'delete' button too in the editor, I keep it small, link-alike under 'save' but I'm not sold on the styling and placement.

**Comment by joshdanielson** [comment]
@IagoSRL added more external platforms on the dev database:

`INSERT INTO dbo.Platform (PlatformID, LanguageID, CountryID, Name, ShortDescription, LongDescription, FeesDescription, PositiveAspects, NegativeAspects, Advice, SignUpURL, SignInURL, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (8, 1, 1, N'Upwork', N'Marketplace for business services.', 'Online workplace where savvy businesses and professional freelancers go to work', '["20% for the first $500 billed with the client.", "10% for lifetime billings with the client between $500.01 and $10,000.", "5% for lifetime billings with the client that exceed $10,000."]', '["Freedom from the constraints of a 9-to-5 office job", "Potential to meet new clients"]', '["Time invested in building a reputation may not outweigh money earned through gigs."] ', '["Build a reputation by specializing your offerings and earning high ratings."] ', N'https://www.upwork.com/i/how-it-works/freelancer/', N'https://www.upwork.com/ab/account-security/login', '2018-02-05 00:00:00.0000000 +00:00', '2018-02-05 00:00:00 +00:00', N'jd', 1);
INSERT INTO dbo.Platform (PlatformID, LanguageID, CountryID, Name, ShortDescription, LongDescription, FeesDescription, PositiveAspects, NegativeAspects, Advice, SignUpURL, SignInURL, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (9, 1, 1, N'NextDoor', N'Online neighborhood community.', 'A way to stay in the know about what''s going on in your neighborhood', '["Free listings"]', '["Getting jobs through local references"]', '["Not a platform solely for jobs", "You must handle payments on your own"]', '["Review house-rules", "Treat it as a passive source of work", "Ask a client to refer you on Nextdoor after you''ve done a job."]', N'https://nextdoor.com/login/', N'https://nextdoor.com/login/', '2018-02-05 00:00:00.0000000 +00:00', '2018-02-05 00:00:00 +00:00', N'jd', 1);
INSERT INTO dbo.Platform (PlatformID, LanguageID, CountryID, Name, ShortDescription, LongDescription, FeesDescription, PositiveAspects, NegativeAspects, Advice, SignUpURL, SignInURL, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (10, 1, 1, N'Wag', N'App for dog walking and dog sitting.', 'Wag! is a dog walking app to book a dog walker on-demand, or at your convenience', '["Wag takes a 40 percent cut"]', '["Opportunity to build a client base, additional income, flexible schedule"]', '["40 percent cut in fees", "No info on the dog before you accept the walk"]', '["Take time to write your profile to set expectations"]', N'https://wagwalking.com/dog-walker', N'https://app.wagwalking.com/#/login/login', '2018-02-05 00:00:00.0000000 +00:00', '2018-02-05 00:00:00 +00:00', N'jd', 1);
INSERT INTO dbo.Platform (PlatformID, LanguageID, CountryID, Name, ShortDescription, LongDescription, FeesDescription, PositiveAspects, NegativeAspects, Advice, SignUpURL, SignInURL, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (11, 1, 1, N'Fiverr', N'Freelance services marketplace', 'A marketplace for lean entrepreneurs to focus on growth & create a successful business at affordable costs.', '["Fiverr keeps approximately $1 for every $5 gig (20%)","PayPal collects its small fee of a few cents for being the payment processor."]', '["Global demand"]', '["Low wage gigs", "Once Fiverr takes their cut you will have to wait 2 weeks from the gig completion date to be able to withdraw your balance."]', '["Only use for supplemental income"]', N'https://www.fiverr.com/start_selling', N'https://www.fiverr.com/login', '2018-02-05 00:00:00.0000000 +00:00', '2018-02-05 00:00:00 +00:00', N'jd', 1);
INSERT INTO dbo.Platform (PlatformID, LanguageID, CountryID, Name, ShortDescription, LongDescription, FeesDescription, PositiveAspects, NegativeAspects, Advice, SignUpURL, SignInURL, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (12, 1, 1, N'Wyzant', N'Find the right tutors. ', 'Meet with the expert of your choice, anywhere in the country', '["Wyzant takes 40% of the tutoring fee that you post, and in order to increase your earnings, you must work more hours.", "After you log 20 hours, they will take 35%.", "After 50 hours, they take 30% and with increasing increments of hours, you keep more money."]', '["Find the best fit for your location and schedule, in person or online."]', '["You''ll have to charge your students a lot more to compensate for the 40% tutoring fee."]', '["Find new clients on the platform", "Build a reputation"]', N'https://www.wyzant.com/signup', N'https://www.wyzant.com/login', '2018-02-05 00:00:00.0000000 +00:00', '2018-02-05 00:00:00 +00:00', N'jd', 1);
INSERT INTO dbo.Platform (PlatformID, LanguageID, CountryID, Name, ShortDescription, LongDescription, FeesDescription, PositiveAspects, NegativeAspects, Advice, SignUpURL, SignInURL, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (13, 1, 1, N'Craigslist', N'Craigslist provides local classifieds', 'A classified advertisements website with sections devoted to jobs, housing, personals, for sale, items wanted, services, community, gigs, résumés, and discussion forums', '["Free."] ', '["You can list your ad for free and take business off the platform"]', '["It''s a crowded marketplace", "You must handle payments on your own"]', '["Add photos to your ad to stand out"]', N'https://post.craigslist.org/', N'https://accounts.craigslist.org/login', '2018-02-05 00:00:00.0000000 +00:00', '2018-02-05 00:00:00 +00:00', N'jd', 1);
INSERT INTO dbo.Platform (PlatformID, LanguageID, CountryID, Name, ShortDescription, LongDescription, FeesDescription, PositiveAspects, NegativeAspects, Advice, SignUpURL, SignInURL, CreatedDate, UpdatedDate, ModifiedBy, Active) VALUES (14, 1, 1, N'Rover', N'App for dog walking and dog sitting.', 'Rover is a dog walking app to book a dog walker on-demand, or at your convenience', '["Rover takes a 40 percent cut"]', '["Opportunity to build a client base, additional income, flexible schedule"]', '["40 percent cut in fees", "No info on the dog before you accept the walk"]', '["Take time to write your profile to set expectations"]', N'https://www.rover.com/become-a-sitter/?bep=event%3Dnavigation-become-a-sitter&ref=header', N'https://www.rover.com/account/continue/?bep=event%3Dnavigation-sign-in&ref=header&action=sign_in&next=/become-a-sitter/%3Fbep%3Devent%253Dnavigation-become-a-sitter%26ref%3Dheader', '2018-02-05 00:00:00.0000000 +00:00', '2018-02-05 00:00:00 +00:00', N'jd', 1);
`
