### ISSUE TITLE
Bug S2: Education not being added to student listing

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#790]
## Steps to recreate
- Click on https://loconomics.com/welcome/california-community-college-students to sign up
- fill out sign-up form and initial onboarding
- no education is shown on /listingEditor
![screen shot 2018-02-05 at 5 31 35 pm](https://user-images.githubusercontent.com/1202838/35837474-2b3e9de6-0a9b-11e8-8f75-5ec59e60d16a.png)

**Comment by IagoSRL** [comment]
As of #791, lost tables makes the process fail early not reaching the point to register user-education. I tested and works. Closing but still, please @joshdanielson double check all the students landing too.
