### ISSUE TITLE
Bug S1: CCCUsers and FieldOfStudy tables missing

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#791]
## Information
- @IagoSRL I should have caught this obviously, but nothing is being recorded for the students (account plan, field of study, or education, or user type). The database is missing the new tables so there must be a branch not merged or something.

**Comment by IagoSRL** [comment]
Applied forgotten scripts (sorry!).
I tested creating a user (that I will remove, id:1480) and worked: CCCUsers has data, education has data, CCC plan was assigned.
Closing.
