### ISSUE TITLE
Create and populate new search database tables

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#801]
### To-do
- [x] SearchCategory
Holds the category names, descriptions, and images that show up on the home page and act as parent categories that solution sub categories are mapped to.
- [x] SearchSubCategory
Holds the sub category names, descriptions, and images that show up in each category page and act as a parent sub categories that solutions are mapped to.
- [x] Solution
Hold the solutions that offerings are mapped to. Includes flags for the need to check Credentials and requirement for a Background Check and a TaxActivityID
- [x] SearchSubCategorySolution
Maps solutions to sub categories. Some solutions may show up in multiple sub categories.
- [x] SearchCategorySearchSubCategory
- [x] Add relevant foreign keys for tables above

**Comment by joshdanielson** [comment]
@IagoSRL I just committed the SQL files to the epic branch and executed them on dev. FOREIGN KEYS have not been implemented. Assigning to you for review.

**Comment by IagoSRL** [comment]
The table from summary [SearchCategorySearchSubCategory] didn't exist anymore. Added FK scripts for all others (completes #802 too)
