### ISSUE TITLE
Map solutions to sub categories 

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#802]
### To-do
- [x] SolutionSubCategorySolution
Maps solutions to sub categories. Some solutions may show up in multiple sub categories.
- [x] Add relevant foreign keys

**Comment by joshdanielson** [comment]
@IagoSRL I just committed the SQL files to the epic branch and executed on the Dev database. Please review and add relevant foreign keys.

**Comment by IagoSRL** [comment]
Table [SolutionSubCategorySolution] is was lately renamed as [SearchSubCategorySolution].
FK scripts added.

**Comment by joshdanielson** [comment]
@IagoSRL I reviewed this in the dev database and all looks good (PKs, FKs, data). Not sure what other QA I can do. If none, you can close.
