### ISSUE TITLE
Add jobTitleID "-2" for user generated job titles

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#805]
## To-do
- [x] Add postionID = -2 to positions table as "User Generated"

**Comment by IagoSRL** [comment]
One concern that arise from this (and actually, any user generated position we are allowing already), is that we don't know if HIPAA rules apply or not.

Safest should be enable it as HIPAA, even if that prevents some useful detail in features, almost until is reviewed by us and creating a specific job title

**Comment by joshdanielson** [comment]
@IagoSRL I've included a IsHIPAA flag in the Solution table (along with credentials and background check) so that if a professional wants to offer a solution, no matter the job title, we review these flags. I know they're not implemented yet but I'm hoping we can refactor to use these instead of job titles.

**Comment by IagoSRL** [comment]
Too, other column defaults related that looks for me that the more conservative option is just the opposite:
- SuppressReviewOfClient: it's false now
- CanBeRemote: it's false now
- SendReviewReminderToClient: it's true now

(defaults for new records, has happens when user adding jbo title)

**Comment by IagoSRL** [comment]
(read now your comment Josh).

It's OK, so this -2 can be HIPAA=false (0) and all that will be taken care by solutions chosen. Makes kind of sense actually, more granulated control.

**Comment by IagoSRL** [comment]
I implemented like this, we can change the values at any time though
```sql
INSERT INTO [positions]
           ([PositionID]
           ,[LanguageID]
           ,[CountryID]
           ,[PositionSingular]
           ,[PositionPlural]
           ,[Aliases]
           ,[PositionDescription]
           ,[CreatedDate]
           ,[UpdatedDate]
           ,[ModifiedBy]
           ,[GovID]
           ,[GovPosition]
           ,[GovPositionDescription]
           ,[Active]
           ,[DisplayRank]
           ,[PositionSearchDescription]
           ,[AttributesComplete]
           ,[StarRatingsComplete]
           ,[PricingTypeComplete]
           ,[EnteredByUserID]
           ,[Approved]
           ,[AddGratuity]
           ,[HIPAA]
           ,[SendReviewReminderToClient]
           ,[CanBeRemote]
           ,[SuppressReviewOfClient])
     VALUES
           (-2
           ,1
           ,1
           ,'User Generated'
           ,'User Generated'
           ,null
           ,''
           ,'2018-03-02 20:36:00'
           ,'2018-03-02 20:36:00'
           ,'il'
           ,null
           ,null
           ,null
           ,1
           ,null
           ,null
           ,0
           ,0
           ,0
           ,null
           ,1
           ,0
           ,1
           ,1
           ,1
           ,0)

```

**Comment by joshdanielson** [comment]
@IagoSRL this looks good!!

**Comment by joshdanielson** [comment]
@IagoSRL tested and working. Closing.
