### ISSUE TITLE
Create static job title list for addJobTitleActivity

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#806]
## To-do
- [x] Create search table on front-end with aliases mapped to main jobTitleIDs

**Comment by IagoSRL** [comment]
@joshdanielson Do you have the "final" list for this somewhere?

**Comment by joshdanielson** [comment]
@IagoSRL I'm finishing this up today hopefully. I ended up going to the solution list and filling in new job titles we were missing (we didn't have many small business services one that CCC will need) and then going to back to the list. So the JobTitleSolution table will also then be done.

**Comment by joshdanielson** [comment]
@IagoSRL here is the list (not sure what format you need it in):

JobTitleID | JobTitleName
-- | --
3 | Pool Cleaner
12 | Bookkeeper
14 | Cleaning Professional
14 | Housecleaner
14 | Housekeeper
16 | Babysitter
17 | Nanny
18 | Daycare Provider
19 | Accountant
22 | Gardener
23 | Lawncare Specialist
25 | Security Guard
27 | Home Health Aide
28 | Personal Care Aide
30 | Auto Mechanic
31 | Lawyer
31 | Attorney
32 | Tutor
36 | Hairstylist
37 | Cosmetologist
38 | Hair Removal Specialist
39 | Bartender
50 | Telemarketer
53 | Personal Assistant
56 | Data Entry Specialist
57 | Public Relations Specialist
61 | Personal Trainer
63 | Laundry Worker
64 | Dry-Cleaner
72 | Caterer
73 | Musician
74 | Singer
76 | Dog Walker
77 | Pet Groomer
78 | Dog Sitter
82 | Handyman
84 | Pool Repairerer
87 | Auto Body Repairer
90 | Photographer
91 | Psychiatrist
92 | Baker
98 | Architect
106 | Massage Therapist
106 | Bodyworker
106 | Licensed Massage Therapist
106 | Certified Massage Therapist
120 | Tax Preparer
126 | Animator
128 | Floral Designer
130 | Manicurist
131 | Pedicurist
132 | Interior Designer
136 | Exterminator
141 | Nutritionist
144 | Veterinarian
145 | Clown
146 | Hypnotherapist
147 | Magician
148 | Psychic
149 | Astrologer
151 | Event Planner
152 | Wedding Planner
154 | AV Equipment Technician
155 | Tailor
156 | Dressmaker
161 | Barber
162 | Upholsterer
163 | Furniture Repairer
164 | Jeweler
168 | Translator
169 | Home Appliance Repairer
170 | Chiropractor
173 | Technical Writer
179 | Esthetician
179 | Aesthetician
182 | Career Counselor
185 | Acupuncturist
185 | Chinese Medicine Practioner
185 | Qigong Practioner
185 | Licensed Acupuncturist
186 | Life Coach
188 | Funeral Service Manager
193 | Psychotherapist
193 | Counselor
194 | Family Therapist
193 | Marriage and Family Therapist
198 | Videographer
206 | Illustrator
217 | Auto Electronics Installer
218 | Auto Electronics Repairer
219 | Auto Glass Installer
220 | Auto Glass Repairer
221 | Motorcycle Mechanic
222 | Copywriter
222 | Proofreader
224 | Athletic Trainer
229 | Chimney Sweeper
237 | Bicycle Repairer
245 | Chef
245 | Personal Chef
248 | Makeup Artist
251 | Disc Jockey
251 | DJ
252 | Emcee
254 | Computer Programmer
255 | Web Developer
256 | Network Administrator
259 | Funeral Director
265 | Printer
268 | House Sitter
269 | Music Teacher
270 | Tennis Instructor
273 | Cello Teacher
274 | Voice Coach
275 | Drum Teacher
277 | Guitar Teacher
278 | Yoga Instructor
279 | Reiki Master
281 | Pilates Instructor
283 | Reiki Practitioner
284 | Comedian
285 | Sound Healer
287 | Herbalist
290 | User Researcher
291 | UX Designer
296 | Art Tutor
303 | Dog Groomer
307 | Web Designer
308 | Graphic Designer
318 | Rolfer
325 | Brand Messaging Specialist
326 | Executive Assistant
332 | Wedding Officiant
346 | Cat Sitter
353 | Audio Engineer
364 | System Administrator
388 | Blogger
398 | Customer Service Representative
406 | Pet Sitter
407 | Phone Repair Specialist
408 | Cell Phone Technician
1001 | Air and Water Balancing Contractor
1002 | Asbestos Abatement Contractor
1003 | Awnings Contractor
1004 | Boiler, Hot Water Heating and Steam Fitting Contractor
1005 | Building Moving/Demolition Contractor
1006 | Cabinet, Millwork and Finish Carpentry Contractor
1007 | Central Vacuum Systems Contractor
1008 | Ceramic and Mosaic Tile Contractor
1009 | Certified Asbestos Contractor
1010 | Certified Hazardous Substance Removal Contractor
1011 | Concrete Contractor
1012 | Concrete Related Services Contractor
1013 | Construction Clean-up Contractor
1014 | Doors, Gates and Activating Devices Contractor
1015 | Drywall Contractor
1016 | Earthwork and Paving Contractors
1017 | Electrical Contractor
1018 | Elevated Floors Contractor
1019 | Elevator Contractor
1020 | Fencing Contractor
1021 | Fire Protection Contractor
1022 | Flooring and Floor Covering Contractors
1023 | Framing and Rough Carpentry Contractor
1024 | General Manufactured Housing Contractor
1025 | Glazing Contractor
1026 | Hardware, Locks and Safes Contractor
1027 | Hydroseed Spraying Contractor
1028 | Insulation and Acoustical Contractor
1029 | Landscaping Contractor
1030 | Lathing and Plastering Contractor
1031 | Lock and Security Equipment Contractor
1032 | Low Voltage Systems Contractor
1033 | Machinery and Pumps Contractor
1034 | Masonry Contractor
1035 | Metal Products Contractor
1037 | Ornamental Metal Contractor
1038 | Painting and Decorating Contractor
1039 | Paperhanging Contractor
1040 | Pile Driving and Pressure Foundation Jacking Contractor
1041 | Pipeline Contractor
1042 | Plumbing Contractor
1043 | Pole Installation and Maintenance Contractor
1044 | Pool and Spa Maintenance Contractor
1046 | Refrigeration Contractor
1047 | Reinforcing Steel Contractor
1048 | Roofing Contractor
1049 | Sand and Water Blasting Contractor
1050 | Sanitation System Contractor
1051 | Scaffolding Contractor
1053 | Sheet Metal Contractor
1054 | Siding and Decking Contractor
1055 | Sign Contractor
1056 | Solar Contractor
1058 | Structural Steel Contractor
1059 | Suspended Ceilings Contractor
1060 | Swimming Pool Contractor
1062 | Tree Service Contractor
1063 | Trenching Contractor
1064 | Warm-Air Heating, Ventilating and Air-Conditioning Contractor
1065 | Water Conditioning Contractor
1066 | Waterproofing and Weatherproofing (under relevant class) Contractor
1067 | Weatherization and Energy Conservation Contractor
1068 | Welding Contractor
1069 | Well Drilling Contractor
1070 | Window Coverings Contractor
1071 | Wood Tanks Contractor
1072 | Electronic and Appliance Service and Repair Contractor
1073 | General Engineering Contractor
1075 | Electrologist
1076 | Golf Instructor
1077 | Swimming Instructor
1078 | Nurse Midwife
1079 | Licensed Midwife
1080 | Doula
1081 | Cat Boarder
1082 | Pet Boarder
1083 | Server
1084 | Dance Instructor
1085 | Data and Analytics Manager
1086 | Cat Groomer
1087 | Dog Boarder
1088 | Account Executive
1089 | Account Manager
1090 | Content Marketing Manager
1091 | Content Strategist
1092 | Digital Marketing Analyst
1093 | Digital Marketing Manager
1094 | Digital Marketing Specialist
1095 | Marketing Coordinator
1096 | Marketing Manager
1097 | Marketing Specialist
1098 | Paid Search Specialist
1099 | Recruiter
1100 | SEO Manager
1101 | SEO Specialist
1102 | Social Media Manager
1103 | Social Media Specialist
1104 | Product Marketing Manager
1105 | Business Analyst
1106 | Database Administrator
1107 | Statistician
1109 | Data Architect
1110 | Data Analyst
1111 | Data Scientist
1112 | Business Intelligence Professional
1122 | UI Designer
1123 | UI/UX Designer
1123 | UI/UX Designer
1124 | Communication Designer
1125 | Visual Designer
1126 | Art Production Manager
1127 | Brand Identity Developer
1129 | Logo Designer
1131 | Production Designer
1132 | Production Artist
1134 | Motion Designer
1135 | Motion Graphics Designer
1136 | Multimedia Developer
1138 | Interface Designer
1143 | Event Coordinator
1144 | Event Manager
1150 | Human Resources Consultant
1151 | Management Consultant
1153 | Strategy Consultant
1154 | Transcriptionist
1155 | Web Researcher
1157 | Financial Analyst
1158 | Front End Developer
1159 | Front End Engineer
1160 | Back End Developer
1161 | Back End Engineer
1162 | JavaScript Developer
1163 | JavaScript Engineer
1164 | Interaction Designer
1165 | Full Stack Developer
1166 | Web Programmer
1167 | Web Application Developer
1168 | Information Architect
1169 | IT Technician
1170 | Dev Ops
1171 | Waiter
1172 | Catering Staff
1173 | Nail Technician
1174 | Dietician
1175 | Tasker
1176 | Errand Runner
1177 | Mother Helper
1178 | Mommy Helper
1179 | Product Manager
1180 | Project Manager
1181 | QA Engineer
1182 | Medium
1183 | Meditation Specialist
1184 | Brand Manager
1185 | Voice Artist
1186 | Writer
1187 | Grant Writer
1188 | Architectural Designer
1189 | CAD Designer
1190 | 3D Designer
1191 | Chemical Engineer
1192 | Structural Engineer
1193 | Electrical Engineer
1194 | Civil Engineer
1195 | Mechanical Engineer
1196 | Product Designer
1197 | Marketing Analyst
1198 | Event Decorator
1199 | Venue Coordinator
1200 | Fundraiser Event Planner
1201 | Smart Home Specialist
1202 | Home Tech Specialist
1203 | Mobile Specialist
1204 | Computer Support Specialist
1205 | TV Mounting Specialist
1206 | Audio and Video Specialist
1207 | WIfi and Network Specialist
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |

**Comment by IagoSRL** [comment]
Done this, is in the branch. I tweaked our textSearch util and it looks by words now, so results are better; it still founds partial matches, what I think is the best (doing full word matching is the same easy with the current approach but forces user to type exact full word).
For the same reason, I discarded to use the module [lunr](https://github.com/olivernn/lunr.js) ("A bit like Solr, but much smaller and not as bright") that wanted to use at first; didn't find how to change it for partial matches, and seems we don't need the level of performance that may provide.
By the way, with that util change, local inbox and clients search gets benefit with the same feature.
The matching of typed words can be to match all of them or any of them, I enabled the first one. Please give it a try

**Comment by joshdanielson** [comment]
@IagoSRL testing this and the textSearch works great. The old listings on /yourListings aren't showing up, though (The userprofilepositions table was empty (see screen shots). And the new listing (actually old job title and everything from the past is still there) then is showing "Marketplace Profile: ON" and is missing the job title name. 
![screen shot 2018-03-10 at 10 04 55 am](https://user-images.githubusercontent.com/1202838/37245292-c6736012-244a-11e8-8bb6-38cb98e6803b.png)
![screen shot 2018-03-10 at 10 04 40 am](https://user-images.githubusercontent.com/1202838/37245293-c69fde30-244a-11e8-8485-e731ec31fe73.png)

**Comment by IagoSRL** [comment]
@joshdanielson Did you applied the update scripts on *dev*? (I ask just in case, trying to now what happened and when)
Anyway, I copied data from the backup table so all positions for users are recovered at *dev*.

And about data for the position, it seems several related tables have not foreign keys properly, allowing to lost the main record without removing that ones (services/offerings and others), so they looks as 'recovered' after adding back the record and if they meet the activation rules, then is enabled by default. I reapplied the changes for the the new title field, because the upgrade process for the userListingID has not the field (happened before), so happens we had the back-end code uploaded but not the database change for 'title' so there was no name displayed for the job title. I re-uploaded this epic changes to *dev* just in case too.

Live db looks fine, all records in place (the userListingID change was applied there per latest release).

Remember that the updated autocomplete for job titles applies too to the home/search page and learnMoreProfessionals too. Descriptions are lost, per new set of data, but I think is not a big deal.

**Comment by joshdanielson** [comment]
@IagoSRL I didn't know I had to run any scripts so thanks for doing them. All the listings are back and the search is very fast. Here are some issues I found, though:
1. Adding a new job title still creates a new title (and ID) in the db:
![screen shot 2018-03-12 at 8 25 19 am](https://user-images.githubusercontent.com/1202838/37292789-ef5f8c8c-25ce-11e8-97e6-8c3cef5c6ee2.png)
![screen shot 2018-03-12 at 8 25 58 am](https://user-images.githubusercontent.com/1202838/37292830-0584782e-25cf-11e8-9da9-9572e528e4d5.png)

2. The new job title shows as null on the listing title
![screen shot 2018-03-12 at 8 23 20 am](https://user-images.githubusercontent.com/1202838/37292862-12f0984e-25cf-11e8-8480-1d08055916ce.png)

**Comment by IagoSRL** [comment]
The new job title depends on work at #832 were didn't comment about anything to test, but coming (this issue is about just the autocomplete).

No, no need to run the scripts, just thinking if you tried and doing it twice (I did it the other day) could have throw the problem with lost records; but seems was the other day when that happened without me noticing it.

**Comment by IagoSRL** [comment]
Closing
