### ISSUE TITLE
Partner Metrics

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#814]
## Epic Story
As a partner administrator, I want to be able to access the progress of the constituents who are part of the programs so I can measure success.

**Comment by joshdanielson** [comment]
@IagoSRL I just finished the first draft of the reports. It's pretty basic, which I think is fine for now. Let's discuss when you're ready to start: https://4jisn8.axshare.com/home.html

**Comment by joshdanielson** [comment]
@IagoSRL adding one last task:
- [ ] Add a button on the main reports page "Request Custom Report" that opens up the contact us page with a pop-up that says "Please describe the data you're looking for, and we'll create a report for you."

**Comment by joshdanielson** [comment]
@IagoSRL reposting my comment from Slack here: 

> so in the live db, the userType is ‘administrator’…in theory, we should have a manual process to approve who is an administrator but for now it’s obviously not an issue.

**Comment by joshdanielson** [comment]
@IagoSRL also getting this error when click on earnings report. The user should NOT need to be a service professional (only admin user type).
![screen shot 2018-06-21 at 9 39 46 am](https://user-images.githubusercontent.com/1202838/41732975-69f0a7da-7537-11e8-9fb3-4f31aac5b50d.png)

**Comment by IagoSRL** [comment]
@joshdanielson  I pushed update to branch (and backend changes to dev); That fixes your latest error, that was related to what I commented at Slack of using initially the earnings-filters component created for user earnings reports, but now uses a specialized earnings-admin-fitlers so don't request ressources of professional-only, and makes a full list of platforms and job titles.

**Comment by IagoSRL** [comment]
ops, sorry, didn't remember platforms was protected too. Used the API of platforms for the user, will do a full public list available.

**Comment by IagoSRL** [comment]
Pushed fix, new REST API for all registered platforms and used here

**Comment by joshdanielson** [comment]
@iagosrl looks fixed! I'll add the labels this afternoon.

**Comment by IagoSRL** [comment]
One important note: right now, data for CCC Colleges (institutions) and list of fields of study is embedded in the app (under /app/source/js/data/embedded/) rather than requested to REST API; this last needs to be created and connected, but as first step and being few data, is fine as is (just remember in case data wants to be updated).

**Comment by joshdanielson** [comment]
@iagosrl testing on the local branch and getting this error:
![screen shot 2018-06-22 at 7 24 16 am](https://user-images.githubusercontent.com/1202838/41782154-4dc0afd0-75ee-11e8-8664-c4c84f6fa8ef.png)

**Comment by IagoSRL** [comment]
Thought I left out a commit to push to *dev*, try now the error should disappear.

**Comment by joshdanielson** [comment]
@iagosrl getting an error loading the dev site (and also merge conflicts when pulling to local...have to leave soon so can't resolve):
![screen shot 2018-06-22 at 8 06 26 am](https://user-images.githubusercontent.com/1202838/41784009-429eaad0-75f3-11e8-83c9-ff4377de7d47.png)

**Comment by IagoSRL** [comment]
Pushed most files to *dev* to fix the problem with not uploaded files. errors should get fixed

**Comment by joshdanielson** [comment]
@IagoSRL tested this and found some things:
- not sure all earnings are being captured correctly (look at userID 1494 who should have $3130:
`select sum(serviceProfessionalPaid)
from booking
where
serviceprofessionaluserid=1494`
- the download csv buttons don't work (and don't understand the difference...should be"Download Summary (.csv)" and "Download Details (.csv)"
- This [commit](https://github.com/loconomics/loconomics/commit/1936d8ae373e2f1f3ba1df5ad7ad66e346a2c749) wasn't pushed (all minor but please review).

**Comment by IagoSRL** [comment]
- It's using data only from userEarningsEntry table so bookings are not accounting, will add (or should we automatically add booking totals as earnings entries for Loconomics platform?). We have this question open at #830.
- OK about buttons naming, makes sense that way. It worked to me but will do further testing.
- About the copy fixes commit, as I commented on it there were problems with the branchs naming and now is at another branch, waiting for release.

**Comment by IagoSRL** [comment]
Found and fixed the download buttons bug (only happened when hosted, if run on dev env worked), updated labels. Released to *live*.

**Comment by IagoSRL** [comment]
@joshdanielson 3 issues where in QA here and in *live* for a while, so I closed, and closing this Epic
