### ISSUE TITLE
Bug S1: Error Saving Bank Account Details

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#82]
From userID: 1256:

Hi Josh, I was unable to complete my profile "Error saving bank payment account" Error of Type Braintree. Let me know when the next meetup is scheduled!

**Comment by joshdanielson** [comment]
@IagoSRL just checking Braintree and no account was created. The last successful one was userID 1239 created 24Oct.

**Comment by IagoSRL** [comment]
At *live*, right?

**Comment by joshdanielson** [comment]
@IagoSRL yes, sorry. I will only label it if it's Dev if that's okay. So assume Live.

**Comment by IagoSRL** [comment]
Was a settings error: when we changed from file-based to Azure settings, a key for Braintree was forgotten and other had an old value. Now is working (my attempt returned a 'bad street address' from Braintree but that means that Braintree stopped sending 'not found' or 'unauthorized' errors, that means settings OK).

If you can double check, the best, like going to your account, payment account and saving.

**Comment by joshdanielson** [comment]
@IagoSRL tested and working. Closing.
