### ISSUE TITLE
Persist authorization tokens

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#827]
### Context
In our current back-end, we have implemented the authorization tokens by reusing a feature from Release-6 epoch called 'autologin', created for links in emails. That computes the token based on an length-limited encrypted version of the stored encrypted password (two different encryptions applied), and it computes the second encryption each time an authenticated request is processed.
To encrypt on every request seems not suitable for performance and to share the authentication with the new back-end (since it should apply the exact same encryption or will fail verifying the token); from what I checked out, this way we encrypt on each request doesn't introduces any additional security, since just anyone having the token is enough to get authenticated, but means extra server work and compatibility between back-ends).

So, we should persist the token at database, along with userID, and compare any value given in a request with that (anyway, the current strategy is already querying the database for the same thing on every request).

### Current Authorization header scheme
The current token is used along with the userID as value for the `Authorization` header, with next scheme  `LC alu=userIdInteger,alk=token` (matches regular expression `^LC alu=([^,]+),alk=(.+)$`).
It's a pair of alu and alk values, rather than single token.

### Compatible but unique token
The stored token must be unique, so each one just matches a single userID; we can store a computed token that uses the userID as part of it, additionally to password (or other auto uuid), so the new authorization scheme can be as simple as just a token, while we can keep the current tokens out there and scheme compatible by using the same generation as before (and updating it, mostly to support App distributed through App stores in the meanwhile they are updated).

### Database
Proposed table `authorizations` with UserID and Token columns, being the Token unique and the primary key. As usual we store CreatedDate, that could help to allow for token expiration.

### Operations
Token must be stored at login and removed at logout operations; too, must get renewed on password change.

### New Authorization header scheme
Just type and token, `Authorization: Bearer sF323sdvxj3kl-vxsd0dDxPf899`

*note: Token or Bearer keyword?* **Update:** implemented 'Bearer' per comments.

### Query string
The original implementation used query string parameters (alk and alu), since the requests needing that 'autologin' feature where just clickable links, so headers cannot be set.

We can implement an `access_token` (or `auth_token`?) query string, to still support cases that don't allow setting headers, like that links (if still in use), images protected being displayed (headers cannot be set as part of an `<img src>`).
**Update:** implemented access_token rather than auth_token, without limitations now.

The header must ever take precedence if both, header and query string are included.

We can limit the query string to GET requests if there are concerns for security. *note: or even a different token, scoped to just read-only (GET)?*.

We can try to use the query string to prevent CORS preflight requests that slow down every authenticated communication with the server (almost all of them!). About the restriction to GET requests, this may be enough, since other type of requests are less frequent and are expected to take some times. As use cases, loading data happens a lot and the server autocomplete APIs needs to be very, very fast to provide a good user experience.

**Comment by ndarilek** [comment]
Let's use bearer tokens. And, yes, they can be entirely opaque. No need 
to do any complicated hashing scheme. We may in the future switch to a 
self-describing token that bakes in ACLs, but for now let's just stay 
opaque.

**Comment by joshdanielson** [comment]
@IagoSRL @ndarilek I created a new issue #828 to create a UserSession table to store session information for users. This may be able to be done in conjunction with this issue.

**Comment by ndarilek** [comment]
I'd like to hold off on it for now. I feel like migrating backends is 
complicated enough without having to introduce significant new changes 
into the flow. I.e. new endpoints are fine, but I'm not yet confident 
enough with this framework to track session metrics. I'm sure it can be 
done, but let's walk before we run. :)

**Comment by IagoSRL** [comment]
I agree @ndarilek, I implemented this and changed to Bearer.
I had already implemented the token using the previous generation code but good to know more opinions; when redoing it in the new back-end we can do it that way, along with authorization per login.
To clarify this last, the table is done with the token as primary key, so can have several records for the same userID; the idea is that every login creates a new authorization for the user attached to device/browser, and removed (or marked as removed) on logout, rather than current way where is an authorization per user on any device. That is actually the 'standard' way of doing this things, right?.
I could have did it but just don't want to put more code that will be replaced soon in the new back-end, so follow-up issues should be created for migrating this, including that behavior.
For the client app is the same because it just reads the token as returned by the login call and uses that until a logout, so doesn't matters how is stored or generated while the scheme keeps the same.

**Comment by joshdanielson** [comment]
@IagoSRL @ndarilek that's fair :)

**Comment by IagoSRL** [comment]
That's reasonable @ndarilek, step by step. But once is migrated and stable, we can do that changes there. Of course, another issue for the migration of this things. For now, as of the new back-end, the only thing is to support the authorization header with the Bearer token, and the query string parameter ('access_token' I guess is more usual name for it) for cases that require it.

**Comment by ndarilek** [comment]
Can we just use a monotonically increasing integer id as primary key for 
now, then enforce uniqueness on the token value? I'm having a bit of 
trouble finding in LoopBack where we might manage deviating from that 
pattern, so for now it would help if we stuck with it. I'm sure it can 
be done, I just don't immediately see how.

Thanks!

**Comment by IagoSRL** [comment]
Well, since right you only need to query the table, should be fine as is (I am NOT asking to implement sign-up, log-in, log-out in the new back-end for now). If there are still LoopBack problems with that when migrating that part, we can add the autoincremental field then, no problem.

So, code to check the header, as in:
```js
// This code goes in a Connect/Express middleware, where `req` is the request object
/**
 * @param {Object} req Connect/Express Request instance.
 * @returns {string} The authorization token, or null if no one or unknown format
 */
function getTokenFromRequest(req) {
    const authorization = req.get('Authorization') || req.query.access_token || '';
    const matches = /^Bearer (.+)$/.exec(authorization);
    return matches ? matches[1] : null;
}
```

The SQL query just something like (don't know the parameters syntax at Loopback, using '@token' here)
```sql
SELECT UserID FROM authorizations WHERE token like @token
```

Then you have a UserID, and you know is authenticated; or no value if token is not valid.

**Comment by ndarilek** [comment]
When you create the new table, I plan on exporting it to LoopBack's 
schema to start creating an in-code system for migrations. From that 
perspective, I'd like to stick with how LoopBack conceptualizes a model 
which, at the moment, I feel is safest with an integer id as primary 
key. I'm also fairly confident I know how to look up the tokens--the 
concern here is playing to LoopBack's strengths as I now understand them 
as to minimize migration friction.

Thanks.

**Comment by IagoSRL** [comment]
OK, adding it now to my script since I didn't push it to *dev* still. All needed changes are in this issue branch already (there is some detail I want to change but didn't affects you).

Sorry, I know you know how to do it, just being as clear as possible for the details giving that simple piece of code (copy&paste current back-end actually), sorry it that comment feels like a different thing, there is no more intention that keep things clear.

**Comment by ndarilek** [comment]
No worries, I wasn't offended, I just wanted to be clear that my intent 
was to keep us as close to LoopBack's concept of a model. Their docs are 
good, but there are a few dusty corners, like how to handle models that 
lack an id field. :)

**Comment by IagoSRL** [comment]
@ndarilek I did the table schema change for the ID, and to address part of #828 already, added DeletedDate column that should be null for valid tokens.
I use that field already, changing actual deletion with soft-delete by populating that column, so part of #828 is done with last commit here.

FYI: the table has a Scope column too, not null but empty for now since can be useful at some point to limit some access / third party acceses (OAuth maybe)

**Comment by IagoSRL** [comment]
I will have to check LoopBack but cannot now. Even without touching it, I don't know if adds more required artifacts than solving problems (aside from some curated selection of modules and set-up in other terms). I had some bad experience in the past with large frameworks (a specific example for Nodejs was Krakenjs, by Paypal, was enforcing more complexity than I actually needed for a project, I simplified a lot by removing that --but may be different cases.)

**Comment by IagoSRL** [comment]
I completed some details and updated initial comment with relevant details:
- using 'Bearer' to denote the authorization scheme rather than Token
- implemented 'access_token' in query string, to support commented cases. No restrictions, but can be added.
- token generated based on GUID rather than password; but still using the userID as text to encrypt and then sanitize for safe URL usage and the result being the token. Maybe is not needed, just in case and is just the same previous code so not time spent on that actually.
- implemented token per login rather than per account (changed my mind about left this for later after found some issues with that).

**Comment by IagoSRL** [comment]
Pushed this to *dev* and moved to QA pipeline.

**Comment by IagoSRL** [comment]
@ndarilek I just renamed AuthorizationID to just `id` for Loopback.
Not sure why requires to query by the autogenerated ID since the only what I needed implementing this at the current back-end, was to query by token, but is done. Closing and pushing to live.
