### ISSUE TITLE
Replace usage of positions names by new userprofilepositions title field

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#831]
As of haulting the ability for users to create new job title IDs, then having it's own custom 'title' for their listing, we must display the value from that new field everywhere in the App (maybe some points of the REST API) rather than PositionSingular or PositionPlural from the positions table (AKA job titles).

**Comment by IagoSRL** [comment]
Actually, the REST API must return the new title field as of the user listing data (public and private)

**Comment by IagoSRL** [comment]
This is ready for QA:
- The REST API /me/user-job-profile, /users, /users/job-profile returns a title property for each UserJobTitle/PublicUserJobTitle record, directly from [userprofilepositions] table.
  - The `jobTitleSingularName` and `jobTitlePluralName` properties of UserJobTitle/PublicUserJobTitle were deprecated; will need clean-up after the stores App is updated.
- The App uses now the title field (from userListings, userJobProfile, UserJobTitle Model) rather than `jobTitle.jobTitleSingularName`.
  - The App codes simplifies lot of places by not needing to use the jobTitles data module to fetch a single record with the name (done before the names were added to the returned userJobTitle record), meaning better performance and more clear code.
  - Some internal APIs and helpers (at userJobProfile and some models) were removed since are not needed (and not recommended) anymore
  - Services still need a pair of getJobTitle(s) APIs, discovering another thing that would break with '-2' job titles if not updated: pricing types are fetched by job-title, and the job-title will not return any data for -2, failing to allow pricing/offerings for new custom job-titles/listings. -> Proposal is to add fetching pricingTypes by jobTitleID (and allow -2 there) to the /pricing-types API (that actually makes more sense even for previous code: one request rather than two sequential ones, and less client code), until the offerings is changed completely by solutions (should be quick).

There were lot of changes in lot of places, I used the new data modules where possible to fetch the user listing, meaning better code and faster loading data at several points, thanks to the new cache on that data modules.

**Comment by IagoSRL** [comment]
I had to do one more change related to this, as found at #833, the viewmodels/UserJobProfile  class was still using job title name rather than listing title. With the change, comes more code simplification, and even found I could change the usage of userJobProfile data module with the new userListing (underneath is the same REST API, but the module uses a better local cache), because of that all usages of the legacy component app-job-titles-list renders the UI faster; immediately with cached data after first use, and this is very perceivable because that is the top element at /listings, where even with a fast connection a loading spinner+empty area and jump in content after the load happened ever, now it shows instant.

**Comment by joshdanielson** [comment]
@IagoSRL I checked the references in the app and didn't find any but did see references to JobTitleSingularName on the server in a few places, especially messaging. We can prioritize these updates until after the ccc deadline (I made a new pipeline). Move to there if you agree.

**Comment by IagoSRL** [comment]
True! Forgot completely, was easy to replace so I did it already. There are some occurrences still there, but just for compatibility with the App released up there (once it is replaced, this latest can be removed). not uploaded but pushed

**Comment by IagoSRL** [comment]
Uploaded that changes

**Comment by IagoSRL** [comment]
Verified that the change at email templates worked fine (after a frustration time no remembering that HIPAA did not display the title). Closing
