### ISSUE TITLE
Update add-listing process to include a value for the new title field

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#832]
### Long Description
As of #804 we added automatic filling the title field for existent records based on positions.PositionSingular. Every new entry must do that too, relying on the text from the selected jobTitleID or the given user text for -2 ID.

### Discard user generated positions
This issue implies the main target of the epic, replace the code that up to now created a new [positions] record using user data by just using the text given by the user as the title and link to jobTitleID=-2, discarding all code that generated a new job title/position.

**Comment by IagoSRL** [comment]
Pushed this implementation to *dev*, but didn't reviewed the message when duplication happens

**Comment by joshdanielson** [comment]
@IagoSRL tested with a new job title and it successfully created it as -2 and all looks good on the the listing. Not sure what you mean by the duplication.

**Comment by IagoSRL** [comment]
I meant, there is an error if user try to add a job title twice, while that's not usual when selecting a job title is easier when typing their own name; we commented this is a limitation we can have now (will change when we adopt the new userListingID everywhere). I did this now and a clear error message is returned now (before was an internal error message cryptic for users).
With this, all this epic should be done, if no bugs

**Comment by joshdanielson** [comment]
@IagoSRL the error message (less cryptic one) does seem to be committed yet. I did a pull and the last commit was 4 hours ago.

**Comment by IagoSRL** [comment]
sorry, pushed now; but was at *dev* FTP already

**Comment by IagoSRL** [comment]
(it's a server change only)

**Comment by joshdanielson** [comment]
Still getting the cryptic message.
![screen shot 2018-03-12 at 1 51 59 pm](https://user-images.githubusercontent.com/1202838/37309033-e5f542bc-25fc-11e8-8189-923004b929d3.png)

**Comment by joshdanielson** [comment]
@IagoSRL I revised the error messages in the last commit. They have NOT been uploaded to the server.

**Comment by IagoSRL** [comment]
Hi @joshdanielson, it is uploaded, an actually that is a new message, but the one for the case duplication happens with a job title we have already registered (rather than a custom one). When duplication happens because of a second custom name you get this:
![screenshot-2018-3-13 create a new listing - loconomics](https://user-images.githubusercontent.com/1070576/37346018-9e1101c0-26ce-11e8-81ed-2f5568eab628.png)

*Note: * the large and cryptic Technical Details section should not appear on *live*, just on *dev* and local in case needs debugging (it's a global setting for any error thrown).


*Note 2:* I implemented a full match search when users type a custom title, without choose from the list, but that title matches a job title that exists (by singular or plural name, it must match the exact same text).

**Comment by IagoSRL** [comment]
I saw now you did a change too, uploaded now with latest #832 changes

**Comment by joshdanielson** [comment]
@IagoSRL that makes sense now. I just tested adding a duplicate (and worked). I also added "Handyworker", which apparently I had deleted some time ago, and got the "You already have that job title" error. I think before it would reactivate the job title. Not really that important given the priorities...should I add a new issue for it?

**Comment by joshdanielson** [comment]
@IagoSRL oh, and the add job title field cache doesn't appear to ever clear (stays on the last one when navigating away and back)

**Comment by joshdanielson** [comment]
@IagoSRL and finally, if it's actually easy, I think we should change the "Add" button to "Create" on the dropdown and move them to the next step. It seems unnecessary to have them click "create" after having just clicked "Add". I think we had it when we could add more than one. Again, if not actually easy, we'll let it go for now.

**Comment by IagoSRL** [comment]
I saw latest but didn't try (should be quick), it comes from before though.
About reactivation...I think so but don't see how the change I did could have changed that. Please, an issue

**Comment by IagoSRL** [comment]
Agree with latest, I can do and the other clean-up  together

**Comment by IagoSRL** [comment]
Done that last commented details:
- Using 'create' in the button
- Auto save on selecting an option
- Clean-up last selected title

it's on the branch only

**Comment by joshdanielson** [comment]
@IagoSRL tested all those and working well!
