### ISSUE TITLE
Bug S1: Booking Requests expiring too soon

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#834]
### Bug Description
User 1510 booked professional 1319 yesterday at 2018-03-04 19:06:41.69 and it expired at Mon, Mar 5, 2018 at 6:00 AM (pacific)....looks like it was 19 hours. So it may be set to 18 hours. Let's set it to 72 hours just to be safe for now.

**Comment by joshdanielson** [comment]
The professional says the more, the better with a reminder. So expires at 72 hours with reminders at 24 hours, 48 hours, and 70 hours (obviously if it hasn't been accepted already).

**Comment by IagoSRL** [comment]
Yes, current set-up is 18 hours, in code:
```C#
        public const int ConfirmationLimitInHours = 18;
```

increasing to 72 hours

**Comment by IagoSRL** [comment]
I updated that and pushed to *live*. in a branch from last release tag.

Just the time change, no reminders implemented

**Comment by IagoSRL** [comment]
Did a quick search and didn't find a reference in plain text about the 24 hours limit time, but a dynamic date calculated using the  ConfirmationLimitInHours constant used at emails to notify users about the limit time for expiration.

**Comment by joshdanielson** [comment]
@iagosrl great! I'll open a new issue for the reminders. Closing.
