### ISSUE TITLE
Review the three additionalinfoX colums at userprofilepositions

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#837]
### Long Description
In a quick search at the code, there are not references to the fields additionalinfo1, additionalinfo2 and additionalinfo3 that exists at the userprofilepositions table.

With next SQL query, we can check that there is not data at that fields
```sql
select len(additionalinfo1) as a1, len(additionalinfo2) as a2, len(additionalinfo3) as a3
from userprofilepositions
```
I run that against dev, live and my local dev, no data at all.

### Proposal
To remove it, please @joshdanielson let me know if there something I forgot about this fields, but I'm pretty sure can be removed.

**Comment by joshdanielson** [comment]
@iagosrl yes, remove them

**Comment by IagoSRL** [comment]
Done, in master, applied to local and *dev*.
