### ISSUE TITLE
Dev Site Bug S1: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#84]
@IagoSRL this happened when trying to make a booking here after entering payment info and clicking the last "Confirm":
http://dev.loconomics.com/#!booking/540/106
![screen shot 2016-12-13 at 4 34 37 pm](https://cloud.githubusercontent.com/assets/1202838/21165112/1500e6e4-c152-11e6-8420-07dd49b77db3.png)

The request was aborted: Could not create SSL/TLS secure channel.

Technical details: {"errorMessage":"The request was aborted: Could not create SSL/TLS secure channel.","exception":{"ClassName":"System.Net.WebException","Message":"The request was aborted: Could not create SSL/TLS secure channel.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":" at LcRest.Booking.CollectPayment(InputPaymentMethod paymentData, Boolean savePayment) in d:\\home\\site\\wwwroot\\App_Code\\LcRest\\Booking.cs:line 1705\r\n at ASP._Page_api_v1_me_client_booking_cshtml.RestMeClientBooking.CreateItem() in d:\\home\\site\\wwwroot\\api\\v1\\me\\client-booking.cshtml:line 391\r\n at ASP._Page_api_v1_me_client_booking_cshtml.RestMeClientBooking.Post() in d:\\home\\site\\wwwroot\\api\\v1\\me\\client-booking.cshtml:line 123\r\n at RestWebPage.Run(WebPage WebPage) in d:\\home\\site\\wwwroot\\App_Code\\RestWebPage.cs:line 139","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":"8\nCollectPayment\nApp_Code.vxq0djd7, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null\nLcRest.Booking\nSystem.Collections.Generic.Dictionary`2[System.String,System.String] CollectPayment(InputPaymentMethod, Boolean)","HResult":-2146233079,"Source":"App_Code.vxq0djd7","WatsonBuckets":null}}

**Comment by joshdanielson** [comment]
@IagoSRL I did a booking on the live site and this is NOT happening there (I did a $1.00 booking).

**Comment by IagoSRL** [comment]
Get's fixed with #87, tested on *dev*
