### ISSUE TITLE
Clean-up of unused and problemating elements at /listings activity

### ISSUE THREAD

**Issue by IagoSRL** [loconomics/loconomics#843]
### Long Description
Found when testing, the listings activity loads more things than needed, has wrong access control and unneeded data modules, can receive a quick clean-up

**Comment by IagoSRL** [comment]
Done and converted into a new-pattern activity. It fixed unneeded complexity and a "random" bug.

**Comment by joshdanielson** [comment]
@IagoSRL tested and closing.
