### ISSUE TITLE
Bug S1: Errors when loading /clientEditor

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#856]
### Bug Description
When loading /clientEditor, a couple bugs appear. Here they are:

- Error message (this was a student loading her client):
![screen shot 2018-04-05 at 9 56 55 am](https://user-images.githubusercontent.com/1202838/38382003-6e8476ac-38bd-11e8-9c6e-64a27a0d8e22.png)
- When I click on a client of mine, I get this message if I want to add them even though they're already added:
![screen shot 2018-04-05 at 10 24 54 am](https://user-images.githubusercontent.com/1202838/38382036-89f39a6c-38bd-11e8-871a-7873855dfe0d.png)
- When looking at the student's screen, she was unable to scroll down to special pricing but was able to reload and see it (not sure why she couldn't without.

**Comment by joshdanielson** [comment]
@IagoSRL my user on dev is 770 and the client it happens on is 551. The CreatedByBookingID is null so not sure that's it for this case.

**Comment by IagoSRL** [comment]
Uploaded a fix from the front-end to *master*. On my example user, where I recreated the problem, get fixed. The code change was small and clear (again) so confident enough to push it directly

**Comment by joshdanielson** [comment]
@IagoSRL awesome, thank you!

**Comment by IagoSRL** [comment]
The second problem, asking to add the user, it seems to happens because the same exact mobile number is found at another records (a lot of another ones), so it think should get 'combined'

**Comment by IagoSRL** [comment]
The last thing, about scroll, should not work as of the binding failed; should not even after reloading, except if navigates to another activity then is fine that works after reload

**Comment by joshdanielson** [comment]
Ahhhh....disregard then for now. I don’t think it should be an issue, at least yet, for the average user.

**Comment by IagoSRL** [comment]
Tried to fix the returning of offerings for removed positions but get's a bit more tricky than expected. the front-end solution is enough though, I'm building for release

**Comment by IagoSRL** [comment]
Released! As webapp v 1.9.6.

Please confirm with her and close if fine, or give some detail (maybe through Slack, as userID)

**Comment by IagoSRL** [comment]
This was apparently fixed with no news from the reporter, I will close but @joshdanielson let me know if you get some info from her.
