### ISSUE TITLE
Bug S2: Error loading calendar

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#860]
### Long Description
@IagoSRL this may be a side effect of the calendar import changes last week. When clicking on Calendar, I have a "busy" event (it appears) that would be an imported event. The event details do not show, and I can't click any other links. After clicking the Back button and then clicking on calendar again, I get an error "
TypeError: Cannot read property 'length' of undefined". Attached are screen shots with the console errors:
![screen shot 2018-04-10 at 11 14 57 am](https://user-images.githubusercontent.com/1202838/38575575-918bb0d8-3cb0-11e8-97cf-66d805ec6a5d.png)
![screen shot 2018-04-10 at 11 15 14 am](https://user-images.githubusercontent.com/1202838/38575585-975b258e-3cb0-11e8-9f0d-7a0280456baf.png)

**Comment by joshdanielson** [comment]
@IagoSRL another issue from the same user who says the events she makes in her phone calendar are showing up 8 hours earlier:
"Hey josh, I was wondering why on my Loconomics calendar the times are all off? For example I made an appointment on my phone for 4:30pm and on  loconomics it comes in at 9:30am. Do I need to set a clock?"

**Comment by IagoSRL** [comment]
Pushed fix for this, *dev* and *live*, and forced an execution of the scheduled task soon after (no errors). Please check data/times!

**Comment by joshdanielson** [comment]
@IagoSRL sorry for the slow response. I updated my calendar link on my dev account (user 540), ran the scheduled task, and then reloaded my calendar and seem to be getting the same errors. It does seem to import events but not all of them.
![screen shot 2018-04-20 at 9 02 50 am](https://user-images.githubusercontent.com/1202838/39061705-0a814450-447a-11e8-9592-850b739db873.png)
![screen shot 2018-04-20 at 9 03 13 am](https://user-images.githubusercontent.com/1202838/39061706-0a9cea48-447a-11e8-8f6c-2f25fc699844.png)
![screen shot 2018-04-20 at 9 04 12 am](https://user-images.githubusercontent.com/1202838/39061707-0ab8fc9c-447a-11e8-9071-1792775ab7d3.png)
![screen shot 2018-04-20 at 9 04 23 am](https://user-images.githubusercontent.com/1202838/39061708-0ad92a1c-447a-11e8-9970-30f54cd0ce94.png)

**Comment by IagoSRL** [comment]
Pushed a fix for a front-end error, but the message I got was different so looks different to that one. Please test (it's on *live* and *dev* already). I was unable to reproduce the exact source error from the screenshots.

**Comment by IagoSRL** [comment]
Weird the (very) different error message we were getting...may depend on the data that could be different now, but if is not reproducible now we can close it, keeping and eye open on calendar (testing it more frequently) in case it reappears.

**Comment by joshdanielson** [comment]
Closing as fix has been confirmed by the user.
