### ISSUE TITLE
Revise About Us format

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#868]
To look something like this:
![screen shot 2018-06-13 at 2 20 29 pm](https://user-images.githubusercontent.com/1202838/41378788-09bdc6e0-6f15-11e8-81a5-8b10b80cf8bd.png)

**Comment by IagoSRL** [comment]
@joshdanielson Closing this since this re-design was being covered at the loconomics-pages repo and it's own issue.
