### ISSUE TITLE
Bug S1 Live: Sign up from ccc student landing page not recorded in cccUsers

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#873]
### Bug Description
When signing up as an administrator, two bugs occurred:
- I was asked to create a listing (neither professors nor administrators should go through these steps)
- my user (1689) was not recorded in the CCCUsers table

**Comment by IagoSRL** [comment]
The first was by design, though on students, would change. The second I don't know, was looking as OK but will review.

**Comment by IagoSRL** [comment]
Fixed and published. I tested in local. Please double check on live.

**Comment by joshdanielson** [comment]
@iagosrl tested this on live and fixed.
