### ISSUE TITLE
Bug S1 Live Site: Error Loading availability when booking

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#874]
### Steps to reproduce:
1. go to book professional: https://loconomics.com/#!booking/1186/308
2. select service, address
3. click on calendar and error message appears:
![screen shot 2018-06-29 at 9 57 22 pm](https://user-images.githubusercontent.com/1202838/42121659-efa64306-7be7-11e8-84df-7df5681f22fc.png)

**Comment by joshdanielson** [comment]
@IagoSRL doesn't seem to be all users FYI.

**Comment by joshdanielson** [comment]
Another one: https://loconomics.com/#!booking/1051/255
![screen shot 2018-06-29 at 10 06 27 pm](https://user-images.githubusercontent.com/1202838/42121707-c79f5dd8-7be8-11e8-8e04-410ec93e0e9e.png)

**Comment by IagoSRL** [comment]
The source problem comes from getting the type of availability of some events, on my checks all 'weekly schedule' events (not sure if a coincidence or the unique type of events that caused it), where a nested property holding that info was unexpectedly null; another variable for "the same value" can be checked, I change it and uploaded as a quick test on *live* and **the big error screen has gone**.
Still need to check that the availability computed remains correct with this change (in theory should be, but need to do some checks just in case).

**Comment by IagoSRL** [comment]
Did some extra check and this seems fixed, but please @joshdanielson give it a try and close if goes fine to you too.

**Comment by IagoSRL** [comment]
This seems completely fixed, closing
