### ISSUE TITLE
Show client info in booking request and emails

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#876]
### User Story
As a service professional, I'd like to have a client's contact information when they make a booking request so that I can reach out to them directly before "denying" their request as it's more professional.

#### To-do's:
- [x] Include client contact info in booking request email (same format as in a confirmed booking)
- [x] Include client contact info in booking request card (same format as in a confirmed booking)

**Comment by IagoSRL** [comment]
@joshdanielson I updated email templates to include the client info for next templates:
- BookingReminder
- BookingRequestConfirmed
- BookingReqeustSummary
- BookingUpdatedByClient
- BookingUpdatedByServiceProfessional
- InstantBookingConfirmed

That applies to folders `BookNow/ToServiceProfessional`, `Marketplace/ToServiceProfessional` and `ServiceProfessionalBooking/ToServiceProfessional` (on this last, only the BookingUpdatdByClient template --it has fewer templates and communications this folder).

I uploaded to *dev* for testing.

**Comment by joshdanielson** [comment]
@iagosrl just tested on dev and seems to be working just fine for email but did not see it show up in the client card (yet) but you haven't checked that as complete yet :)

**Comment by IagoSRL** [comment]
@joshdanielson I'm putting the phone and email as a second line at the appointment card, but don't find the current "format as in a confirmed booking" (at the webapp, even a confirmed booking don't show up that client details... or where?)

**Comment by joshdanielson** [comment]
@iagosrl not sure if it was always missing... I guess add it if it’s easy.

**Comment by IagoSRL** [comment]
Pushed to *dev* right now changes to show up phone and email (with links) about the client at the appointment card. @joshdanielson please test!

**Comment by joshdanielson** [comment]
@IagoSRL tested and working! Thank you.
