### ISSUE TITLE
Bug S1 - Live Site: Error when signing up

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#880]
### Bug Description
Getting a bug when creating a new user after clicking sign-up:
![screen shot 2018-08-14 at 12 16 16 pm](https://user-images.githubusercontent.com/1202838/44113202-23db2f36-9fbc-11e8-9b37-eb757aa78838.png)

**Comment by IagoSRL** [comment]
Signups run successfully, but welcome activity fails initializing, located a template error., fixing

**Comment by IagoSRL** [comment]
It's released to live! (app v 1.13.4)
