### ISSUE TITLE
Bug S1 Live Site: Load Service Error

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#881]
### Steps to reproduce:
1. go to book professional: https://loconomics.com/#!booking/1186/308
2. This appears:
![screen shot 2018-08-28 at 12 11 32 pm](https://user-images.githubusercontent.com/1202838/44745118-a5ad3b80-aabb-11e8-8764-4f72c37d6e5b.png)

**Comment by IagoSRL** [comment]
Found the problem source, a change making the activity to an ES6 class and using it as the activity itself (the new pattern) but this was a special complex case, when was extending another class for the content methods, with three levels of hierarchy (ViewModel<-NewClientBookingCardVM<-BaseClientBookingCardVM). The prototype chain was broken, have the solution

**Comment by IagoSRL** [comment]
Fix it's at *dev* for testing.

**Comment by IagoSRL** [comment]
There was a deploy error, now is at dev properly
