### ISSUE TITLE
Bug S1: Add Profile Photo alert not working

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#884]
### Bug Description
After adding my profile photo, the alert does not complete and my listing is still not active:
![screen shot 2018-09-27 at 7 44 23 am](https://user-images.githubusercontent.com/1202838/46154098-4ca30580-c229-11e8-9c87-233b17260c1f.png)

**Comment by joshdanielson** [comment]
@IagoSRL it disappeared after a minute or two. Not sure why it took a while.

**Comment by IagoSRL** [comment]
It was a cache invalidation error, fixed, pushed to *dev* in between
