### ISSUE TITLE
Add "Copy listing URL" button to /listingEditor

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#885]
### Long Description
Right now there is no way for the professional to find the URL of their listing to share with clients (not sure when we hid the bookMebutton). A quick fix is to add a "Copy listing URL" button to the /listingeditor navigation as a primary button with white font/border (in the nav) with a link (in a new tab) to their live listing.

#### To-do:
- [ ] add button with link here (responsive, button will just be below the rest still in the teal background):
![screen shot 2018-09-27 at 7 56 50 am](https://user-images.githubusercontent.com/1202838/46155044-4ca40500-c22b-11e8-98d1-15a5fe741e58.png)

@IagoSRL I changed my mind and think the button should be "Copy listing URL" - please revise the text from the screenshot.

**Comment by IagoSRL** [comment]
The bookMeButton was hidden one year ago with the accessibility review, opening #645 ([commit](https://github.com/loconomics/loconomics/commit/bf86e118cb1c8d84c46ae914a50051f61447d753)). There is a related/duped at #699.

**Comment by IagoSRL** [comment]
This is implemented, pushed to dev and live along with tested progress updates from #460 (it's getting deployed, Slack will notice it in a few minutes when it ends)
