### ISSUE TITLE
Bug: S2 Switching job titles on profile throws exception

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#94]
Produced only on https://loconomics.com
Reported by Daniel Fields

## Firefox 

1. Navigate to Daniel Field's marketplace profile: https://loconomics.com/#!/profile/1263. He has two job titles, Massage Therapist (default) and Hydration Specialist.
3. Click on Hydration Specialist next to his profile photo

This causes the following exception:

![fields-profile-exception](https://cloud.githubusercontent.com/assets/6644016/21703840/df1f32e0-d369-11e6-8728-f21f410a264d.png)

After this error, both job titles are visible as links next to the profile photo. The expected behavior is that the Job Title header and the job title as a link would switch back and forth as you navigate between them.

Here's the callstack on live. 

![callstack](https://cloud.githubusercontent.com/assets/6644016/21704564/1b34a3e6-d36f-11e6-9341-6b6694bb2abc.png)

My suspicion is that this may be triggered because the Hydrologist job title does not have any services that have a fee. The issue starting in models/PublicUserJobTitle: minServiceValue.

![fields-profile-two-links](https://cloud.githubusercontent.com/assets/6644016/21703798/838abd28-d369-11e6-8519-a3f055e103a2.png)

## Chrome

We get a different exception in Chrome:

![chrome-exception](https://cloud.githubusercontent.com/assets/6644016/21738497/b379fa54-d43a-11e6-9d9a-0ed243c7fb7d.png)

**Comment by situatedbit** [comment]
Here's the callstack on live. 

![callstack](https://cloud.githubusercontent.com/assets/6644016/21704564/1b34a3e6-d36f-11e6-9341-6b6694bb2abc.png)

My suspicion is that this may be triggered because the Hydrologist job title does not have any services that have a fee. The issue starting in models/PublicUserJobTitle: minServiceValue.

I'm trying to confirm this locally.

**Comment by situatedbit** [comment]
I can reproduce this locally. The problem is in models/PublicUserJobTitle findMinValue and minServiceValue. It is triggered when a job title does not have a service that has a price above 0 or a priceRate set (for consultations). I plan to fix this on Monday.

**Comment by situatedbit** [comment]
issued pull request to fix this issue: #97

**Comment by IagoSRL** [comment]
@situatedbit Uploaded fix to *live*. I tried the profile link and works fine, please quick double check it you too.

@situatedbit , @joshdanielson : I tagged this as release 1.2.1, needs upload to stores since it affects apps too.

**Comment by situatedbit** [comment]
@IagoSRL I confirmed that it works on live with Firefox and Chrome

**Comment by IagoSRL** [comment]
Too: It works for me on Firefox and Chrome on Windows 7.

Thanks @situatedbit for the work! You can notify the fix to the user.

Closing.
