### ISSUE TITLE
Bug: S2 Consultation price rate looks like price of consultation

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#98]
Site: live

When professionals create free consultations, but set their price rate (for other services) above $0, then in several places the consultation looks like it costs as much as the starting rate. 

To reproduce:
1. as a professional, create a free consultation pricing and set the field _my rates start at_ to be a value above $0.

In the following places, that consultation pricing (which should be free) looks like it costs as much as the _my rates start at_ value. However, during the booking process, this value is _not_ added to the total cost of the booking (as expected).

1. Professional services screen
2. Marketplace profile
3. Client booking process

Here are the relevant screenshots:

Creating the pricing:
![01-create-pricing](https://cloud.githubusercontent.com/assets/6644016/21788741/3a6e2174-d685-11e6-8737-7cf311c35312.jpg)

Service Professional Services:
![02-service-professiona-services](https://cloud.githubusercontent.com/assets/6644016/21788756/4a341e06-d685-11e6-90cc-b487b0c49a9f.jpg)

Marketplace Profile:
![03-marketplace-profile](https://cloud.githubusercontent.com/assets/6644016/21788767/51b64ef6-d685-11e6-851b-442edd98129f.jpg)

Marketplace Profile (_is this value correct? Should it reflect the cost of the consultation or the other services?_):
![04-marketplace-profile](https://cloud.githubusercontent.com/assets/6644016/21788781/6a5eeefe-d685-11e6-8784-e2d57f125ae3.jpg)

Booking Request:
![05-booking-request](https://cloud.githubusercontent.com/assets/6644016/21788787/7167e5c0-d685-11e6-86e4-6b9bec95fbd6.jpg)

Booking Request Total:
![06-booking-request-total](https://cloud.githubusercontent.com/assets/6644016/21788789/7a117966-d685-11e6-9f71-debe111e43d6.jpg)

**Comment by situatedbit** [comment]
I saw this confusion again when working with a user this past week. It appears that the consultation has two prices. We need to fix the language and explain what the intention of a _consultation_ is as a particular type of item.

**Comment by joshdanielson** [comment]
This was fixed as part of the accessibility release. Closing.
